### ISSUE TITLE
move project to GitHub

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#1022]
(Original issue 1318 created by None on 2017-01-22T17:56:40.168729+00:00)

I'm finding it difficult to contribute to this project, because Bitbucket has a crappy UI.

**Comment by Anteru** [comment]
(Original comment by birkenfeld on 2017-01-22T18:16:51.233954+00:00)

Hello Anonymous,

while I've since grown to prefer git/github as well, in my opinion Bitbucket's UI is usable enough, you're just less accustomed to it. Migrating a project is always quite a daunting task, especially since pull requests cannot be transferred, and while issues can be, their owners will be gone. (Plus not only the hosting provider but also the repo itself has to be migrated to git.)

So if a migration is to be made (and note that I'm not closing this issue), it'll have to be timed so that a minimum of PRs and open issue properties are lost.

**Comment by Anteru** [comment]
(Original comment by alanhamlett on 2017-02-20T19:22:34.855295+00:00)

Any progress on this? I also find contributing difficult. I would probably become a regular contributor if this project was on GitHub...

https://github.com/alanhamlett

**Comment by birkenfeld** [comment]
@alanhamlett well, in the end this has happened after all, due to the stupidity of Bitbucket management :-|
