### ISSUE TITLE
re.match causes re.MULTILINE to be a noop

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#1056]
(Original issue 1352 created by alanhamlett on 2017-06-08T06:43:07.775020+00:00)

A lot of lexers use `re.match` with `re.M`/`re.MULTILINE`, but `re.M` doesn't actually match start of lines unless used with `re.search`.

This is causing poor Lexer accuracy and probably some edge-case bugs.

**Comment by Anteru** [comment]
(Original issue was assigned to birkenfeld)

**Comment by Anteru** [comment]
(Original comment by alanhamlett on 2017-06-08T06:46:14.062244+00:00)

For example, using `re.match` here causes Matlab files with comments on the second line to be identified as Objective-C:
https://bitbucket.org/birkenfeld/pygments-main/src/7941677dc77d4f2bf0bbd6140ade85a9454b8b80/pygments/lexers/matlab.py?at=default&fileviewer=file-view-default#matlab.py-137

Changing to `re.search` correctly detects Matlab files with comments on lines other than the very first line.

**Comment by alanhamlett** [comment]
Glad to see this issue imported, should I create a PR to replace incorrect usages of `re.match` with `re.search` in lexers?

**Comment by Anteru** [comment]
Yes please! :) That would be most welcome!

**Comment by alanhamlett** [comment]
Just created #1388. Turns out it was only 4 files... not a lot but still an improvement.
