### ISSUE TITLE
Support for css variables (aka custom properties)

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#1060]
(Original issue 1356 created by aleray on 2017-06-15T22:15:43.804108+00:00)

Hi,

I noticed that the css lexer doesn't support yet css custom properties like this:

```
#!css

:root {
    --page-width: 148.5mm;
    --page-height: 210mm;

    --margin-top: 30mm;
    --margin-right: 20mm;
    --margin-bottom: 30mm;
    --margin-left: 20mm;

    --column-count: 2;
    --column-gap: 9pt;
}
```

Is this something planned somehow?

Thanks!

**Comment by Anteru** [comment]
(Original issue 1356 last updated on 2019-05-24T19:59:09.397047+00:00)

(Issue automaticaly closed due to status in Bitbucket: resolved)

**Comment by Anteru** [comment]
(Original comment by sloria on 2017-12-24T16:56:50.451309+00:00)

This would be excellent.

As a workaround, I've been using `javascript` for blocks that use custom properties, and it usually ends up looking OK.

```javascript
:root {
    --page-width: 148.5mm;
    --page-height: 210mm;

    --margin-top: 30mm;
    --margin-right: 20mm;
    --margin-bottom: 30mm;
    --margin-left: 20mm;

    --column-count: 2;
    --column-gap: 9pt;
}
```

Works for now, but I'd love to see support in the CSS lexer, especially since custom properties are now supported in every major browser.

**Comment by Anteru** [comment]
(Original comment by SylvainCorlay on 2019-04-30T18:49:21.389031+00:00)

Hi All,  

This is my first post here. I am very interested in allowing CSS variables in `pygments` styles.

The motivation is that we use `pygments` in Jupyter \(in Jupyter/nbconvert\) and I am creating a nbconvert theme that outputs HTML including JupyterLab CSS variables.  
  
Simply allowing CSS variables in `colorformat` to pass through appears to be doing the job.

Thanks,

**Comment by Anteru** [comment]
(Original comment by Anteru on 2019-04-30T19:28:36.952407+00:00)

Hi, this does indeed sound like an interesting feature. Would you be interested in providing a PR for this? Unfortunately I don’t have the bandwidth to extend the lexers at the moment.

**Comment by Anteru** [comment]
(Original comment by SylvainCorlay on 2019-05-01T16:29:16.428786+00:00)

OK, I am looking into it.  
  
In short, since colors can now include formulas like `calc(var() * 2 - 20px)`, we need to let any value pass through the color validation, and always include the `#` in the colors, instead of prefixing them later on.

**Comment by Anteru** [comment]
(Original comment by SylvainCorlay on 2019-05-02T10:22:53.386295+00:00)

@Anteru I opened a simple pull request to allow styles to make use of CSS variables.

**Comment by Anteru** [comment]
(Original comment by Anteru on 2019-05-02T10:31:19.208437+00:00)

Thanks, I’ll try to get it merged for 2.4 :slight_smile:

**Comment by Anteru** [comment]
(Original comment by SylvainCorlay on 2019-05-02T11:53:51.146360+00:00)

That would be great! This is the only blocker for me. Is 2.4 scheduled soon?

In the mean time, I will manually include the CSS generated by my patched version.

**Comment by Anteru** [comment]
(Original comment by Anteru on 2019-05-02T12:12:09.730663+00:00)

Yes, soon™ :wink: Don’t be surprised this is not closing, as I’ll keep this bug open because the issue you’re reporting is different from the issue the original poster reported.

**Comment by Anteru** [comment]
(Original comment by SylvainCorlay on 2019-05-08T21:01:57.341766+00:00)

> Yes, soon™ :wink: Don’t be surprised this is not closing, as I’ll keep this bug open because the issue you’re reporting is different from the issue the original poster reported.

Hi @{557058:34fc1567-22c0-457a-baf3-b49341033f1c} I saw that you tagged 2.4, but it does not include the PR fixing this issue. Is there a chance that it gets into a release soon or should we look for a workaround?

**Comment by Anteru** [comment]
(Original comment by Anteru on 2019-05-09T05:01:20.087624+00:00)

Args, I missed it, sorry about that. I’ll get a 2.4.1 out within two weeks with this, if that’s ok for you in terms of waiting time.

**Comment by Anteru** [comment]
(Original comment by SylvainCorlay on 2019-05-09T10:05:24.692845+00:00)

Thanks for merging @{557058:34fc1567-22c0-457a-baf3-b49341033f1c} . I am looking forward for the 2.4.1. I will definitely not get into dirty workarounds if you it is released in the next couple of weeks!

**Comment by Anteru** [comment]
(Original comment by Anteru on 2019-05-21T16:31:18.649507+00:00)

Fixed in PR#814.

**Comment by Anteru** [comment]
(Original comment by SylvainCorlay on 2019-05-23T22:07:06.099379+00:00)

Hey @{557058:34fc1567-22c0-457a-baf3-b49341033f1c} , would you guys consider tagging a patch release including this?

**Comment by Anteru** [comment]
(Original comment by Anteru on 2019-05-24T19:18:08.322653+00:00)

Yes, we considered it, and hopefully we just released 2.4.1 without forgetting this patch :slight_smile:

**Comment by Anteru** [comment]
(Original comment by SylvainCorlay on 2019-05-24T19:59:09.378714+00:00)

Thanks @{557058:34fc1567-22c0-457a-baf3-b49341033f1c} this is great news!

**Comment by zjeffer** [comment]
@Anteru Any updates for this? I'm on 2.4.2 and the css lexer still highlights css vars as errors.

**Comment by Anteru** [comment]
No update, and I just verified it doesn't work with 2.7.3. Are you interested in preparing a PR to resolve this?

**Comment by zjeffer** [comment]
Thanks for the quick reply. 

I'll see what I can do.
