### ISSUE TITLE
Add Python 3 specialization for console lexer

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#1062]
(Original issue 1358 created by PavloKapyshin on 2017-06-26T14:48:08.562150+00:00)

Currently `pygments.lexers.python.PythonConsoleLexer` uses Python 2 by default. Python 3 support requires special handling, e.g. allowing to pass options to lexer or faking pycon3 with a conditional.

Maybe other users of pygments will also benefit from having specialization of `PythonConsoleLexer` that uses just Python 3—`pycon3`?

**Comment by birkenfeld** [comment]
Python 3 is now the default.
