### ISSUE TITLE
MySQL Variable support

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#1063]
(Original issue 1359 created by None on 2017-06-26T16:12:03.533437+00:00)

It appears that the mysql lexer doesn't include support for variables in SQL / MySQL. The '@' prefix is highlighted as an operator, rather than as part of the name.

Example: http://pygments.org/demo/1808073/

Doc: https://dev.mysql.com/doc/refman/5.7/en/user-variables.html

**Comment by kurtmckee** [comment]
I'm overhauling the MySQL lexer, and improved variable support (including all variants of quoting) is already handled in my branch. PR coming after I've written automatic keyword update code a-la the Postgres builtins, as well as unit tests.
