### ISSUE TITLE
Monokai traceback highlighting

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#1081]
(Original issue 1377 created by None on 2017-09-18T16:10:11.047702+00:00)

Hi,

can you please help me modifying the molokai theme such that it renders more readable stacktraces in qt console?

Please see this SO post for details: https://stackoverflow.com/questions/46023242/how-to-change-monokai-pygments-style-in-qtconsole-with-jupyter

**Comment by Anteru** [comment]
(Original comment by marcel_liker on 2017-09-18T16:11:43.516919+00:00)

Sorry, forgot to login before posting

**Comment by kdeldycke** [comment]
Python tracebacks are properly rendered with Monokai theme on my blog, which relies on Pygments 2.7.2:
* https://kevin.deldycke.com/2015/11/pip-install-ssl-error/
* https://kevin.deldycke.com/2010/09/convert-lotus-notes-nsf-files-mbox-nlconverter/
* https://kevin.deldycke.com/2010/09/ultimate-guide-lotus-notes-mail-migration/

So I guess this issue can be closed.
