### ISSUE TITLE
Add a way to preview the styles

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#1098]
(Original issue 1394 created by Merwok on 2017-11-10T16:12:54.415812+00:00)

In the docs for Sphinx, it is very useful to see screenshots for all the themes, instead of having to try them one by one and rebuild.  It would be great to have something similar for Pygments styles.

This could be a simple change to the docs to include static images, or a change to the demo pastebin app to let people select style in addition to lexer.

**Comment by birkenfeld** [comment]
> This could be a simple change to the docs to include static images, or a change to the demo pastebin app to let people select style in addition to lexer.

They can.
