### ISSUE TITLE
Apparent missing unicode support for Coq

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#1099]
(Original issue 1395 created by None on 2017-11-20T15:15:33.554027+00:00)

The following is accepted by the Coq compiler, but raises errors in pygments.

```
#!coq
Definition logeq_both_false {X Y : UU} : ¬X -> ¬Y -> (X <-> Y).

```
Unicode is supported by coq and used widely.

**Comment by Anteru** [comment]
(Original comment by JasonGross on 2019-05-06T00:55:49.289012+00:00)

Duplicate of [https://bitbucket.org/birkenfeld/pygments-main/issues/971/unicode-in-coq-files-marked-as-error-with](https://bitbucket.org/birkenfeld/pygments-main/issues/971/unicode-in-coq-files-marked-as-error-with) ?

**Comment by birkenfeld** [comment]
duplicate, new issue is #678
