### ISSUE TITLE
asciidoctor and pygments not working under cygwin64

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#1102]
(Original issue 1398 created by None on 2017-11-30T09:08:40.908992+00:00)

I will simply quote [this post](http://discuss.asciidoctor.org/asciidoctor-and-pygments-not-working-under-cygwin64-td5212.html):

“when i try and generate a html file by running asciidoctor test.adoc ... i get no output and the task keeps running and running and running without generating any output”

Further in the page, someone suggests that using the older 0.6.3 version would solve the issue under Windows, and indeed it does:

“The pygments.rb recently underwent an internal change to support Ruby >= 2.4 and JRuby. It no longer uses posix/spawn to invoke Python. Now it just uses popen4. There's a chance this change has caused a problem on Windows.”

**Comment by birkenfeld** [comment]
Not sure what we can do about this...
