### ISSUE TITLE
Support JavaScript modules extension *.mjs

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#1120]
(Original issue 1416 created by alanhamlett on 2018-02-07T05:31:22.045990+00:00)

More info on this extension:
https://nodejs.org/api/esm.html

If someone with merge permission wants, I'll create a PR.

**Comment by Mesteery** [comment]
This can be closed (https://github.com/pygments/pygments/pull/1392).

**Comment by Anteru** [comment]
Thanks, good find!
