### ISSUE TITLE
Matlab double quoted string is not highlighted

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#1124]
(Original issue 1420 created by None on 2018-03-01T18:25:18.198712+00:00)

Matlab double quoted string is not highlighted. Matlab now supports double quoted strings. It is very desirable that such strings are highlighted.

a = 'string'  => this is highlighted

b = "string" => this is NOT highlighted

**Comment by wallysalami** [comment]
Any updates on this issue?

**Comment by Anteru** [comment]
No progress yet -- please note this is an imported issue from ~1.5 years ago :) I'll see what I can do about it. Do you have a sample Matlab code showing this issue?

**Comment by wallysalami** [comment]
```matlab
text1 = 'Hello world';
text2 = "Hello world";
```

Github identifies both notations as strings, but pygments does not recognise the second one, which was introduced in 2017.

I wrote a small correction in `pygments/lexers/matlab.py` that fixes the issue. Can I make a pull request for the master branch, or should I create a new one?

**Comment by Anteru** [comment]
If you have a PR for master, that works for me :)
