### ISSUE TITLE
Error in documentation for the token Keyword.Constant

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#1131]
(Original issue 1427 created by Beafantles on 2018-03-11T14:30:46.885382+00:00)

Hello,

It seems there's an error in the documentation regarding the builtin tokens.  In this [page](http://pygments.org/docs/tokens/), we can see:

![Keyword.Constant](https://i.imgur.com/44JvuoG.png)

However, `Keyword.Constant` doesn't seem to affect the keyword `None` in Python. `Name.Builtin` does.

Here's an example code:

```
#!python
from pygments import highlight
from pygments.lexers import get_lexer_by_name
from pygments.formatters import ImageFormatter
from io import BytesIO
from PIL import Image
from pygments.style import Style
from pygments.token import Keyword, Name


class Style1(Style):
    styles = {
        Keyword.Constant: "#ff0000"
    }


class Style2(Style):
    styles = {
        Name.Builtin: "#ff0000"
    }


code = "a = None"

lexer = get_lexer_by_name("python")

formatter_1 = ImageFormatter(style=Style1)
formatter_2 = ImageFormatter(style=Style2)

result_1 = highlight(code, lexer, formatter_1)
result_2 = highlight(code, lexer, formatter_2)

im_1 = Image.open(BytesIO(result_1))
im_2 = Image.open(BytesIO(result_2))

im_1.save("image_1.png")
im_2.save("image_2.png")
```

Here's `image_1.png`: ![image_1.png](https://bitbucket.org/repo/baqM/images/1560290171-image_1.png)

Here's `image_2.png`: ![image_2.png](https://bitbucket.org/repo/baqM/images/1431215169-image_2.png)

**Comment by birkenfeld** [comment]
None in Python3, not Python2 :)
