### ISSUE TITLE
Lua lexer broken in 2.2.0

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#1145]
(Original issue 1441 created by katsterling on 2018-05-03T20:12:09.035223+00:00)

Pygments does not style Lua code at all. I believe this is due to a syntax error in the Lua lexer.

```
pygmentize -H lexer lua
```
Also throws a syntax error (with no useful information) while other lexers appear to work fine.

**Comment by Stanzilla** [comment]
You mean this one?

`File "test.py", line 236, in get_newest_version
    m = r.match(line)
TypeError: cannot use a string pattern on a bytes-like object`

**Comment by Anteru** [comment]
Sorry, I'm a bit lost here -- what does the comment refer to to? This is a ported issue from Bitbucket from 2018, so I suspect it's no longer relevant. I don't know what PDFs or gz you're referring to.

**Comment by Stanzilla** [comment]
Oh I mean the issue is still true. the script in the lua lexer is still broken, just won't be an easy fix.

**Comment by Anteru** [comment]
Cannot reproduce -- Lua highlighting seems to work just fine.

**Comment by Stanzilla** [comment]
The websites the script uses to gather info don't even exist anymore so I'd say that on its own is a problem
