### ISSUE TITLE
Python source code not getting detected

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#1146]
(Original issue 1442 created by amalmurali47 on 2018-05-09T10:05:31.823334+00:00)

Thank you for the great work on this library! The issue I've discovered is that guess_lexer() is not finding this  (among other snippets) as Python source code:

```
out=open('assignment.in', 'w').write

n = 300

out('%d\n'%n)
for i in range(1, n + 1):
	out(' '.join('%d'%(i * j) for j in range(1, n + 1)) + '\n')
```

Or any of these:
 - https://pastebin.com/raw/aKbNPSkT
- https://pastebin.com/raw/Ubf9h0Ax
- https://pastebin.com/raw/JsPsMTtQ

etc. 

What _can_ it detect as Python source code? 
I'm trying to understand why. Could anyone please shed some light on this problem?

Thanks!

**Comment by Anteru** [comment]
(Original comment by amalmurali47 on 2018-05-09T10:08:14.247888+00:00)

Is it because of this condition in `lexers/python.py` line 240?

```
    def analyse_text(text):
        return shebang_matches(text, r'pythonw?(2(\.\d)?)?') or \
            'import ' in text[:1000]
```

**Comment by birkenfeld** [comment]
Not every small snippet can be detected successfully.  We don't have a neural network for guessing (yet... :smile:)
