### ISSUE TITLE
Javascript lexer misclassifies `async`

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#1150]
(Original issue 1446 created by Xavdidtheshadow on 2018-06-14T05:05:44.112262+00:00)

Hi there!

When using the JS lexer, the "await" keyword is listed as "Token.Name.Other" rather than "Token.Keyword.Reserved". This extends to other related tokens, such as "async"

My test input was:

```
#!javascript

const j = async () => await Promise.resolve(3)
```

**Comment by Anteru** [comment]
(Original comment by peterbe on 2019-02-06T15:31:12.023318+00:00)

Demonstrated here: http://pygments.org/demo/6783285/

**Comment by Anteru** [comment]
(Original comment by jonluca on 2019-02-16T04:50:23.374630+00:00)

There is also an ancillary issue to JavaSript's `async` keyword - it's incorrectly colored when it is the name of a variable in a function definition, as below:

```
function testFunc(param1, param2, async){
    // do something
}
```


An example can be found [here](https://blog.jonlu.ca/posts/illegal-streams), near the bottom of the page, at `    XMLHttpRequest.prototype.open = function (method, url, async, user, pass)`.

**Comment by Domiii** [comment]
Pygment's JavaScript support is evidently very weak and has not been updated in a long time (and apparently, [there is little interest in this either](https://github.com/pygments/pygments/issues/1165)). Forces me to switch from `minted` to `listings` for my writing needs.

Great project, but insufficient for my use case :/

**Comment by Anteru** [comment]
We are quite interested in improving any lexer -- but we don't have the bandwidth nor the knowledge of all languages to do it, so we rely on the community to contribute. Would you mind preparing a PR for the issues you're facing? I'll be happy to review it so we can get it integrated into Pygments.

**Comment by Domiii** [comment]
I just checked and it does list `async` and `await` as keywords.

Not sure why it did not highlight them? I used v2.7.3.

[Here](https://github.com/pygments/pygments/blob/190717d1eb5c1b29cf3cf28d7ccc7db3e1f366f7/pygments/lexers/javascript.py#L84) it is in the lexer.

**Comment by xavdid** [comment]
(I'm the OP from bitbucket)

Looks like this was fixed in https://github.com/pygments/pygments/pull/1605. I had no idea it was so straightforward or I would have just done it back in 2018 🙈

Thanks a bunch!

![](https://cdn.zappy.app/7a3c28b3cf0530bf6cb90ab13865ad12.png)

**Comment by Anteru** [comment]
@xavdid Thanks! :) Given it was merged 29 days ago, that means it should be in 2.7.3 -- @Domiii , can you please double-check you're using 2.7.3?

**Comment by Domiii** [comment]
Ok, I found the problem. I assumed it was using my `pip`-installed version, but it in fact used some version that was installed by Anaconda and of the wrong version. Apologies!
