### ISSUE TITLE
Ability to change Json boolean colors

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#1158]
(Original issue 1454 created by galindro on 2018-06-25T12:54:29.584464+00:00)

I want to display true and false values of a boolean json object in different collors: when true, it must be green. If false, it must be red. How could I do this?

Reading source code, I've noticed that [here](https://bitbucket.org/birkenfeld/pygments-main/src/7941677dc77d4f2bf0bbd6140ade85a9454b8b80/pygments/lexers/data.py#lines-463), true, false and null values are threated as Keyword.Constant keywords. So, I think that because of this, it is impossible to make a custom colorscheme mapping in TerminalFormatter for each boolean situation. Am I right?

**Comment by kurtmckee** [comment]
@Anteru do you want me to implement this? I anticipate that I can add children to the existing `Keyword.Constant` token types. Perhaps something like:

* `Keyword.Constant.True`
* `Keyword.Constant.False`
* `Keyword.Constant.Null`

I seem to recall that if the token is exactly recognized by the style then it'll be used...but if it isn't, then its parent will be. If you want, I'll try this out and confirm. Then this bug could be closed.

**Comment by Anteru** [comment]
@kurtmckee Feel free to add this, I've recently fixed a bug related to lookups not working properly and that should be solved now for all formatters. It will require a new style though to use.

**Comment by kurtmckee** [comment]
> I've recently fixed a bug related to lookups not working properly

Hot dog!

> It will require a new style though to use.

Understood. I don't anticipate adding such a style change myself, just simply allowing users like galindro (who originally reported this) to implement this as they see fit.

I'll submit a PR outside of work hours. :smile:

**Comment by birkenfeld** [comment]
Ok.
