### ISSUE TITLE
Add Enaml lexer to pygments

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#1178]
(Original issue 1474 created by None on 2018-09-13T00:41:12.052048+00:00)

Hi, 

Enaml is a declarative language to generate GUI built on top of Python. The project https://github.com/nucleic/enaml includes a pygments lexer (tools/pygments). This lexer is now available on PyPI as enaml-pygments.

As a maintainer of enaml I would be interested in getting it included in Pygments itself. Would you be interested and how should I proceed ?

**Comment by Anteru** [comment]
(Original comment by mdartiailh on 2018-09-13T00:42:39.880538+00:00)

Sorry I forgot to log in before posting.

**Comment by birkenfeld** [comment]
I'm closing all requests for lexers/formatters without a patch/PR.
