### ISSUE TITLE
Type hints

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#1189]
(Original issue 1485 created by The-Compiler on 2018-11-26T15:24:35.119863+00:00)

I recently started using [mypy](http://mypy-lang.org/) with my [project](https://www.qutebrowser.org/) and it says *"No library stub file for module 'pygments'"* (same for `pygments.lexers` and `pygments.formatters`).

Do you have any plans to introduce type annotations for pygments? Those could be done in the code as comments, as a [separate stub file](https://mypy.readthedocs.io/en/latest/stubs.html#stub-files), or (whenever Python 2 support is dropped), with a proper annotation syntax.

Also, thanks a lot for pygments! I've been using it for a while now, and never had any trouble with it.

**Comment by Anteru** [comment]
(Original comment by birkenfeld on 2018-11-26T15:34:58.769385+00:00)

Thanks for the kind words :)

Personally, I have no plans to introduce type hints; I haven't worked with them so far. I'm not opposed to it, but it's possibly a better time to do that after 2.7 gets unsupported and we can just use the proper syntax throughout.

**Comment by birkenfeld** [comment]
Not going to happen with out a PR (and as said, probably after 2.7 is unsupported).

**Comment by Akuli** [comment]
I might want to work on this (but don't get too excited, I might change my mind and decide to just live with `# type: ignore` comments).

Is it preferred to have type hints in `.py` files with rest of the code or in separate `.pyi` files?
