### ISSUE TITLE
Lexing Support for HTTP/2

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#1190]
(Original issue 1486 created by ocket8888 on 2018-12-05T01:32:24.460808+00:00)

the HTTPLexer only supports HTTP/1, but HTTP/2 is quite mature and in fact most major web browsers already support HTTP/3. I'm not sure what extra work that would entail, but at the very least it shouldn't cause a failure to lex if the protocol version isn't `1.1`. For example, `HTTP/2 204\r\n\r\n` is a totally valid HTTP/2 response, but will fail to pass through the lexer (for serveral reasons).

**Comment by birkenfeld** [comment]
`HTTP/2` and `3` are now supported.
