### ISSUE TITLE
Remove nose dependency

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#1194]
(Original issue 1490 created by mcepl on 2019-01-10T01:08:06.625515+00:00)

nose seems to me mostly obsolete and dead project (even its own maintainers seem to move to its successor). Moreover, it seems to be mostly unnecessary now, at least as far as the code itself is concerned by API provided by the very standard library of Python even in the version 2.7. Therefore, dependency on nose is no longer necessary and thus advisable.

This attached patch suggests removal of this dependency (I am sorry, with all due respect, I really have hard time to fight with Mercurial, so I am just attaching patch to this issue).

Thank you for considering this issue.

**Comment by Anteru** [comment]
(Original comment by Anteru on 2019-04-01T15:10:30.799951+00:00)

Hey, thanks for this patch! While this does apply cleanly, it seems to break a bunch of tests, in particular make test doesn't work afterwards. I tried to fix this manually, but there are two failures related to the cmdline I can't quite decipher. Did you try running the tests suites with this patch applied?

**Comment by Anteru** [comment]
(Original comment by mcepl on 2019-04-01T19:48:35.883659+00:00)

Refreshed patch. This should really work against Pygments-2.3.1 tarball.

**Comment by Anteru** [comment]
(Original comment by mcepl on 2019-04-02T07:00:22.422946+00:00)

One more thing: get rid of ``tests/run.py``. In times when you wrote it, it could make sense to have your own test runner, but it certainly doesn't any more. Use ``python -munittest discover``, use ``pytest``, heck use even ``nosetests``, but there are so many more stable, mature, and maintained test runners in Python, that it is just silly to maintain your own.

**Comment by Anteru** [comment]
(Original comment by Anteru on 2019-04-02T12:18:04.314313+00:00)

Thanks for the updated patch! Not sure what I'm doing wrong here, but running this yields:

```
.......................
======================================================================
FAIL: test_F_opt (tests.test_cmdline.CmdLineTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/disk1/work/dev/bitbucket/pygments-main/tests/test_cmdline.py", line 185, in test_F_opt
    '-fhtml', filename)
  File "/media/disk1/work/dev/bitbucket/pygments-main/tests/test_cmdline.py", line 72, in check_success
    self.assertEqual(err, '')
AssertionError: '/usr/lib/python3.6/importlib/_bootstrap_e[200 chars]g)\n' != ''
- /usr/lib/python3.6/importlib/_bootstrap_external.py:426: ImportWarning: Not importing directory /home/anteru/.pyenv/pygmentum/lib/python3.6/site-packages/sphinxcontrib: missing __init__
-   _warnings.warn(msg.format(portions[0]), ImportWarning)


======================================================================
FAIL: test_outfile (tests.test_cmdline.CmdLineTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/disk1/work/dev/bitbucket/pygments-main/tests/test_cmdline.py", line 115, in test_outfile
    self.check_success(*opts)
  File "/media/disk1/work/dev/bitbucket/pygments-main/tests/test_cmdline.py", line 72, in check_success
    self.assertEqual(err, '')
AssertionError: "/media/disk1/work/dev/bitbucket/pygments[145 chars]e)\n" != ''
- /media/disk1/work/dev/bitbucket/pygments-main/pygments/cmdline.py:548: ResourceWarning: unclosed file <_io.BufferedWriter name='/tmp/tmpcdefogyd'>
-   return main_inner(popts, args, usage)


----------------------------------------------------------------------
```

If you could help me get rid of that, I think there's no problem moving to unittest proper (at least for the 3.x builds, Python 2.7 might still require a separate test.)

Regarding the test runner, is that causing any problems? I haven't written it, but I suspect it's there for some reason, so I'd like to hear where it's falling short.

**Comment by Anteru** [comment]
(Original comment by birkenfeld on 2019-05-06T05:24:57.001806+00:00)

I agree, nose should be removed. We should just switch to plain pytest, without any special runners \(except a Make target for running it, for old time convenience sake\).

**Comment by Anteru** [comment]
(Original comment by birkenfeld on 2019-05-06T05:38:24.102561+00:00)

BTW, @{557058:5be7ed14-c3b5-44a9-81bf-bad9a9c917cc}

> that it is just silly to maintain your own

This is borderline disrespectful. If you have any open source project yourself, you know that a working status quo wins, as long as it doesn't break or someone volunteers to change it.

**Comment by birkenfeld** [comment]
Pytest migration branch is now merged.
