### ISSUE TITLE
Add support for the Oz language

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#1199]
(Original issue 1495 created by None on 2019-02-07T11:20:13.965965+00:00)

There currently is no support for the [Oz language](https://en.wikipedia.org/wiki/Oz_(programming_language)),
which would be nice to have.

**Comment by Anteru** [comment]
(Original comment by zzzannen on 2019-04-27T17:28:21.179909+00:00)

I notice that [Wikipedia page on Oz](https://en.wikipedia.org/wiki/Oz_(programming_language)#Functions) uses `erlang` to do the syntax highlight.

Is Oz sufficiently close to erlang to get away with using the pygments erlang lexer for Oz?

**Comment by birkenfeld** [comment]
I'm closing all requests for lexers/formatters without a patch/PR.
