### ISSUE TITLE
IRC highlighting too minimal

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#120]
(Original issue 341 created by None on 2008-06-19T16:39:04+00:00)

IRC highlighting would be much more useful if it did nick highlighting, specifically adding different colors for each nick.  

(I can imagine this might be outside the normal behavior of pygments, as it's very context-sensitive, but without it the highlighted logs aren't any more readable than the plain text logs.)

Reported by guest

**Comment by Anteru** [comment]
(Original comment by gbrandl on 2009-09-11T13:30:59+00:00)

Postponing.

**Comment by Anteru** [comment]
(Original comment by thatch on 2009-03-25T23:22:34+00:00)

The styles need to be referenced in some of the *formatters*, a typo in my previous post.  The 16-color terminal formatter doesn't read rgb values.  It might work to have them in the base style since you're not going to mix `Cycle` tokens with regular source code.

**Comment by Anteru** [comment]
(Original comment by gbrandl on 2009-03-15T21:56:31+00:00)

I don't have a better idea, but couldn't those styles be defined only once in the base Style?

**Comment by Anteru** [comment]
(Original comment by thatch on 2009-02-22T22:01:00+00:00)

Can you give this patch a try? For now it will only give good output on the original terminal lexer.

Georg, do you have a better suggestion than `Generic.Cycle.C[0..n-1]` for the token type?  I don't particularly look forward to adding this to each of the style definitions.

**Comment by Anteru** [comment]
(Original comment by thatch on 2008-12-31T03:14:54+00:00)

I should have time before 1.1 ships.

**Comment by Anteru** [comment]
(Original comment by gbrandl on 2008-11-15T17:32:11+00:00)

Tim, if you don't get to do this for 1.0, just move it to the next milestone.

**Comment by Anteru** [comment]
(Original comment by thatch on 2008-07-26T16:08:27+00:00)

We'd need to do a second pass to come up with the list of nicks.  Targeting to 0.12 since I'd like to get #340 ironed out first.

**Comment by kurtmckee** [comment]
It appears that this ticket was last updated 12 years ago. I recommend closing.
