### ISSUE TITLE
Support copy-paste of HTML output without Token.Generic.Prompt

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#1201]
(Original issue 1497 created by xhochy on 2019-02-13T09:19:56.617509+00:00)

In the case of using the HTMLFormatter together with the ipython lexer for formatting the following output, the leading characters are correctly formatted as `Token.Generic.Prompt`, i.e. they will be formatted as `<span class="gp">…</span>` in HTML.

```
In [3]: df = pd.DataFrame(
   ...:     {
   ...:         "A": 1.,
   ...:         "B": pd.Timestamp("20130102"),
   ...:         "C": pd.Series(1, index=list(range(4)), dtype="float32"),
   ...:         "D": np.array([3] * 4, dtype="int32"),
   ...:         "E": pd.Categorical(["test", "train", "test", "train"]),
   ...:         "F": "foo",
   ...:     }
   ...: )
```

We would like that users of our documentation can copy-paste the code examples without including the prompt part. This can be achieved by making the prompt part of the style instead of the actual text by replacing `<span class="gp">   ...: </span>` with `<span class="gp" data-marker="   ...: "></span>` and a CSS definition `span.gp::before { content: attr(data-marker); }`.

I would be happy to make a PR to add this as an option to the HTMLFormatter but I'm unsure what the correct approach would be to implement this.

**Comment by Anteru** [comment]
(Original comment by hhsprings on 2019-04-27T07:55:24.913109+00:00)

Does "[copybutton](https://docs.python.org/3/_static/copybutton.js)" help you? (See [actual examples](https://docs.python.org/3/tutorial/stdlib.html#dates-and-times.)) I think it would be useful for pygments to do what you want, but your target is html, so I think copybutton.js is also what you want. I myself use a [customized version](https://hhsprings.bitbucket.io/docs/programming/examples/ffmpeg/_static/copybutton.js) of this (which is used in [this document](https://hhsprings.bitbucket.io/docs/programming/examples/ffmpeg/index.html)). 

(Rather, I'm not happy because I think that the widely used copybutton.js won't work if your plan is adopted.)

**Comment by Anteru** [comment]
(Original comment by Anteru on 2019-07-20T09:43:51.588308+00:00)

Right, wouldn't this be better done by using some JavaScript to massage the HTML into what you need? Alternatively, can you subclass the HTML formatter and have one which does your specific change? I’m a bit reluctant to make it a generic option in Pygments unless there is more demand for this kind of CSS trickery.

**Comment by birkenfeld** [comment]
This is too specific to make it work for all cases, IMO.
