### ISSUE TITLE
Dockerfile file ending comments are not handled correctly

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#1211]
(Original issue 1507 created by errge on 2019-04-20T09:55:50.823911+00:00)

E.g.:

```
FROM node            # This is our base layer
ADD . /app           # But we add our app
RUN npm install      # And install dependencies
```

Looking into the lexer, the problem seems to be that we have matches like VOLUME .* matching to Keyword and String, but the .* part can contain the comment (#) "inside" the volume name.

I unfortunately don't know enough of the lexers to prepare a proper pull request, sorry about that!

**Comment by amitkummer** [comment]
Straight from the [Dockerfile docs](https://docs.docker.com/engine/reference/builder/#format):

> Docker treats lines that begin with # as a comment, unless the line is a valid parser directive. A # marker anywhere else in a line is treated as an argument.

Hence, the provided snippet does not actually contain any comments, which is probably why the Docker lexer wasn't doing what OP expected.

**Comment by birkenfeld** [comment]
Thanks for digging! Closing.
