### ISSUE TITLE
FontNotFound is not included in __all__ list in formatter.img

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#1224]
(Original issue 1520 created by vanyakosmos on 2019-06-01T18:08:50.799847+00:00)

**Comment by Anteru** [comment]
(Original comment by Anteru on 2019-06-22T19:08:54.840751+00:00)

That's consistent with the  other error messages and helper objects \( `FontManager`, `PilNotAvailable`, etc.\) Any reason why you want it include in `__all__`?

**Comment by birkenfeld** [comment]
We're actually using the `__all__` lists only for lexers/formatters in their respective modules.
