### ISSUE TITLE
Java Lexer: Name vs. Type

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#1227]
(Original issue 1523 created by miranska on 2019-06-06T22:56:11.168574+00:00)

Hi,  
This may be an RTFM issue, but I wonder if it is a bug or a feature. Consider this Java code snippet:

```java
String hw = "Hello, World";
```

I would expect that the `String` word would be recognized as `Type`. Instead, it is recognized as `Name`.

Here is a code snippet for the repro:

```python
from pygments import highlight
from pygments.formatters import RawTokenFormatter
from pygments.lexers.jvm import JavaLexer
src = 'String hw = "Hello, World";'
parsed_data = highlight(src, JavaLexer(), RawTokenFormatter())
print(parsed_data.decode('ascii'))
```

Output:

```
Token.Name	'String'
Token.Text	' '
Token.Name	'hw'
Token.Text	' '
Token.Operator	'='
Token.Text	' '
Token.Literal.String	'"Hello, World"'
Token.Operator	';'
Token.Text	'\n'
```

**Comment by birkenfeld** [comment]
Correctly lexing names vs. types in C-style declarations is a job for a parser, not a lexer.
