### ISSUE TITLE
Unicode not working for Python

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#1233]
(Original issue 1529 created by julienmalard on 2019-07-04T06:26:02.506969+00:00)

Pygments does not recognise variable names containing unicode characters as specified by Python’s PEP 3131 [https://www.python.org/dev/peps/pep-3131/](https://www.python.org/dev/peps/pep-3131/). This makes colouring of any code that is not written in English \(or Malaysian, to be fair\) crash.

**Comment by birkenfeld** [comment]
The Python3 lexer (now default) does support Unicode names.
