### ISSUE TITLE
get_lexer_for_filename performance issues

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#1241]
(Original issue 1537 created by cyrus-and on 2019-08-24T19:54:25.651180+00:00)

`get_lexer_for_filename` is so much slower than `get_lexer_by_name` even though AFAIK it only performs some string matching:

```
$ time python3 -c 'import pygments.lexers; pygments.lexers.get_lexer_for_filename("foo.c")'

real    0m0.938s
user    0m0.860s
sys     0m0.073s

$ time python3 -c 'import pygments.lexers; pygments.lexers.get_lexer_by_name("c");'

real    0m0.071s
user    0m0.054s
sys     0m0.016s
```

Since subsequent invocations do not exhibit this behavior, it hints \(pure speculation\) that maybe this is related to a Python import that gets cached after the first time:

```
$ time python3 -c 'import pygments.lexers; pygments.lexers.get_lexer_for_filename("foo.c"); pygments.lexers.get_lexer_for_filename("foo.c")'

real    0m0.907s
user    0m0.779s
sys     0m0.105s
```

**Comment by Anteru** [comment]
(Original comment by cyrus-and on 2019-08-24T20:07:16.991674+00:00)

Something weird:

* I tried in a clean Docker container on the same machine and the problem disappears \(or it is _fast enough_\);
* I tried on another equivalent machine and the problem is less severe \(300ms instead of 1s\) but still there.

**Comment by birkenfeld** [comment]
Well, this function needs to find all the plugin lexers provided by entry points. This can be an expensive operation depending on the number of installed packages and pkg_resources behavior.
