### ISSUE TITLE
Is this repo a mirror?

### ISSUE THREAD

**Issue by tzing** [pygments/pygments#1244]
Hi,
I realized that the link to the repository both on its official site and in readme file is still pointing to bitbucket, and it is a Mercurial repo.
But the commits/issues of this repo *seems* to be synced with the one on bitbucket.

Is this repo a mirror or the core maintainers is planing to move this project to github?
And- Should I send PR to one on bitbucket, or I could use this one?

**Comment by Anteru** [comment]
You should use this one. We're still in the process of updating the website and shutting down the original repo.

**Comment by tzing** [comment]
got it! thanks :)
