### ISSUE TITLE
Pygments demo page 404

### ISSUE THREAD

**Issue by noisytoken** [pygments/pygments#1252]
I use pygments demo page quite a bit to view how different styles look.

Right now the page https://pygments.org/demo/ gives 404 error.

why is that?

**Comment by birkenfeld** [comment]
Hi,

we've switched hosting of pygments.org to github pages, since the old site was a maintenance burden and potential legal liability.

It's pretty easy to try out styles from the command line, with the `full` option for the html formatter.

**Comment by definelicht** [comment]
If it's no big overhead for you, can you bring back the demo? I've relied on it for formatting code for Powerpoint slides for more than a year, so I was quite sad to see it go away. Using the CLI for this is rather clunky.

**Comment by birkenfeld** [comment]
Ok, I'm currently experimenting with simply embedding [pyodide](https://pyodide.readthedocs.io/) (which comes with Pygments already). Then all the work is done in the browser, and we don't have to provide anything on the server side.

So far it looks feasible.  If I succeed, it'll be live in a few days.

**Comment by Anteru** [comment]
How does pyodide reference packages? Can you just build a new version of the website with the latest development build of Pygments with that?

**Comment by birkenfeld** [comment]
If we don't want to use the bundled one (currently 2.3.1), there's also support for fetching and loading something from PyPI.

I could also look at their build process and build a new .js after tagging on CI. Now that the library is mature, I don't think the demo needs to reflect the development version anymore.

**Comment by Anteru** [comment]
Both options sound good to me -- we're releasing often enough that latest from PyPI should work. As long as it is somewhat up-to-date :)

**Comment by noisytoken** [comment]
> If it's no big overhead for you, can you bring back the demo? I've relied on it for formatting code for Powerpoint slides for more than a year, so I was quite sad to see it go away. Using the CLI for this is rather clunky.

https://thepythonguru.com/tools/pygments-demo/

**Comment by definelicht** [comment]
> https://thepythonguru.com/tools/pygments-demo/

Thanks for the pointer!

**Comment by noisytoken** [comment]
@birkenfeld 

Can you add the link to https://thepythonguru.com/tools/pygments-demo/ in the official docs?

**Comment by Anteru** [comment]
I'd rather not link to external pages which we don't control -- let's see if we can get the client-side preview to work and then we can re-evaluate.

**Comment by jpiggod** [comment]
Hope that the new demo page can be live soon too! I've also relied on the web demo page for highlighting codes for a long time...  But I'm really glad that developers are actively updating this - and thanks!! Looking forward to the good news :D

**Comment by birkenfeld** [comment]
Check it out at https://pygments.org/demo/ and let me know.

**Comment by birkenfeld** [comment]
Closing this for now.
