### ISSUE TITLE
API to get the current state?

### ISSUE THREAD

**Issue by laixintao** [pygments/pygments#1254]
Hi, I am writing a command-line tool and using pygments to do the syntax highlighting and completion.

For the auto-completion, I need pygments to tell me the current `state`, so I can guess the next possible token, base on that, I can have a complete list.

For example, I have a redis lexer like this:

```
class RedisLexer(RegexLexer):
    name = "redis lexer"

    tokens = {
        "root": [
            (r"\s+", Whitespace),
            (r"(?i)GET", Keyword, "get"),
            (r"(?i)SET", Keyword, "set"),
        ],
        "get": [(r"\s+", Whitespace), (r"\w+", Name, "#pop")],
        "set": [(r"\s+", Whitespace), (r"\w+", Name, "value")],
        "value": [(r"\s+", Whitespace), (r"\w+", Name, "#pop:2")],
    }
```

When user type `set foo`, I want to know the current state is `"value"`.

Is there an API to do this? I searched the documents but didn't find any.

**Comment by Anteru** [comment]
Hi, Pygments is not designed for auto-completion. While it may be possible to hack something along those lines using Pygments, I don't see us adding (and committing) to a public API to facilitate this.

**Comment by laixintao** [comment]
OK thanks.
