### ISSUE TITLE
guess_lexer picks TeraTermLexer for most code samples in Pygments 2.4

### ISSUE THREAD

**Issue by chriskuehl** [pygments/pygments#1256]
I think there is an issue with the TeraTerm lexer which causes Pygments to guess it for many code snippets (more than 50% of the random snippets I try).

Here's an example of text that is correctly identified as C in Pygments 2.3.1 but identified as TerraTerm in Pygments 2.4.0 and above (including 2.4.2):

```python
from pygments.lexers import guess_lexer

TEST_C = '''
#include <stdio.h>
#include <stdlib.h>

int main(void);

int main(void) {
    uint8_t x = 42;
    uint8_t y = x + 1;

    /* exit 1 for success! */
    return 1;
}
'''
print(guess_lexer(TEST_C))
```

I think it might be because of this special scoring logic:
https://github.com/pygments/pygments/blob/c3fdd7bcf01b317f242efc3525afca44aa199924/pygments/lexers/teraterm.py#L152-L158

I'm not quite sure what the fix is here; it seems like `analyze_text` is used to pick between filename matches, but in this case where no filename is provided, a large number of samples will go for TerraTerm as most languages use some of the commands it's looking for: https://github.com/pygments/pygments/blob/c3fdd7bcf01b317f242efc3525afca44aa199924/pygments/lexers/teraterm.py#L57-L97

**Comment by birkenfeld** [comment]
Yes, that's definitely excessive. The analyzers should only pick on pretty unique features, or use very small values like 0.01.

Until something better is implemented, I think the analyzer should just be removed.

**Comment by Anteru** [comment]
Aye, yeah, I didn't notice how greedy it is. I'll get rid of it.

**Comment by kurtmckee** [comment]
@chriskuehl I apologize for the inconvenience!

@birkenfeld For some reason I thought that `analyze_text()` would be called based on file extension alone. Sorry for creating this problem!

@Anteru thanks for fixing this.
