### ISSUE TITLE
pygments 2.5.0 is globally installing its tests under the "tests" module

### ISSUE THREAD

**Issue by thehcma** [pygments/pygments#1280]
This obviously pollutes the global top-level ``tests`` module.

```
/..../lib/python3.7/site-packages/tests/
├── dtds
│   ├── HTML4.dcl
│   ├── HTML4.dtd
│   ├── HTML4-f.dtd
│   ├── HTML4-s.dtd
│   ├── HTML4.soc
│   ├── HTMLlat1.ent
│   ├── HTMLspec.ent
│   └── HTMLsym.ent
├── examplefiles
│   ├── 99_bottles_of_beer.chpl
│   ├── abnf_example1.abnf
│   ├── abnf_example2.abnf
│   ├── AcidStateAdvanced.hs
│   ├── addressbook.proto
│   ├── ahcon.f
│   ├── all.nit
│   ├── AlternatingGroup.mu
│   ├── antlr_ANTLRv3.g
│   ├── antlr_throws
│   ├── apache2.conf
│   ├── as3_test2.as
│   ├── as3_test3.as
│   ├── as3_test.as
│   ├── aspx-cs_example
│   ├── autoit_submit.au3
...
...
```

**Comment by Anteru** [comment]
Uh, that's not good. It shouldn't be installing the tests at all, but then again, nothing changed on the build script side. @birkenfeld any idea what went wrong here? Is this related to the py.test migration by any chance?

**Comment by Anteru** [comment]
The `tests` folder is mentioned in `MANIFEST.in`, but that file has not changed in years. Maybe it's due to `__init__.py` being present in `tests`, and `find_package` in `setup.py` should become: `
    packages = find_packages(exclude=['tests']),`

**Comment by birkenfeld** [comment]
Yeah, that looks to be the culprit.

Oh well, no big deal, time for a brown-paper-bag release.

**Comment by thehcma** [comment]
Thanks for fix!

**Comment by Anteru** [comment]
2.5.1 is live now with the fix. Sorry for the inconvenience!
