### ISSUE TITLE
Pull requests/branches from bitbucket have disappeared

### ISSUE THREAD

**Issue by matthiasdiener** [pygments/pygments#1281]
I had opened a pull request on bitbucket some time ago (https://bitbucket.org/birkenfeld/pygments-main/pull-requests/809/bashsessionlexer-allow-using-for-comments/ ). The PR has been closed with a message that they have been imported to GitHub as branches. However, I don't see a branch referring to this pull request on GitHub, and since the source on bitbucket has been deleted, I also can't recreate the PR easily from scratch :-(

**Comment by Anteru** [comment]
PRs didn't come across when we migrated. The best you can try is to diff your `shell.py`: https://bitbucket.org/birkenfeld/pygments-main/pull-requests/809/bashsessionlexer-allow-using-for-comments/diff#chg-pygments/lexers/shell.py against the current one, if it was contained to a few rules, it should be reasonably easy to reconstruct the PR from there?

**Comment by birkenfeld** [comment]
My bad, the text on bitbucket is based on a misunderstanding of mine.

However, the source on bitbucket doesn't seem to be deleted; you can see the commit on https://bitbucket.org/birkenfeld/pygments-main/pull-requests/809/bashsessionlexer-allow-using-for-comments/commits (assuming it's only that one).

**Comment by matthiasdiener** [comment]
> However, the source on bitbucket doesn't seem to be deleted; you can see the commit on https://bitbucket.org/birkenfeld/pygments-main/pull-requests/809/bashsessionlexer-allow-using-for-comments/commits (assuming it's only that one).

This works for me, thanks!
