### ISSUE TITLE
pygmentize missing since 2.5

### ISSUE THREAD

**Issue by cprivite** [pygments/pygments#1335]
I don't see any mention of it being removed in the change notes. Is it supposed to be gone now?

**Comment by birkenfeld** [comment]
It wasn't mentioned since it is still present in the installed package, just now as a setuptools console script.

For checkouts, use python -m pygments.

**Comment by cprivite** [comment]
Ok, got it, thanks.

**Comment by cprivite** [comment]
So does that mean this documentation needs to be updated to reflect you have to run it weirdly now?
https://pygments.org/docs/cmdline/

**Comment by Anteru** [comment]
No, if you have installed it, there will be a pygmentize. This should only affect developers.
