### ISSUE TITLE
Pygments does not work_MacBookAir_Latex_Python3.7

### ISSUE THREAD

**Issue by jsbibra** [pygments/pygments#1346]
I need a detailed install guide for Pygments on OSX to be able to prettify Latex code-- I have tried various options as explained at  `https://github.com/SublimeText/LaTeXTools/issues/657#issuecomment-414410430` 

Python 3.7 installed with brew
Pygments installed with pip
Using Sublime Text3 for build --shell -escape enabled 
Still having problems-- frozencache + pygments not detected+shell escape disabled only ifwindows

Can a macro be created for installation and setting the path/ creating symlink

**Comment by Anteru** [comment]
Can you run `pygmentize`? Does that work at least?

**Comment by jsbibra** [comment]
if i try to install pyg i get the message already installed--
if i try $which pyg i get the path 
i added the path manually to ST3 under platform settings--usr/local/bin/pygmentize 
and also Users/Apple/.pyenv/shims/Pygmentize
and Users/Apple/.pyenv/shims/Python
get the warnings during build--frozencache + pygments not detected+shell escape disabled only ifwindows

**Comment by Anteru** [comment]
Not sure what `pyg` is. Can you run `pygmentize <some file>` on the command line (obviously replacing `<some file>` with an actual filename) and does that work? If so, I don't see how we can fix this, as all we do is provide the `pygmentize` command (and install the library).

**Comment by Anteru** [comment]
Closing due to lack of feedback. If this still occurs, please comment here or open a new issue.
