### ISSUE TITLE
Release Plans

### ISSUE THREAD

**Issue by CrafterKolyan** [pygments/pygments#1351]
Are there any plans for the next release date? Are there any conditions that must be satisfied for the release? It's already 3 months passed since last release and many fixes were done to the library. Do you have any tasks that delay the release?

**Comment by Anteru** [comment]
There is no specific date for a next release -- we just need to cut off at some point and make one. Is there anything particularly important fix that would warrant a new release?

**Comment by CrafterKolyan** [comment]
As for us there were some important fixes connected with `SLexer` but as I think there are some important changes for all contributors (because in my opinion some of these changes are made after people found some bug in their own software or project using `pygments`). Actually I am for the constant delivery of updates (just as `tqdm` does).

If you want some really important fix we can fix for example f-strings in python so that jupyter notebook will highlight them correct. But I'm not sure that's a bad thing to release just some fixes. They are fixes after all. And there's no particular need in releasing 2.6 version. We can release 2.5.3.

**Comment by Anteru** [comment]
We have new lexers, so the next release will be 2.6. If there was some important fix that would warrant a 2.5.3 then I could push it out. Basically, we do a new release when "enough" stuff has accumulated, and there are some larger PRs waiting to get merged here which I personally would like to land before 2.6 happens.

**Comment by birkenfeld** [comment]
2.5.3 can't be released right now since the master branch contains new features and fixes.
I wanted to have 2.6 in 2020 since we're removing 2.x compatibility.

As for release frequency, releases are not free.  They generate work for us, of course, but also for downstream users/packagers who have to decide which versions to pick up.

**Comment by Anteru** [comment]
I meant that we could do a 2.5.3 if an *important* fix is needed by manually backporting it, but that has high cost and I don't see a fix that would warrant that :)

**Comment by birkenfeld** [comment]
Yes, sorry, I responded to Nikolay and your post crossed mine :)
