### ISSUE TITLE
PEP 8 - E0611 - No name <N> in module <M> - Lexers and Formatters Example

### ISSUE THREAD

**Issue by Timothy-Dement** [pygments/pygments#1359]
| Component | Version |
| --- | --- |
| macOS | 10.15.2 |
| Python | 3.8.0 |
| Pylint | 2.4.4 |
| Pygments | 2.5.2 |

The import statements given in the [Introduction and Quickstart](https://pygments.org/docs/quickstart/) example result in a `E0611` flag.

```python
'''
Sample Module Docstring
'''

from pygments import highlight
from pygments.lexers import PythonLexer
from pygments.formatters import HtmlFormatter

CODE = 'print "Hello World"'
print(highlight(CODE, PythonLexer(), HtmlFormatter()))
```

```bash
************* Module main
main.py:6:0: E0611: No name 'PythonLexer' in module 'pygments.lexers' (no-name-in-module)
main.py:7:0: E0611: No name 'HtmlFormatter' in module 'pygments.formatters' (no-name-in-module)

----------------------------------------------------------------------
Your code has been rated at -10.00/10 (previous run: -10.00/10, +0.00)
```

However, using these import statements instead seems to adhere to the `E0611` PEP 8 guidelines.

```python
'''
Sample Module Docstring
'''

from pygments import highlight
from pygments.lexers.python import PythonLexer
from pygments.formatters.html import HtmlFormatter

CODE = 'print "Hello World"'
print(highlight(CODE, PythonLexer(), HtmlFormatter()))
```

```bash

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)
```

| Flags `E0611` | Does Not Flag `E0611` |
| --- | --- |
| `from pygments.lexers import PythonLexer` | `from pygments.lexers.python import PythonLexer` |
| `from pygments.formatters import HtmlFormatter` | `from pygments.formatters.html import HtmlFormatter` |

**Comment by birkenfeld** [comment]
All the lexer classes are automatically re-exported from `pygments.lexers` for convenience.
You're free to use the imports from the full module; we do guarantee that they won't be renamed or moved without compatibility shims.

BTW, this is not related to PEP 8; it is just a style guide. Pylint checks tons of stuff unrelated to PEP 8.

**Comment by Timothy-Dement** [comment]
Updating the title and comment so it doesn't confuse — thanks for the info!
