### ISSUE TITLE
PythonLexer coloring of dictionaries

### ISSUE THREAD

**Issue by AdrienLemaire** [pygments/pygments#1365]
Usecase: Getting nicer prints of object values in ipdb

What I tried:

.pdbrc
```py
import json
from pygments import highlight
from pygments.lexers import JsonLexer, PythonLexer
from pygments.formatters import TerminalFormatter=
from pprint import pformat

alias ppj %1: print(highlight(json.dumps(%1, indent=2, sort_keys=True), JsonLexer(), TerminalFormatter(style='tomorrownight')))
alias ppp %1: print(highlight(pformat(%1), PythonLexer(), TerminalFormatter(style='tomorrownight')))
```

ipdb> pp vars(obj)
![image](https://user-images.githubusercontent.com/260983/72872078-c79e0280-3d2f-11ea-9e9d-7e4c78c34860.png)
⇒ The results from pp are non-colorized

ipdb> ppj vars(obj)
![image](https://user-images.githubusercontent.com/260983/72872106-dedcf000-3d2f-11ea-8e65-7246b9313912.png)
⇒ The results with JsonLexer have unwanted escape characters in the values and unicode chars are replaced with their code.

ipdb> ppp vars(obj)
![image](https://user-images.githubusercontent.com/260983/72872128-ea301b80-3d2f-11ea-994c-dc566bb28253.png)
⇒ The results from PythonLexer have a single color

I would like to use PythonLexer with colors looking like with the JsonLexer, but couldn't figure it out. Can someone help me out with it ?

**Comment by birkenfeld** [comment]
The Python lexer doesn't treat strings differently depending on their position as keys or values in a dict.

I think this is fine, since it's hard to lex this unambiguously (Python syntax being much more complex than JSON) and also introduces very arbitrary choices here.
