### ISSUE TITLE
console lexer does not handle slash command line continuation

### ISSUE THREAD

**Issue by peterjc** [pygments/pygments#1368]
Example:

```
$ cat fragment.txt 
shell$ long-command -a blah-blah-long-arguments \ 
 -b more-arguments-on-continued-line
This is the output
shell$
```

```
$ cat fragment.txt | pygmentize -l console -f html
<div class="highlight"><pre><span></span><span class="gp">shell$</span> long-command -a blah-blah-long-arguments <span class="se">\ </span>
<span class="go"> -b more-arguments-on-continued-line</span>
<span class="go">This is the output</span>
<span class="gp">shell$</span>
</pre></div>
```

Desired output has the line `` -b more-arguments-on-continued-line`` formatted like the command (local default style?), not as command output (``<span class="go">...</span>``), perhaps:

```
<div class="highlight"><pre><span></span><span class="gp">shell$</span> long-command -a blah-blah-long-arguments <span class="se">\ </span>
 -b more-arguments-on-continued-line
<span class="go">This is the output</span>
<span class="gp">shell$</span>
</pre></div>
```

Comparison:

```
$ cat one-line.txt
shell$ command -a blah -b more-blah
This is the output
shell$
```

```
$ cat one-line.txt | pygmentize -l console -f html
<div class="highlight"><pre><span></span><span class="gp">shell$</span> command -a blah -b more-blah
<span class="go">This is the output</span>
<span class="gp">shell$</span>
</pre></div>
```

Version tested:

```
$ pygmentize -V
Pygments version 2.4.2, (c) 2006-2019 by Georg Brandl.
```

Ran this example on macOS, but seeing this within the GitHub rending of RST into HTML, e.g.

https://github.com/peterjc/thapbi-pict/blob/v0.6.4/docs/worked_example/sample_summary.rst

(Edited to remove my own prompt for clarity)

**Comment by Anteru** [comment]
Could you please test it with 2.5.2? In 2.5.0, there were fixes to the bash session lexer.

**Comment by peterjc** [comment]
Sorry - thought it was up to date. Retested (on a second macOS machine) with v2.5.2, no change:

```
$ pygmentize -V
Pygments version 2.5.2, (c) 2006-2019 by Georg Brandl.
```

**Comment by Anteru** [comment]
Thanks! Bummer ... I'll see if I can do something about it.

**Comment by Anteru** [comment]
Is there a whitespace character after the `\`? Without it, it works for me -- and as far as I can tell, [it must be followed *immediately*](http://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Escape-Character) by a newline.

**Comment by peterjc** [comment]
That is subtle.

Yes, the ``fragments.txt`` example _did_ have an accidental trailing space - removing that fixes this test case:

```
$ cat fragment2.txt | pygmentize -l console -f html
<div class="highlight"><pre><span></span><span class="gp">shell$</span> long-command -a blah-blah-long-arguments <span class="se">\</span>
 -b more-arguments-on-continued-line
<span class="go">This is the output</span>
<span class="gp">shell$</span>
</pre></div>
```

But the real world example did not have any space after the slash (although hard to see in GitHub rendering), in part because I actively check for trailing white space in the continuous integration tests for the repository cited:
 
https://github.com/peterjc/thapbi-pict/blob/v0.6.4/docs/worked_example/sample_summary.rst
https://github.com/peterjc/thapbi-pict/blob/v0.6.4/.circleci/config.yml#L28
https://github.com/peterjc/thapbi-pict/blob/v0.6.4/.travis.yml#L29

Minimal test case:

```
$ head -n 29 docs/worked_example/sample_summary.rst | tail -n 7 

    $ thapbi_pict sample-summary -i intermediate/ \
      -o summary/thapbi-pict.samples.tsv \
      -e summary/thapbi-pict.samples.xlxs \
      -r summary/thapbi-pict.samples.txt
    ...
```

There are no trailing space after the slashes:

```
$ head -n 29 docs/worked_example/sample_summary.rst | tail -n 7  | hexdump -C
00000000  0a 20 20 20 20 24 20 74  68 61 70 62 69 5f 70 69  |.    $ thapbi_pi|
00000010  63 74 20 73 61 6d 70 6c  65 2d 73 75 6d 6d 61 72  |ct sample-summar|
00000020  79 20 2d 69 20 69 6e 74  65 72 6d 65 64 69 61 74  |y -i intermediat|
00000030  65 2f 20 5c 0a 20 20 20  20 20 20 2d 6f 20 73 75  |e/ \.      -o su|
00000040  6d 6d 61 72 79 2f 74 68  61 70 62 69 2d 70 69 63  |mmary/thapbi-pic|
00000050  74 2e 73 61 6d 70 6c 65  73 2e 74 73 76 20 5c 0a  |t.samples.tsv \.|
00000060  20 20 20 20 20 20 2d 65  20 73 75 6d 6d 61 72 79  |      -e summary|
00000070  2f 74 68 61 70 62 69 2d  70 69 63 74 2e 73 61 6d  |/thapbi-pict.sam|
00000080  70 6c 65 73 2e 78 6c 78  73 20 5c 0a 20 20 20 20  |ples.xlxs \.    |
00000090  20 20 2d 72 20 73 75 6d  6d 61 72 79 2f 74 68 61  |  -r summary/tha|
000000a0  70 62 69 2d 70 69 63 74  2e 73 61 6d 70 6c 65 73  |pbi-pict.samples|
000000b0  2e 74 78 74 0a 20 20 20  20 2e 2e 2e 0a 0a        |.txt.    .....|
000000be
```

And the output looks fine:

```
$ head -n 29 docs/worked_example/sample_summary.rst | tail -n 7 | pygmentize -l console -f html
<div class="highlight"><pre><span></span><span class="gp">    $</span> thapbi_pict sample-summary -i intermediate/ <span class="se">\</span>
      -o summary/thapbi-pict.samples.tsv <span class="se">\</span>
      -e summary/thapbi-pict.samples.xlxs <span class="se">\</span>
      -r summary/thapbi-pict.samples.txt
<span class="go">    ...</span>
</pre></div>
```

I was misled by the trailing space in my constructed test case, and concluded wrongly the problem was in pygments. Sorry about that.

Perhaps a trailing space is being introduced elsewhere in the stack (Sphinx via ReadTheDocs, and the GitHub RST rendering) and giving the less than perfect output?

Anyway, it does not look like a pygments problem after all - thank you for your help. Unless you can think of anything else to investigate from this end, shall we close this issue?

**Comment by Anteru** [comment]
Thanks for the investigation! I'll close it then, because there's not much the Bash session lexer can do about it, it specifically checks for ``\\\n`` at the end of a line.  If there is anything else (potentially even a different line ending character), it will bail out, but that seems to match Bash.

**Comment by peterjc** [comment]
I've tried to log an issue on the GitHub rendering, I suspect they are not using pygments in their current system.

Perhaps the RTD/Sphinx problem I recall seeing had trailing whitespace.... the Read-The-Docs hosted output for this cited example has put the entire code block in a ``<pre>`` block with no formatting within that (so the question is irrelevant). Running Sphinx locally with the RTD theme, the HTML markup matches the test case as discussed above - no problem.
