### ISSUE TITLE
%d in date formatting in f-strings

### ISSUE THREAD

**Issue by verhovsky** [pygments/pygments#1373]
<img width="680" alt="Снимок экрана 2020-01-27 в 1 41 32 AM" src="https://user-images.githubusercontent.com/5687998/73154716-3f5c8c00-40a6-11ea-974c-d838a44beef9.png">

`%d` shouldn't be highlighted in this case.

https://docs.python.org/3/library/string.html#format-examples

**Comment by birkenfeld** [comment]
We're highlighting the old-style format placeholders in any string (except f-strings), since we can't decide if it's being used for %-formatting for `.format` formatting.

This is one of the small inaccuracies that's unavoidable as we're not an interpreter.
