### ISSUE TITLE
Italic and bold text for markdown files in the terminal

### ISSUE THREAD

**Issue by MaxGyver83** [pygments/pygments#1377]
I'm wondering why I don't see **bold** or _italic_ text when I use `pygmentize` with a markdown file.

`pygmentize demo.md`

![grafik](https://user-images.githubusercontent.com/13970628/73589905-78e52b00-44dc-11ea-8683-070579261fc1.png)

The terminal/the font should not be a problem. It can render italic and bold text:

`./styles.bash`

![grafik](https://user-images.githubusercontent.com/13970628/73589976-3cfe9580-44dd-11ea-82ff-5ec3c4a5ad91.png)

Do I need additional parameters to get the formatting right?

I'm using:
* Ubuntu 18.04
* Pygments version 2.2.0
* terminator 1.91

---

`demo.md` (without the code block)

```md
# Main Header

* `**bold**` for **bold text**
* `__bold__` for __bold text__
* `*italic*` for *italic text*
* `~~strikethrough~~` for ~~strikethrough~~ text

## Links

External link: [Pygments Homepage](https://pygments.org/)
```

`styles.bash`

```bash
#!/bin/bash
echo -e '\e[1mbold\e[22m'
echo -e '\e[2mdim\e[22m'
echo -e '\e[3mitalic\e[23m'
echo -e '\e[4munderline\e[24m'
echo -e '\e[21mdouble underline\e[24m'
echo -e '\e[4:3mcurly underline\e[4:0m'
echo -e '\e[9mstrikethrough\e[29m'
echo -e '\e[53moverline\e[55m'
```

**Comment by MaxGyver83** [comment]
Sorry, my Pygments installation is old. That's the output with Pygments 2.5.2:

![grafik](https://user-images.githubusercontent.com/13970628/73590187-dfb81380-44df-11ea-965b-26d6338d6dc0.png)

Bold formatting works now, but italic doesn't. (And the contrast is bad now 😃)

**Comment by MaxGyver83** [comment]
I just discovered this [PR: allow terminal256 formatter to show italics](https://github.com/pygments/pygments/pull/1288) for Pygment 2.6. Apparently, italics in the terminal are not yet supported in version 2.5.2. I suppose strikethrough is not yet supported either.

**Comment by Anteru** [comment]
Yeah, forgot to mention that PR. Will be fixed in the next release!
