### ISSUE TITLE
C++: declarations of functions that return a reference (&) are not highlighted

### ISSUE THREAD

**Issue by leombro** [pygments/pygments#1396]
In the following snippet:

    // Function forward declaration
    type a_function();
    
    // Another forward declaration
    type& another_function();

The second function is not highlighted due to the return type being a reference.

Minimal working example at https://www.overleaf.com/read/kfwwcrpktwwh

**Comment by jokoon** [comment]
Apparently no function are ever highlighted, at least in my case.

Oddly, only function like abs, interp are highlighted.
