### ISSUE TITLE
Script block in __init__.py

### ISSUE THREAD

**Issue by gribok** [pygments/pygments#1401]
Hi all,

I am trying to understand the following statement in `__init__.py`

https://github.com/pygments/pygments/blob/154f3a0c9ef4a57fff7af3568b7d88552db640d8/pygments/__init__.py#L88-L90

As I understood, the mentioned lines should never be executable. An `__init__.py` declares directory as a package und could provide functions on top-level.  
But is it possible to execute `__init__.py` as script, like per `__main__.py`?

Thanks in advance.

**Comment by Anteru** [comment]
This is invoked when you run it like so `python -m pygments`.

**Comment by gribok** [comment]
> This is invoked when you run it like so: `python -m pygments`.

With `python -m pygments` will be `__main__.py` invoked. If I am deleting `__main__.py`, I will get following error msg:
`/usr/bin/python3.6: No module named pygments.__main__; 'pygments' is a package and cannot be directly executed`

Maybe do you have an example?

**Comment by Anteru** [comment]
Oh ... I see, I somehow thought that calls `__init__.py`, my bad. I have no idea why it's in `__init__.py` then, maybe @birkenfeld can shed some light on this :) It was there from the very beginning, 14 years ago -- do you happen to know when `__main__.py` was introduced?

**Comment by gribok** [comment]
I think, we have a clear understanding, that the mentioned part doesn't work in current python version. So I am closing the issue.

**Comment by birkenfeld** [comment]
It's probably there by accident and can be removed.
