### ISSUE TITLE
Pygments 2.6 identifies as Python 2 & 3

### ISSUE THREAD

**Issue by GadgetSteve** [pygments/pygments#1411]
Just did a pip install -U pygments and spotted:

`Downloading Pygments-2.6.1-py2.py3-none-any.whl`

But the release notes specify:

> Pygments 2.6 is a major new release removing support for Python 2.x.
> From Pygments 2.6, we require Python 3.5 or newer to run Pygments.

So surley this should be packaged as `Pygments-2.6.1-py3-none-any.whl` so that python 2 users _(there are still quite a few)_ will **not** get this update.

**Comment by Anteru** [comment]
Uh, does it actually manage to install on Python 2.x installations? I fixed that packaging issue yesterday, but I didn't re-upload new packages yet ...

**Comment by Anteru** [comment]
The universal wheel has been removed from PyPi. That should hopefully fix it, if not, please let me know.

**Comment by GadgetSteve** [comment]
@Anteru - Just tried on a different machine and on python 3.7/8 successfully got Pygments-2.6.1-py3-none-any.whl but with python 2.7 got Pygments-2.5.2-py2.py3-none-any.whl so looking good!

**Comment by jacob-garcia-coupa** [comment]
Quick question - I'm working on a dev team that didn't have a version rule implemented yet for Python 2.7 legacy products.

Would there be any way to take down the universal wheel for 2.6.0 as well? We're working on shoring up our end, just thought I'd save someone else the trouble.

**Comment by Anteru** [comment]
I'll look into it. Sorry for the trouble.

**Comment by jacob-garcia-coupa** [comment]
No problem at all! Appreciate your work and prompt reply!
