### ISSUE TITLE
pygments hashes do match on pypi

### ISSUE THREAD

**Issue by perlow** [pygments/pygments#1412]
THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    pygments==2.6.1 from https://files.pythonhosted.org/packages/2d/68/106af3ae51daf807e9cdcba6a90e518954eb8b70341cee52995540a53ead/Pygments-2.6.1-py3-none-any.whl#sha256=ff7a40b4860b727ab48fad6360eb351cc1b33cbf9b15a0f689ca5353e9463324 (from -r /dev/stdin (line 1032)):
        Expected sha256 aa931c0bd5daa25c475afadb2147115134cfe501f0656828cbe7cb566c7123bc
        Expected     or 647344a061c249a3b74e230c739f434d7ea4d8b1d5f3721bc0f3558049b38f44
             Got        ff7a40b4860b727ab48fad6360eb351cc1b33cbf9b15a0f689ca5353e9463324

**Comment by Anteru** [comment]
I don't understand this error -- I have not modified the files. I just tried to reproduce myself and it works for me. Can you reproduce this on any other machine?

**Comment by birkenfeld** [comment]
Where does the "expected sha256" come from? The file from PyPI matches the `ff7...` one.

@Anteru do you still have the original files you uploaded on your machine?

**Comment by Anteru** [comment]
For 2.6.1 -- yes. For 2.6.0, no.

**Comment by birkenfeld** [comment]
well, looks like the bug report is about 2.6.1.  I assume your local files match the published hashes on PyPI?

**Comment by Anteru** [comment]
Just ran this on my machine, and yes, the hashes match:

```
$ sha256sum Pygments-2.6.1-py3-none-any.whl 
ff7a40b4860b727ab48fad6360eb351cc1b33cbf9b15a0f689ca5353e9463324  Pygments-2.6.1-py3-none-any.whl
```

**Comment by birkenfeld** [comment]
Then, pending clarification from OP, it looks like a corruption issue on their end...

**Comment by Anteru** [comment]
... and I just noticed I also have the 2.6.0 wheels around as well :) In fact, all files I ever uploaded, should this issue arise again.

**Comment by perlow** [comment]
Now I am getting it for 2.6.0 as well

```
THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    pygments==2.6.0 from https://files.pythonhosted.org/packages/b1/f1/b029e6454e6ce6965e806ba9c8152cbeb6eab080068576cb48767fd8ff4e/Pygments-2.6.0-py3-none-any.whl#sha256=ccfb2441778d5825f5cb3741c91e1c9f79bb459622454fc29cd47356338392c6 (from -r /deps/nextdoor3_requirements.txt (line 1035)):
        Expected sha256 fade06c85a04feb688a5a23d65a86daed4489680f35b4ae4c685110e98d1eda8
        Expected     or d4b5e1c585ec7e5fd4ef3e8584f9b04bdd3d9e2e87e64c2fbcada605cf1b6ca4
             Got        ccfb2441778d5825f5cb3741c91e1c9f79bb459622454fc29cd47356338392c6
```

Is there a way to double check pypi and make sure that none of the files have been tampered with? I wonder if it could be some stale cache in pypi even. I noticed the files were recently updated. Were they ever updated without bumping the version number?

**Comment by Anteru** [comment]
That file was freshly uploaded. It was never changed (in fact, you _cannot_ change a file on PyPi.) The file I uploaded is:

```
$ sha256sum Pygments-2.6.0-py3-none-any.whl 
ccfb2441778d5825f5cb3741c91e1c9f79bb459622454fc29cd47356338392c6  Pygments-2.6.0-py3-none-any.whl
```

Which seems to match the expected hash. If I had to guess, I'd say your machine has a faulty memory stick.

**Comment by perlow** [comment]
I'm using Poetry as the package manager and it's generating the lockfile with those hashes. Then I am using `poetry export -f requirements.txt | pip install -r /dev/stdin` to install them with pip. Maybe something is going wrong along the way. The project contains hundreds of dependencies and this is the only one with this issue. I am wondering if there's some unusual about how this library might be packaged.

**Comment by perlow** [comment]
Here's what poetry generates for the requirements.txt file:

`pygments==2.6.1 \
    --hash=sha256:aa931c0bd5daa25c475afadb2147115134cfe501f0656828cbe7cb566c7123bc \
    --hash=sha256:647344a061c249a3b74e230c739f434d7ea4d8b1d5f3721bc0f3558049b38f44
`

**Comment by perlow** [comment]
Okay, I figured out the issue. https://github.com/python-poetry/poetry/issues/51
It's related to caching. It looks like the exact issue where the whl file was uploaded a day later.

**Comment by birkenfeld** [comment]
Thanks for letting us know. In the future, please include details such as the tool you're using in the initial bug report. Poetry is far from universally used, so we don't know that particular text output is generated by it.

I might also add that it's pretty deceiving by Poetry to claim "someone may have tampered with the files" when they can't even ensure they're comparing the same file that originally generated the hash.  But that's not your fault, of course.

**Comment by perlow** [comment]
Yep, I agree. Thanks.
