### ISSUE TITLE
CLexer does not correctly determine comments that use "//".

### ISSUE THREAD

**Issue by KanoeGitHub** [pygments/pygments#1421]
CLexer does not correctly determine single comments that use "//".
I ran the code below.
```
from pygments.token import Token
from pygments.lexers import CLexer

code = '//Hello'
lexer = get_lexer_by_name("c")
token_it = lexer.get_tokens_unprocessed(code)
for idx, token_type, token_string in token_it:
   print(token_type , '=' ,token_string)
```

The result is as follows.
```
kanoe@kanoe-macbookpro:~/desktop/code$ python3 /home/kanoe/desktop/code/sample.py
Token.Operator = /
Token.Operator = /
Token.Name = Hello
```

Pygments version is 2.6.1.
Python3 on Ubuntu

**Comment by kurtmckee** [comment]
@KanoeGitHub try using `get_tokens()`, not `get_tokens_unprocessed()`. It correctly parses the code.

@Anteru and @birkenfeld I can confirm this behavior exists in master. I don't know whether this is a bug or anticipated behavior, though.
