### ISSUE TITLE
pygmentize -O looks like doing nothing switch

### ISSUE THREAD

**Issue by pt12lol** [pygments/pygments#1424]
I wanted to use any option, but I haven't managed yet. Tried out with Python 3, Pygments 2.6.1 version, on Ubuntu 18.04. Tried also under fresh Ubuntu 18.04 Docker image - just installed pip3 and Pygments. Example failure use:
```
$ echo -e 'print("hello")\nprint("world")' | pygmentize -l python -O lineos=1                                                                     
print("hello")
print("world")
```
No lines numbering provided.
Have already debugged the issue, found `lineos` set to 1 as a lexer option but without any effect. Was looking for any `lineos` word in a code base, but couldn't find anything.

**Comment by birkenfeld** [comment]
The terminal formatter does not (currently) support outputting line numbers. You'll have to e.g. use the HTML formatter.

(Also, the option is called `linenos` but that is probably a typo only in this issue.)

**Comment by pt12lol** [comment]
Yes, that was a typo. Thanks for explanation.
