### ISSUE TITLE
Slow processing of JSON

### ISSUE THREAD

**Issue by kellyjonbrazil** [pygments/pygments#1425]
Can I do anything to optimize the performance of highlighting JSON in my app, or is this working as designed?
```
class JelloStyle(Style):
    styles = {
        Name.Tag: 'bold ansiblue',     # key names
        Keyword: 'ansibrightblack',    # true, false, null
        Number: 'ansimagenta',         # int, float
        String: 'ansigreen'            # string
    }

print(highlight(output, JsonLexer(), Terminal256Formatter(style=JelloStyle))[0:-1])
```
(I remove the last character because it seems for some reason `highlight` adds a newline character, but that doesn't seem to affect performance)

When I use the highlight function on a relatively large (6MB) JSON file, it adds 13 seconds to the output time:
```
time cat ls-R.out | jc --ls | jello -m
real    0m3.101s
user    0m1.727s
sys 0m0.537s
```
vs.
```
time cat ls-R.out | jc --ls | jello
real    0m16.916s
user    0m14.624s
sys 0m0.721s
```
Using the plain `TerminalFormatter` didn't seem to improve performance.

**Comment by kellyjonbrazil** [comment]
Could there be any performance gains by compiling some of the core functionality via Cython or perhaps with mypyc when/if it is ready?

**Comment by birkenfeld** [comment]
It might, although I suspect that most time is spent matching the regexes anyway, and of course the regex engine is already C code.

So either we optimize the regexes, or we switch to a faster regex engine...

**Comment by kurtmckee** [comment]
@kellyjonbrazil could you link to the file you're using, or suggest a way to locally produce a representative file?

For example, if it's a very very very nested structure, perhaps there are some opportunities to improve the internal stack processing of the JSON lexer. Or perhaps the formatter is doing some calls/lookups/whatever that, at scale, are adding some time. Or perhaps the lexer's regular expressions are truly the issue and it would be worthwhile to explore a faster regex engine like @birkenfeld suggested.

Whatever the root cause actually is, it will be helpful to have a representative (if not identical) sample file.

By the way, is your app exclusively writing 6MB of JSON to console? Are there any other use cases (other languages, other output formats, etc) that should be accounted for while investigating?

**Comment by kellyjonbrazil** [comment]
Hi @kurtmckee,

My application is called `jc` (https://github.com/kellyjonbrazil/jc) and it JSONifies the output of many commands. The performance issue would probably not be noticed in most situations since you would not normally want to see hundreds of megabytes worth of pretty-printed JSON text in the terminal, but I did notice it in testing.

To reproduce, you can redirect the output of a large `ls` job to a file:
```
ls -alR / > lsfile.out
```
Then you can run the following `jc` command to convert it to JSON in the terminal. When `jc` outputs to the terminal, Pygments will color the output by default. If the `-m` option is used, Pygments is disabled:
```
cat lsfile.out | jc --ls      # this is slow
cat lsfile.out | jc --ls -m     # this is faster
```
The JSON that Pygments is working on looks like this (it's relatively flat):
```
[
  {
    "filename": "CHANGELOG",
    "flags": "-rw-r--r--",
    "links": 1,
    "owner": "kbrazil",
    "group": "staff",
    "size": 336,
    "date": "Sep 25 10:52"
  },
  {
    "filename": "Procfile",
    "flags": "-rw-r--r--@",
    "links": 1,
    "owner": "kbrazil",
    "group": "staff",
    "size": 21,
    "date": "Aug 26 14:09"
  },
  {
    "filename": "README.md",
    "flags": "-rw-r--r--@",
    "links": 1,
    "owner": "kbrazil",
    "group": "staff",
    "size": 104,
    "date": "Sep 25 10:52"
  },

...
```

**Comment by kurtmckee** [comment]
@kellyjonbrazil thanks for describing how to generate a representative file. I created a 118MB input file using `jc`, timed it, and then rewrote the JSON lexer and timed the new code.

**118MB input file with current regex code**
```
real    2m57.441s
user    2m41.297s
sys     0m10.030s
```

**118MB input file with new code**
```
real    1m42.079s
user    1m31.906s
sys     0m6.530s
```

This is a promising improvement but it isn't sufficient.

First, `get_tokens_unprocessed()` only takes 22 seconds to lex the 118MB file (compared with 63 seconds for the current regex lexer). That means 80+ seconds are spent elsewhere in Pygments.

Second, memory consumption explodes to over 3GB with both implementations. I haven't found where this is happening yet. A cursory tour of the lexer-to-formatter-to-output pipeline suggests that everything is handled through iteration, but it's definitely happening somewhere.

There are also other issues to resolve. The JSON lexer lacks meaningful unit tests. The JSON bare-object and JSON-LD lexers are dependent on the existing JSON regex lexer. And there's an opportunity to tokenize in-string escape sequences like `\n` or `\u1234`, which is missing from the current implementation. However, I don't want to tackle this until the runaway memory consumption is addressed.

I'll update again when I've addressed some or all of these issues.

**Comment by kurtmckee** [comment]
I've submitted a patch to help improve your processing times. The JSON lexer is three times faster now, and unrelated to this ticket, the HTML formatter consumes 33% less memory that it did before.

There may be other improvement opportunities but this is a good place to stop either for feedback or for merging.
