### ISSUE TITLE
Error when applying python lexer to string containing `

### ISSUE THREAD

**Issue by antonio-rojas** [pygments/pygments#1429]
Applying the python lexer to a string containg "`" throws an error:
```
from pygments import lex
from pygments.lexers import PythonLexer

PL = PythonLexer()
PL.add_filter('raiseonerror')
l = lex("`", PL)
u = list(l)
```
```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    u = list(l)
  File "/usr/lib/python3.8/site-packages/pygments/filter.py", line 20, in _apply
    for token in filter_.filter(lexer, stream):
  File "/usr/lib/python3.8/site-packages/pygments/filters/__init__.py", line 196, in filter
    raise self.exception(value)
pygments.filters.ErrorToken: `
```
This only happens the first time, so the following code doesn't crash
```
from pygments import lex
from pygments.lexers import PythonLexer

PL = PythonLexer()
l = lex("`", PL)
u = list(l)
PL.add_filter('raiseonerror')
v = list(l)
```

**Comment by birkenfeld** [comment]
This is working as intended:

- The backtick is not valid syntax anymore in Python 3, and the PythonLexer has been switched to Python 3.  Therefore an error token is emitted, which is converted to an exception by the filter.
- The return value of `lex` is a generator, which once exhausted (first call to `list`) doesn't return anything (i.e. `v` is empty).
