### ISSUE TITLE
Error: no lexer for filename 'gitweb_config.perl' found

### ISSUE THREAD

**Issue by stdedos** [pygments/pygments#1433]
What am I doing wrong?

```console
$ pygmentize gitweb_config.perl
Error: no lexer for filename 'gitweb_config.perl' found
$ pygmentize -O style=monokai gitweb_config.perl
Error: no lexer for filename 'gitweb_config.perl' found
$ pygmentize gitweb_config.perl -l pl
(full help text spam)
$ pygmentize gitweb_config.perl -l perl
(full help text spam)
$ pygmentize gitweb_config.perl gitweb_config.perl -L | grep perl
(full help text spam)
$ pygmentize gitweb_config.perl -L | grep perl
* antrlr-perl:
* perl, pl:
* perl6, pl6, raku:
* perldoc:
    Style similar to the style used in the perldoc code blocks.
$ pygmentize -V
Pygments version 2.6.11, (c) 2006-2019 by Georg Brandl.
```

**Comment by birkenfeld** [comment]
Options (`-l pl`) must come before the input file name, like you did correctly with `-O`.

**Comment by stdedos** [comment]
😲 That's weird. I don't remember a lot of cases that the flags order did matter

I am wondering though, why is the file extension not recognizable? Does it have to be `pl`?

**Comment by birkenfeld** [comment]
> That's weird. I don't remember a lot of cases that the flags order did matter

It's using the standard (albeit outdated) getopt module. We should probably update to argparse or click.

> I am wondering though, why is the file extension not recognizable? Does it have to be pl?

Well, so far nobody requested `.perl` to be recognized. If you say it's common I have no problem adding it, especially since no other lexer is likely to claim it.

**Comment by stdedos** [comment]
"Common" ... idk - I'll never make such claim.

But gitweb for some reason is using it (I don't know if it doesn't like `pl`, but a lot of its scripts do it like that), no other lexer is likely to claim it ... and getopt is annoying to deal with 😝

Your call

**Comment by birkenfeld** [comment]
OK, new extension is added. Thanks for reporting!
