### ISSUE TITLE
Have pygmentize output as JSON instead

### ISSUE THREAD

**Issue by tig** [pygments/pygments#1437]
It'd be great if `pygmentize` had the option of emitting lists (`-L`) as `JSON`.

I could go learn Python enough to figure out how to call `get_lexers` to do this. But I'd rather just do:

`pygmentize -L lexers -f json` 

or similar.

**Comment by legoktm** [comment]
I'd like to second this request. In [MediaWiki](https://gerrit.wikimedia.org/g/mediawiki/extensions/SyntaxHighlight_GeSHi/+/b4f53c7ad17c3438f187378652d083bc675dbe19/maintenance/updateLexerList.php) we currently extract the output of `pygmentize -L lexers` with some string parsing so we can show our users a list of all available lexers. It would be nice if pygmentize could output something machine-readable like JSON so we don't need to do that.

**Comment by Anteru** [comment]
I'll look into that. Shouldn't be too hard ... I suspect a `--json` argument to format the output as JSON would suffice (for the arguments where it's applicable?)

**Comment by birkenfeld** [comment]
Good idea!

**Comment by Anteru** [comment]
@legoktm I created a PR which adds a `--json` option that can be used in conjunction with `-L`. Would you mind giving it a try?
