### ISSUE TITLE
make fails on ubuntu - python/python3 problem

### ISSUE THREAD

**Issue by wolandscat** [pygments/pygments#1440]
Doing a basic make on a new clone on a Ubuntu 19 OS produces this:
```
thomas:pygments$ make mapfiles
(cd pygments/formatters; python _mapping.py)
pygments.formatters.terminal256
Traceback (most recent call last):
  File "_mapping.py", line 51, in <module>
    module = __import__(module_name, None, None, [''])
  File "../../pygments/formatters/terminal256.py", line 31, in <module>
    from pygments.style import ansicolors
  File "../../pygments/style.py", line 171
    class Style(metaclass=StyleMeta):
```

This appears to be due to the assumption in the Makefile that `python` should resolve to python3. This is not the usual assumption as far as I know, and won't work on any system where `python` means Python 2.x and `python3` is used as the name of Python 3.x. Some simple changes to the Makefile will fix this.

**Comment by Anteru** [comment]
This is mostly due to us always running make from within a virtual environment, to ensure that dependencies are present. Running it on the system-wide installation of Python is not that common, but I agree t hat this is rather simple fix.
