### ISSUE TITLE
Citation of sources in example files...

### ISSUE THREAD

**Issue by hrieke** [pygments/pygments#1445]
Hello all,

Sigh... While I enjoy pounding sand as much as the next person, there are times when I think dear old [Will had the right idea](https://en.wikipedia.org/wiki/Let%27s_kill_all_the_lawyers).

So, does anyone know where the source of tests/examplefiles originate from?
The licenses are all over the place, from Public Domain, to GNU General Public License v2.0 or later, to BSD 3-clause.

Thanks,

**Comment by Anteru** [comment]
The source for most of those files gets added as part of the lexer for the language.  What's the problem here?

**Comment by hrieke** [comment]
Legal asked me a question, so now I'm trying to figure things out. 
Thought that perhaps you had somewhere a list of where these files originated from, who the author is, and under which license the files are distributed with.
A few of these files have from what I can tell very restrictive license terms, or are commercial in nature.

**Comment by Anteru** [comment]
Those files are not redistributed, if you install the package, you shouldn't get them. They're only used for testing.

**Comment by hrieke** [comment]
Well, they are, and so here we are.
I do understand the purpose of the test files, I get that they should not be re-distributed, still when an audit of the code is performed, legal likes to know what they're dealing with.
[Murphy was an optimist!](https://en.wikipedia.org/wiki/Murphy%27s_law)

And Thank You for taking the time to answer my questions.
Hope you and yours are safe in these difficult times.

**Comment by Anteru** [comment]
They're not part of the Pygments wheel, so I'm a bit confused :) Can you create an *installation* of Pygments and let legal review that? Unless you're planning to fork Pygments and/or contribute, of course.

The only alternative I can think of is to produce a list of affected files, and re-create them. Which sounds interesting but I'm afraid that'll be a significant amount of work.

**Comment by hrieke** [comment]
Policy states that all the files in a package must be reviewed.
It's not my call, but it is my job to carry out the identification.

Thank you again.  If you want to close this ticket you can, but please carefully consider compiling a list of where these files originate from.
