### ISSUE TITLE
mysql unicode 

### ISSUE THREAD

**Issue by Freed-Wu** [pygments/pygments#1453]
mysql allow user to use unicode character to create table, but in minted

```
\documentclass{ctexbook}
\usepackage{minted}
\begin{document}
\begin{minted}{mysql}
create table basic(
	股票编号 int not null,
	上市年限 int not null,
	所属行业 varchar(20) not null,
	所属概念板块 varchar(200) not null
);
\end{minted}
\end{document}
```

the result:

![image](https://user-images.githubusercontent.com/32936898/82216088-009b5c00-994b-11ea-954b-310f9dd5d85e.png)

the unicode character be considered as `PYG@token@err` which will be added a red box. is it true?

**Comment by marijnschraagen** [comment]
Interestingly, it does work if there is a non-space latin character before the unicode characters:
```
\documentclass{ctexbook}
\usepackage{minted}
\begin{document}
\begin{minted}{mysql}
create table basic(
   a股票编号 int not null,
   b上市年限 int not null,
   c所属行业 varchar(20) not null,
   d所属概念板块 varchar(200) not null
);
\end{minted}
\end{document}
```
![Schermafdruk van 2020-06-23 15-58-29](https://user-images.githubusercontent.com/14089378/85412920-6abaa880-b56a-11ea-9616-a550f9379dc8.png)

**Comment by Freed-Wu** [comment]
amazing!

**Comment by kurtmckee** [comment]
I'm working on an overhaul of the MySQL lexer. I will _try_ to make this work, at least to the point that it doesn't render as an error.
