### ISSUE TITLE
Supported optional and nested groups in bygroups(...)

### ISSUE THREAD

**Issue by ComFreek** [pygments/pygments#1474]
## Example

Say we got a language supporting the following lines:
```
declare abc.
declare abc : def.
declare abc : def        .
```

Then, I'd like to be able to use `bygroups` as follows:

```python
(r'(declare)(\s+)(\S+)(\s*)((:)(\s*)(\S+)(\s*))?(\.)', bygroups(
  Keyword,
  Name.Variable,
  Whitespace,
  (Punctuation, Whitespace, Name.Variable, Whitespace),
  Punctuation
))
```

However, with the current Pygments version I get `TypeError: 'tuple' object is not callable`, so I guess this is not supported or intended. Any plans to add support for this?

As a workaround in my lexer, I currently duplicate the lexing rule with and without the optional part.

**Comment by birkenfeld** [comment]
Just make the outer parens non-capturing (with `(?: ... )`), then you don't need a tuple.
