### ISSUE TITLE
Prolog lexer backslash escape does not work properly

### ISSUE THREAD

**Issue by marijnschraagen** [pygments/pygments#1479]
The Prolog lexer does not recognize strings with an escaped (i.e., double) backslash.

For example the following code is valid Prolog:
```prolog
writeln("abc\"def").
writeln("abc\\def").
```
When executed in Prolog the `"` and `\` characters are escaped, so this results in
```none
abc"def
abc\def
```
Pygments however detects a syntax error on the second line:
![pygments_prolog_syntax_error](https://user-images.githubusercontent.com/14089378/84596076-da8aae00-ae5b-11ea-956e-a6b8044d008f.png)
Note that the [Github highlighter for Prolog](https://github.com/alnkpa/sublimeprolog) does it right on the second line but now there is a problem in escaping `"` on the first line.

The behavior should be the same as in, e.g., Python:
```python
print("abc\"def")
print("abc\\def")
```
![pygments_python_syntax_ok](https://user-images.githubusercontent.com/14089378/84596123-2b9aa200-ae5c-11ea-9c5f-e87b4cc00a1c.png)

**Comment by Anteru** [comment]
Fixed, thanks for the report!
