### ISSUE TITLE
Markdown Lexer doesn't recognize strong/emph at the very beginning of the text

### ISSUE THREAD

**Issue by PowerSnail** [pygments/pygments#1492]
Reproduce:

```python
from pygments.lexers.markup import MarkdownLexer

l = MarkdownLexer()

print(list(l.get_tokens("*bolded text*")))
# OUT: [(Token.Text, '*bolded'), (Token.Text, ' '), (Token.Text, 'text*'), (Token.Text, '\n')]

print(list(l.get_tokens(" *bolded text*")))
# OUT: [(Token.Text, ' '), (Token.Generic.Emph, '*bolded text*'), (Token.Text, '\n')]

print(list(l.get_tokens("**bolded text**")))
# OUT: [(Token.Text, '**bolded'), (Token.Text, ' '), (Token.Text, 'text**'), (Token.Text, '\n')]

print(list(l.get_tokens(" **bolded text**")))
# OUT: [(Token.Text, ' '), (Token.Generic.Strong, '**bolded text**'), (Token.Text, '\n')]
```

As shown in the code, if I add a space before the bold-ed/emph-ed text, the lexer outputs `Token.Generic.Strong` for the entire bold-ed/emph-ed phrase. 

If nothing precedes the bold-ed/emph-ed phrase, the lexer sees the phrase as regulart text and breaks down the phrase into parts.

### Environment

Python: Python 3.8.3
Pygments: 2.6.1

**Comment by Leistungsabfall** [comment]
On top of that:
It seems like the MarkdownLexer is only recognizing tokens when they are surrounded by whitespace.

For example this inline code between brackets is not recognized:

    (`my inline code`)

**Comment by Leistungsabfall** [comment]
I created a PR which fixes these issues: https://github.com/pygments/pygments/pull/1495.

**Comment by Anteru** [comment]
I'd say that is comprehensively fixed. Thanks for your contribution!
