### ISSUE TITLE
Can you add language shortnames to the documentation?

### ISSUE THREAD

**Issue by iBug** [pygments/pygments#1501]
I often look through this page <https://pygments.org/languages/> to check which languages I can use with Pygments, but it lacks an important piece of information - the short name for specifying the language.

By "short name", I mean the "language name" part after the opening fence, as shown below:

````markdown
```ruby
#  ^^^^ This part
```
````

It's too common the case that I have to iterate through the Python code in [`pygments/lexers`](https://github.com/pygments/pygments/tree/master/pygments/lexers) to determine which short name I should use. For example, it wasn't intuitive enough that the Python console session has a short name of `pycon`, when we usually don't refer to that feature with "console", but rather "REPL".

May I ask that the short names for each supported language be listed on the documentation page? As far as I am concerned, one short name for each language would be enough.

**Comment by birkenfeld** [comment]
They are all listed on https://pygments.org/docs/lexers/ which is automatically generated from the source code. Maintaining that list manually on /languages would get out of date quickly.
