### ISSUE TITLE
[docs] [help] How to test my new lexer on the command line

### ISSUE THREAD

**Issue by uvtc** [pygments/pygments#1518]
I just wrote the beginnings of a new lexer for the [Janet language](https://janet-lang.org/) and would like to test it. I couldn't find a link to a mailing list or forum, so I'm posting this here, but hopefully it can serve to not only help me but help improve the docs.

This is a lexer for the Janet programming language. My first attempt is: <https://gist.github.com/uvtc/f1fbd0d014bb3b2e60aeb0f3aaca582c>, and I have that saved as "janet_lexer.py".

I've read <https://pygments.org/docs/cmdline/> and <https://pygments.org/docs/lexerdevelopment/> but still cannot figure out how to run and test my pygments lexer on an input.janet file.

I'm on Debian GNU/Linux, and have my janet_lexer.py and input.janet together in the same directory. I have python3-pygments installed via apt, and so have the `pygmentize` command line tool installed.

It appears there's two ways to test my lexer: (1) via the command line, or (2) via a small script where I import the relevant modules and call the `highlight()` function.

I've tried command line incantations like:

    $ pygmentize -f html -o out.html -l janet_lexer.py:JanetLexer input.janet 
    Error: no lexer for alias 'janet_lexer.py:JanetLexer' found

    $ python3 -m pygments -l janet_lexer.py:JanetLexer -x input.janet
    /usr/bin/python3: No module named pygments.__main__; 'pygments' is a package and cannot be directly executed

to no avail.

Can you please tell me how to test my lexer? Once I can try it out and tweak its output, I can then submit a PR to request inclusion into Pygments to support Janet.

Thanks!

**Comment by birkenfeld** [comment]
> And additionally, I didn't know I should append the -f html input.janet to the command.

Well you don't *have* to, without `-f html` you'll get colored output on the terminal, which is usually fine as well, and without specifying the input file you can supply the source to stdin.

I'll amend the docs to say something to that effect.
