### ISSUE TITLE
pygments.bashcomp broken by DOS-style (CRLF) lineendings in pypi package

### ISSUE THREAD

**Issue by mitchblank** [pygments/pygments#1545]
My OS/X homebrew setup started throwing errors when I launched `bash`.  I think I tracked it down to a bad bash completion script which got installed:
```
$ file /usr/local/etc/bash_completion.d/* | grep CRLF
/usr/local/etc/bash_completion.d/pygmentize:                 ASCII text, with CRLF line terminators
```
In the homebrew formula, this file comes direct from the `external/pygments.bashcomp` file inside the Pygments package itself.  Downloading both the current and previous releases from pythonhosted.org (which is what homebrew installs):
* https://files.pythonhosted.org/packages/6e/4d/4d2fe93a35dfba417311a4ff627489a947b01dc0cc377a3673c00cf7e4b2/Pygments-2.6.1.tar.gz
* https://files.pythonhosted.org/packages/5d/9d/208733ccc91b1d2c2af7270ffe3def197504bd8da875bc3fa1dc75039795/Pygments-2.7.0.tar.gz
I see that something did in fact change with how this file got packaged in that tarball:
```
$ file */external/*bashcomp
Pygments-2.6.1/external/pygments.bashcomp: ASCII text
Pygments-2.7.0/external/pygments.bashcomp: ASCII text, with CRLF line terminators
```
...and, sure enough, this causes an easily reproducible regression:
```
$ . Pygments-2.6.1/external/pygments.bashcomp

$ . Pygments-2.7.0/external/pygments.bashcomp
bash: $'\r': command not found
bash: exit 127
bash: Pygments-2.7.0/external/pygments.bashcomp: line 6: syntax error near unexpected token `$'\r''
'ash: Pygments-2.7.0/external/pygments.bashcomp: line 6: `_pygmentize()
bash: exit 2
```
The CRLF lineendings appear to have infected that 2.7.0 tarball in lots of files that had normal UNIX lineendings in the 2.6.1 tarball, so something probably changed in how the packaging was done.  However, most of the python and such wasn't line-ending sensitive; just this `bash` script seems to have suffered.
```
$ file `find Pygments-2.6.1 -type f` | grep "with CRLF line terminators" | wc -l
      28
$ file `find Pygments-2.7.0 -type f` | grep "with CRLF line terminators" | wc -l
     891
```
What is really odd, is that when I downloaded the same release from github's releases page directly and it did NOT have that problem (`file` detected 29 files that appeared to have CRLF line endings, so on par with what I saw on 2.6.1)  So it seems that something about the process about how 2.7.0 got added to pypi seems to have caused the lineendings to be screwed up.  Maybe the github zip was used as an intermediary instead of the tar.gz?

**Comment by birkenfeld** [comment]
I can confirm that the 2.7.0 tarball is odd. You'll be happy to know that I just released 2.7.1 for another regression fix, and the tarball looks good to me.

I'm keeping this open until the release checklist is amended to avoid this in the future.

**Comment by mitchblank** [comment]
Great to hear.  I opened a PR on homebrew to update to that new 2.7.1 release.  Hopefully it will be accepted promptly.  https://github.com/Homebrew/homebrew-core/pull/61254

**Comment by mitchblank** [comment]
Homebrew is now updated to 2.7.1, and the problem I was experiencing has gone away.

**Comment by Anteru** [comment]
@birkenfeld I'll try to figure out how to avoid this. I specifically built the tarball under WSL, but I suspect that checking out the source on Windows combined with CR/LF conversion may have caused this. That said I would have never thought of this to be an actual issue.

**Comment by birkenfeld** [comment]
Right, it should be possible to configure Git to leave line endings alone...

(And I hope Windows editors other than Notepad have learned to cope with Unix line endings by now?)

**Comment by Anteru** [comment]
Yeah, of course they do :) That's not the problem -- it's just a source of error I didn't have on my radar. I'll add an item to the release checklist for that this weekend so we won't have that happening again.
