### ISSUE TITLE
Incorrect spacing between words.

### ISSUE THREAD

**Issue by jyjdal** [pygments/pygments#1558]
I'm working on a program which uses Pygments as a tool.
When generating an image, Chinese characters become random codes, so I choose to use a font that supports Chinese.
However, it becomes like this
![error py](https://user-images.githubusercontent.com/52844714/94589420-d1610800-02b7-11eb-89cc-297629e814d2.png)
As you can see, it has something wrong with the spacing and I don't know why, is that a bug or a mistake of me?
Thanks.

**Comment by lielie-0125** [comment]
This is what happens when I didn't specify the font: Chinese characters became random codes.
![error py](https://user-images.githubusercontent.com/52844714/94589768-492f3280-02b8-11eb-987c-399e7dcef9a6.png)

**Comment by Anteru** [comment]
This can be closed due to the fix in #1611, correct?

**Comment by jyjdal** [comment]
That's right, sir. Thank you very much.



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pygments/pygments"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月6日(星期三) 晚上7:19
收件人:&nbsp;"pygments/pygments"<pygments@noreply.github.com&gt;;
抄送:&nbsp;"九月家的敖烈"<lielie_0125@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [pygments/pygments] Incorrect spacing between words. (#1558)





 
This can be closed due to the fix in #1611, correct?

**Comment by Anteru** [comment]
All credit to @15b3 :) - Thanks for getting back quickly, closing now.
