### ISSUE TITLE
new lexer request: gnu data language

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#156]
(Original issue 377 created by None on 2008-12-03T22:20:16+00:00)

Hi 

it would be nice if we could get a lexer for gdl sources
http://gnudatalanguage.sourceforge.net/

cheers
Reimar

Reported by ReimarBauer

**Comment by Anteru** [comment]
(Original comment by thatch on 2009-06-21T21:47:32+00:00)

A link to a language description or example file would be nice.

**Comment by birkenfeld** [comment]
I'm closing all requests for lexers/formatters without a patch/PR.
