### ISSUE TITLE
c++: `has_value()` function marked as generic Name rather than Function.Name

### ISSUE THREAD

**Issue by tabatkins** [pygments/pygments#1561]
Another change I noticed when bumping from 2.6.1 to 2.7.1, probably as part of <https://github.com/pygments/pygments/commit/fc56ab883a80f6182339d7fbf95e531ff32e4809>.

In the following code:

```cpp
constexpr bool has_value() const noexcept;
```

`has_value` was previously marked as Name.Function, but now it's marked as just Name. I suspect it should still be Name.Function.

**Comment by tabatkins** [comment]
I'm seeing changes in both directions, actually:

In:
```cpp
 E& error() &;
```

The `error` token was Name in 2.6.1, and is Name.Function is 2.7.1 (looks like a correct change).

While in:
```cpp
 virtual const char* what() const noexcept override;
```

The `what` was Name.Function in 2.6.1, and is just Name in 2.7.1 (looks like an error).

All of these examples were taken from <http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p0323r8.html>, btw.

**Comment by amitkummer** [comment]
I am also seeing that function names with `::` are tokenized as Names:

```cpp
int Type::has_value() {}
```

has_value is tokenized as a Name and not Name.Function. I think this is because the lexer has a list of identifiers it uses to match function names and ':' is not on this list.
