### ISSUE TITLE
pygmentize -S does not use the styler

### ISSUE THREAD

**Issue by jfmoulin** [pygments/pygments#1566]
Under Linux mint 20:
invoking 
`pygmentize -l python mipy.py `
works correctly, whereas when I try to specify a style (using a name listed by pygmentize -L)
`pygmentize -S inkpot -l python mipy.py `
returns the help page

**Comment by birkenfeld** [comment]
`-S` is the option to print general style definitions (e.g. CSS) for a given style.

To *use* a given style, `style` is a formatter option, e.g. `pygmentize -O style=inkpot mipy.py`.
