### ISSUE TITLE
2.7.1: tests/examplefiles is missing from PyPI package, but required by test_lexers_other.py

### ISSUE THREAD

**Issue by sandrotosi** [pygments/pygments#1567]
Hello,
`test_lexers_other.py` [requires](https://github.com/pygments/pygments/blob/master/tests/test_lexers_other.py#L74-L82) a couple of files from tests/examplefiles, but that directory is not shipped in the PyPI tarball, so the full test suite cant be executed.

**Comment by birkenfeld** [comment]
Hi Sandro, for me it looks like the files *are* shipped in the source tarball. Are you sure you aren't removing them for Debian (because of unclear licenses, I seem to remember...)?

**Comment by sandrotosi** [comment]
you're right, we needed to remove it due to unclear licensing -- thanks!
