### ISSUE TITLE
Add morhetz's "gruvbox" theme to the styles list. [Feature Request]

### ISSUE THREAD

**Issue by Saul-Dickson** [pygments/pygments#1571]
Many people use gruvbox as the theme for, well... as many things as possible. It is, on its own, a vim theme. There are many ports to other things as well. For example, my Fast-Syntax-Highlighting custom theme is gruvbox based and is available at `https://github.com/Saul-Dickson/dotfiles/blob/master/.config/fsh/overlay.ini`. There is also a `.yml` file for it at `https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/alacritty/Gruvbox%20Dark.yml`.

**Comment by yu-andy** [comment]
Hi there!

We (Aaron, Aiman, Andy, Georgia, and Sakib) are currently taking the course Software Process Improvement at the University of Adelaide as an elective in our Honours degrees. As part of the course, we are tasked with contributing to an open source project and we would like to tackle this issue!

Our team aims to submit our initial pull requests by late April/early May.
In terms of actually adding gruvbox as a theme, from other similar issues it seems like we need to 1) Add it to the list of available styles in pygments/styles/__init__.py and 2) Create a new file in pygments/styles which contains a class for the new style. Are there any other details that we should be made aware of?

Any helpful tips would be much appreciated!

**Comment by Anteru** [comment]
Yes, that's pretty much it -- and thanks for picking Pygments as your open source project you want to contribute to! You can always look at another style change and use that as a template, for instance: https://github.com/pygments/pygments/pull/1662/files

What you may want to do is update the documentation along the way, as there is no "Writing your own style" chapter yet. You could also look at running it through the script here once done: https://github.com/pygments/pygments/issues/1718 to see how well your style fares in terms of accessibility, but that's optional :) Given you're five folks, just writing a single style might be a bit boring :)

**Comment by yu-andy** [comment]
Awesome, thank you! We'll definitely have a go at updating the docs and running it through the script :)
Do we need to be assigned to the issue?

**Comment by Anteru** [comment]
It's not required but I assigned you, just in case someone wants to work on this and doesn't check the issue for status :)

**Comment by AaronC23** [comment]
Hi!Aaron here, one of the students taking on this pull request, you mentioned there is no "Writing your own style" chapter yet. In your documentation here: https://pygments.org/docs/styles/#creating-own-styles. It looks like there is a "Creating own styles" chapter, is this what you wanted or something different?

**Comment by Anteru** [comment]
I have totally missed that because it's not in the place where the other "Write your own ..." docs are: https://pygments.org/docs/ -- I think it would make sense to move this to the top level.

**Comment by birkenfeld** [comment]
It's now moved to a better place, I hope.

**Comment by yu-andy** [comment]
Hi @Anteru looks like this one already got completed (https://github.com/pygments/pygments/pull/1763) while we were working on it! Can we pick up https://github.com/pygments/pygments/issues/1678 instead? Now that we have a good handle on how to write a style, we should be able to put up a PR quickly :)

**Comment by Anteru** [comment]
Sure
