### ISSUE TITLE
C# interpolated strings not supported

### ISSUE THREAD

**Issue by MongoCaleb** [pygments/pygments#1573]
[Interpolated Strings](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated) cause the code to lose all syntax formatting. Removing the `$` and just using boring strings works. 

This works:
```
                Console.WriteLine("I created a key named" + newKey.Name +
                    "Is it enabled?" + newKey.IsEnabled);
```
This doesn't:
```
                Console.WriteLine($"I created a key named {newKey.Name}. " +
                    $"Is it enabled? {newKey.IsEnabled}");
```

**Comment by ashantilong** [comment]
claim

**Comment by matrdr** [comment]
It seems that they do not crash the entire system any more. But the dollar signs get highlighted by putting a red box around them which looks horrible.
![image](https://user-images.githubusercontent.com/45005058/111441511-af453000-8707-11eb-85ef-d6299a581810.png)
