### ISSUE TITLE
Parsing input inline , is it possible?

### ISSUE THREAD

**Issue by blackjyn** [pygments/pygments#1575]
I know that we can print the result to stdOut like this:
`pygmentize -f html source.ext`

Nah, is it possible that we can parse code inline? 
For instance  I have PHP code `$str='Hello World;` and I want to pygmentizing inline like :

`pygmentize -f html -l php "$str='Hello World;"`

Is it possible? 

EDIT: The real question is : "Will this feature be implemented?" since I think this will be very nice if it be implemented.

**Comment by birkenfeld** [comment]
The default source is standard input, so you can use `echo "$str='Hello World;" | pygmentize` or `pygmentize <<<"$str='Hello World;"` (here string syntax).
