### ISSUE TITLE
Invalid MATLAB example?

### ISSUE THREAD

**Issue by senden9** [pygments/pygments#1582]
Hi!

The Matlab test file seems to have a invalid block comment in it. According to the [official documentation](https://www.mathworks.com/help/matlab/matlab_prog/comments.html) block comments start with `%{` and end with  `%}`. The test file has the comment start sequence swapped.
https://github.com/pygments/pygments/blob/3e1b79c82d2df318f63f24984d875fd2a3400808/tests/examplefiles/matlab_sample#L28-L30

**Comment by Anteru** [comment]
Good catch, thanks!
