### ISSUE TITLE
Rust Lexer Needs Work

### ISSUE THREAD

**Issue by SethWalkeroo** [pygments/pygments#1585]
I've been trying to use the **Rust lexer** for syntax highlighting in my tkinter application, but the default tokens are pretty bad. It is possible that I could be doing something wrong, but I have used 10 other lexers, and they have worked much better than this one. 

_Here is an example of what I am talking about..._

![rust](https://user-images.githubusercontent.com/16292617/97092035-b3a86980-15fd-11eb-9261-bb3bc15d7842.png)

**Comment by birkenfeld** [comment]
Thanks for the report, but I can't reproduce this.  This looks very strange, especially the 1-character numbers and keywords.  I know the Rust lexer had some problems in earlier Pymgents versions, but it was (as far as I remember) never as broken as that.

You can check out the highlighting of the current version yourself at https://pygments.org/demo/

**Comment by SethWalkeroo** [comment]
@birkenfeld Alright, it might just be the way I am implementing it. I will try to pin down my issue. Thanks for the quick response though; I really appreciate that.
