### ISSUE TITLE
Doxygen comments in django/javascript code creating weird behaviour from lexer

### ISSUE THREAD

**Issue by boanergies** [pygments/pygments#1588]
With the following code as an example
```
/**
  * @param {*} cool
  */
func = function(cool) {
};

/**
 * @param {*} stuff
 */
fun = function(stuff) {
};
```

For some reason the first '*' in '{\*}' causes everything after it to be marked a Token.Comment until you hit the second '{\*}'. The weirder thing is the behaviour only happens if both '{\*}' are present. Remove either one of the '{\*}' and it works as expected. Is there a formatter, filter, or another lexer I'm supposed to use to help with doxygen comments?

I confirmed this by running it through the demo you have on your website.

Just to clarify I'm using the javascriptDjangoLexer and I see the behaviour already happen before my filters run so its not any of my custom filters or formatters making something weird happen.

For reference of the correctness of the commenting you can look at JSDoc [here](https://jsdoc.app/tags-param.html)

**Comment by birkenfeld** [comment]
Well, `{* ... *}` and `{# ... #}` are comments for the Django template language.

**Comment by boanergies** [comment]
the second statement is true as I found [here](https://docs.djangoproject.com/en/3.1/ref/templates/language/#comments) but I don't see docs supporting that `{\* ... \*}` are comments, do you have a link supporting your claim?

**Comment by birkenfeld** [comment]
It looks like the lexer is mistaken there.  Do you want to make a PR to fix it?

**Comment by boanergies** [comment]
Sure I can do that, it looks like it will be a one line fix from the code
