### ISSUE TITLE
console lexer (BashSessionLexer) fails with quotes inside comments

### ISSUE THREAD

**Issue by j1elo** [pygments/pygments#1598]
Hi, I'm facing failures from Pygments while trying to build my project's documentation with Sphinx; after some analysis I discovered that the issue comes from single quotes (`'`) being used within comments.

A block such as this one causes the issue:

```
.. code-block:: console

   # My project's build script
   echo "Hello World"
```

the [code-block](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-code-block) will try to parse its contents with the `console` lexer from Pygments, which fails:

```
WARNING: Could not lex literal_block as "console". Highlighting skipped.
```

Removing the single quote solves the issue:

```
.. code-block:: console

   # My projects build script
   echo "Hello World"
```

Pygments and Sphinx versions:

```
$ pip3 freeze | grep -i -e sphinx -e pygments
Pygments==2.7.2
Sphinx==3.3.0
```

I searched for "console" and "console quote" and couldn't find an already existing bug so I'm opening this one. Sorry if this is a duplicate (I somehow believe this bug must have been reported already, using a single quote in simple-form English comments seems too much of a common use case to have this bug unnoticed... but I haven't found anything)

**Comment by j1elo** [comment]
The linked commit ([d368202](https://github.com/Kurento/doc-kurento/commit/d3682029e234519e8d3c365f23b68bb42860c651)) shows the real situation where I hit this issue.

**Comment by birkenfeld** [comment]
Hey @j1elo, the `console` lexer is meant for cases where you include shell prompt, command and output, e.g.
```
# ls -l
total 128
-rw-r--r-- 1 gbr gbr  8816 Oct 24 21:54 AUTHORS
-rw-r--r-- 1 gbr gbr 40808 Oct 24 21:54 CHANGES
```
The `#` at the start of a line here is recognized as a common prompt (for the root user), not as a comment sign.

If you're presenting pure shell code, you should use one of the shell lexers, usually `bash`.

**Comment by j1elo** [comment]
> Hey @j1elo, the `console` lexer is meant for cases where you include shell prompt, command and output, e.g.
> 
> ```
> # ls -l
> total 128
> -rw-r--r-- 1 gbr gbr  8816 Oct 24 21:54 AUTHORS
> -rw-r--r-- 1 gbr gbr 40808 Oct 24 21:54 CHANGES
> ```
> 
> The `#` at the start of a line here is recognized as a common prompt (for the root user), not as a comment sign.
> 
> If you're presenting pure shell code, you should use one of the shell lexers, usually `bash`.

Oh my, that means I was very wrong about the intended use case of `console`! (I've been using it all across the docs for everything related to a console... both command samples and shell code).

The way I see it, this grants then a "documentation" bug in the sense that the docs are *really* too bare and somewhat confusing. I'll open a couple new issues wrt. to this topic, and close this one in a couple of days (just in case some more insightful comments happen to arrive).
