### ISSUE TITLE
console lexer (BashSessionLexer) description lacks detail

### ISSUE THREAD

**Issue by j1elo** [pygments/pygments#1599]
After reporting an issue with the `console` lexer seemingly wrong behavior with single quotes in comment sections (https://github.com/pygments/pygments/issues/1598) it turns out the issue was just a matter of misuse.

I believe this is a documentation bug in the sense that the current description in the user docs ("*Lexer for simplistic shell sessions*", [BashSessionLexer](https://pygments.org/docs/lexers/#pygments.lexers.shell.BashSessionLexer)) is not even trying to convey the most basic concept of intended usage and explanation of the behavior.

Even something simple such as the example given in the other issue would already be a big improvement:

https://github.com/pygments/pygments/issues/1598#issuecomment-725224524

> the `console` lexer is meant for cases where you include shell prompt, command and output, e.g.
> 
> ```
> # ls -l
> total 128
> -rw-r--r-- 1 gbr gbr  8816 Oct 24 21:54 AUTHORS
> -rw-r--r-- 1 gbr gbr 40808 Oct 24 21:54 CHANGES
> ```
> 
> The `#` at the start of a line here is recognized as a common prompt (for the root user), not as a comment sign.
> 
> If you're presenting pure shell code, you should use one of the shell lexers, usually `bash`.

**Comment by birkenfeld** [comment]
Thanks, this is a very good point.

**Comment by j1elo** [comment]
Quite terse, but already much better than before. Thanks!

**Comment by pspacek** [comment]
I guess someone in future might appreciate an example, so here is one generated using Sphinx:

- Bash
![code-block-bash](https://user-images.githubusercontent.com/11509590/161698847-a8f3c6c7-7d3b-49e3-9094-c06489b1ebc5.png)

- Console
![code-block-console](https://user-images.githubusercontent.com/11509590/161698852-e519b159-14d0-4776-a96c-f5b1f494451a.png)
