### ISSUE TITLE
new formatter request: postscript

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#161]
(Original issue 382 created by ivazquez on 2008-12-19T02:45:44+00:00)

It would be nice to have PostScript output with an optional pygmentize destination of a printer so that enscript could finally be sent packing.

**Comment by Anteru** [comment]
(Original comment by thatch on 2009-02-22T23:15:47+00:00)

ivazquez, do you see this being most useful as a Letter/A4 formatter, or side by side half sheet (2x A5, rotated and laid out on an A4) like I think enscript does?

**Comment by birkenfeld** [comment]
I'm going to close all requests for lexers/formatters without a patch/PR.
