### ISSUE TITLE
Integration with OSS-Fuzz

### ISSUE THREAD

**Issue by Google-Autofuzz** [pygments/pygments#1628]
Hello pygments people,

I've started to fuzz a bit pygments, and found a [couple of DoS]( https://github.com/pygments/pygments/issues?q=author%3AGoogle-autofuzz ). I've automated the process by integrating pygments [into OSS-Fuzz]( https://github.com/google/oss-fuzz/pull/4794 ): I just need an email address to throw the issues at, since there is no integration with github (for now).

Thanks

**Comment by birkenfeld** [comment]
I've set up fire-bot, so you can send emails to `pygments-reports/fire.fundersclub.com` and they should show up here as issues.

**Comment by birkenfeld** [comment]
Thanks for the effort, btw, we appreciate it a lot!

**Comment by birkenfeld** [comment]
How can we access the now reported bugs? I get "Permission denied" when I use the link, e.g. bugs.chromium.org/p/oss-fuzz/issues/detail?id=28605

**Comment by Google-Autofuzz** [comment]
It seems that you [need to provide a Google account]( https://google.github.io/oss-fuzz/getting-started/new-project-guide/#reviewing-results ) for the email address.

**Comment by birkenfeld** [comment]
Does the address have to be associated with the account?

**Comment by Google-Autofuzz** [comment]
Unfortunately, it seems so, yes

**Comment by birkenfeld** [comment]
ok, then please change the address to georg@python.org, the Google account name is georg.brandl - I will create the issues manually.

**Comment by Google-Autofuzz** [comment]
As I'm taking a couple of days off, feel free to send a pull-request on your own, the relevant file being https://github.com/google/oss-fuzz/blob/master/projects/pygments/project.yaml

Or wait until I come back :)

**Comment by birkenfeld** [comment]
Ok, thanks. I made a PR (https://github.com/google/oss-fuzz/pull/4856) but I won't sign a CLA just for that.

**Comment by birkenfeld** [comment]
So I've fixed the first two issues from there already :+1:

What I've noticed, though, is that in the fuzz target you do `str(bytes)` to get the input: this will always end up with an input in the form `b'...'` or `b"..."`, so in many languages it only lexes as a single string.

It would probably be better to use `.decode('latin1')` or `.decode('utf8')` with a fallback to latin1. What do you think?

**Comment by Google-Autofuzz** [comment]
I'm unsure it's worth falling back to `latin1`, woudn't `.decode('utf-8', 'ignore')` be enough?

**Comment by birkenfeld** [comment]
Sure, although I don't know if the fuzzer likes that whole stretches of bytes are completely ignored?  Will it "learn" to produce valid UTF-8, or just mostly produce ASCII?

**Comment by birkenfeld** [comment]
Nice! One more question, is it possible to record which lexer was chosen for the highlight? It will speed up local reproduction with the test case, since I'm not sure that guessing is 100% reproducible.

**Comment by Google-Autofuzz** [comment]
You can throw the "Minimized Testcase" at something like this:

```python
import sys
import pygments
import pygments.formatters
import pygments.lexers

with open(sys.argv[1]) as f:
  data = f.read().decode('utf-8')

lexer = pygments.lexers.guess_lexer(data)
print('lexer: %s' % lexer)
pygments.highlight(data, lexer, pygments.formatters.HtmlFormatter())
```

**Comment by birkenfeld** [comment]
Sure, but as I said, I'm not sure that this will always result in the same guess for some given input.  I should check that myself, however :)

**Comment by Google-Autofuzz** [comment]
You mean that the lexer guessing isn't deterministic? If it's the case, we should make it dedterministic by hooking whatever randomness there is there, and hook it up the fuzzer's input.

**Comment by birkenfeld** [comment]
Yep. There's a few of dictionaries involved :) But maybe the fuzzer already disables Python hash randomization?

Anyway, I will check this carefully and get back to you.

**Comment by birkenfeld** [comment]
In the meantime: how can I reproduce the effect of `ConsumeUnicode`?  Can you give me an explanation of how to turn the downloaded testcases into what the lexer sees?

Slightly related: instead of guessing, should the input data just be lexed with *all* available lexers?  This will make fuzzing more useful, since some lexers don't have any useful "guessing" routine, and so will never be utilized.

**Comment by Google-Autofuzz** [comment]
For `ConsumeUnicode`, I have nothing better to offer than the [implementation]( https://github.com/google/atheris/blob/d558fea27d2322bed441891de0aaf09fcef6a473/fuzzed_data_provider.h#L62 ).

As for running the input on all available lexers, I'm afraid that it would take too long and timeout. What we can do however, is having a second fuzzer (because we still want to fuzz the guesser, right?) picking a lexer "at random" and throw the input at it. What do you think?

**Comment by jvoisin** [comment]
Coverage is now around [70%](https://storage.googleapis.com/oss-fuzz-introspector/pygments/inspector-report/20230820/fuzz_report.html)!

**Comment by Anteru** [comment]
Thanks a lot for the fuzzing work! Found quite a few serious issues already, and this is one of those projects where fuzzers tend to find particularly gnarly issues :)

**Comment by jvoisin** [comment]
Feel free to add your email address [here]( https://github.com/google/oss-fuzz/blob/master/projects/pygments/project.yaml ) if you want to get access to all the crashes :)

**Comment by jvoisin** [comment]
I think this issue can be closed :)
