### ISSUE TITLE
new lexer request: opencl

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#164]
(Original issue 385 created by None on 2009-01-17T06:20:27+00:00)

OpenCL support would be great.  Should just be a few more reserved words than c99. 

Reported by guest

**Comment by Anteru** [comment]
(Original comment by thatch on 2009-06-21T18:52:38+00:00)

Using a C lexer on [http://en.wikipedia.org/wiki/OpenCL OpenCL] code doesn't appear to have any errors, it just doesn't know about the additional words.

The pages that might describe such words are accessible from [http://www.khronos.org/registry/cl/] but I don't have the time to integrate this at the moment, so it's moving to Someday.

**Comment by birkenfeld** [comment]
I'm closing all requests for lexers/formatters without a patch/PR.
