### ISSUE TITLE
spaces are not preserved while generating html for python3 lexer

### ISSUE THREAD

**Issue by animesh-sharama** [pygments/pygments#1641]
I am trying to generate html for the file 
```
print('{0} {1} are varialbes'.format('abc', 'xyz'))
```
as below
The generate html does not have the spaces preserved between **{0} {1}**
If I try the same with python lexer not python3 then spaces are preserved.
But python lexer lacks support for unicode - https://github.com/pygments/pygments/issues/1233  

Can someone suggest any quick way such that I have unicode support and well as space preserved?

**Comment by Anteru** [comment]
I just tried this with Pygments 2.7.3 and it works correctly (and Pygments does support Unicode now.) Can you please provide some repro steps for your issue?

**Comment by birkenfeld** [comment]
See https://pygments.org/demo/?lexer=python&code=print('%7B0%7D%20%7B1%7D%20are%20varialbes'.format('abc'%2C%20'xyz')) - spaces are not lost.
