### ISSUE TITLE
Missing shell keyword `in`

### ISSUE THREAD

**Issue by jmd-dk** [pygments/pygments#1652]
The [shell lexer](https://github.com/pygments/pygments/blob/master/pygments/lexers/shell.py) does not include the `in` keyword. In particular, the `BashLexer` class contains the following basic tokens:
```
if|fi|else|while|do|done|for|then|return|function|case|select|continue|until|esac|elif
```
which does not include `in`. Thus Bash code like
```bash
for i in 1 2 3; do
    echo $i
done
```
is not lexed and formatted correctly with respect to `in` (unlike the rendering above as done by GitHub).

This is easily fixed by just adding `in` to the list of tokens. I believe the `in` keyword is not present for *any* of the shell lexers in `lexers/shell.py`, though I do not know which of the non-Bash shells also supports this keyword.

**Comment by Anteru** [comment]
Thanks, good catch! As far as I can tell, it's in PowerShell already, it's not in TCSH, but it's a keyword in Bash/ZSH/KSH, so I added it to the `BashLexer` only.
