### ISSUE TITLE
Python parser: pull out Keyword arguments 

### ISSUE THREAD

**Issue by alexlenail** [pygments/pygments#1654]
In sublime, keyword arguments in python get a color. Not so in pygments' monokai. How would one address this?

**Comment by Anteru** [comment]
You would have to teach the Python lexer to add some extra class to them, and then use that in the theme. That's how you'd make this work, but I'm not entirely sure we can reliably determine keyword arguments given we're _not_ a Python lexer which understands the underlying language, but just a syntax highlighter. Some highlighting can be only done with additional context information which I presume Sublime has.
