### ISSUE TITLE
Add "nord" theme to the styles list. 

### ISSUE THREAD

**Issue by ScrumpyJack** [pygments/pygments#1678]
The amazing nord theme can be found here https://nordtheme.com

**Comment by ScrumpyJack** [comment]
Can you use this one?

https://github.com/sbrisard/nord_pygments

**Comment by yu-andy** [comment]
@Anteru Made a PR for this here https://github.com/pygments/pygments/pull/1799 could you take a look?

**Comment by Anteru** [comment]
Implemented via #2189
