### ISSUE TITLE
Highlight error with C++ code

### ISSUE THREAD

**Issue by HeRaNO** [pygments/pygments#1695]
When highlighting the code [here](https://github.com/HeRaNO/OI-ICPC-Codes/blob/master/test.cpp), there're errors on line 33 and line 34.

```cpp
	int m21=((result_0*0+result_1*/*0<-----*/1)%mod+mod)%mod;
	int m22=((result_0*1+result_1*/*1<-----*/0)%mod+mod)%mod;
```

But it should be like this, and the code itself has no error.

![](https://user-images.githubusercontent.com/18643142/106011031-0dd13300-60f5-11eb-87a9-1fce04b972f3.png)

Would someone take a look at it?

**Comment by birkenfeld** [comment]
Funny, github's highlighter also fails here. Anyway, on our side this was a (misguided I think now) attempt to catch wrong comment-ends. Thanks for the report!
