### ISSUE TITLE
sphinx + emphasized lines + line numbering in inline mode = unexpected result

### ISSUE THREAD

**Issue by joerg-vandervlies** [pygments/pygments#1698]
Hi,

recently I read that sphinx will change the way lines are numbered in the next versions from table style to inline style. I made a quick test in my project and found that the combination of inline line numbers together with emphasized lines doesn't look right:

![image](https://user-images.githubusercontent.com/28155731/106386341-c5f02b80-63d4-11eb-9c89-cd350455a3f9.png)

As you can see, the emphasized lines are incorrectly wrapped and I couldn't find a quick fix with custom css on my side.

Is this issue addressed correctly to this project and if so, can you confirm it's a bug? Or do I need to address this to the sphinx project?

kind regards
Jörg

**Comment by Anteru** [comment]
If it's broken with Pygments without Sphinx, then it's a bug here, if it's only broken when used within Sphinx it's an issue "over there". Can you try to reproduce this with just using Pygments? I'm not entirely sure what is actually going wrong here ... and it would be good to know if we need to notify the Sphinx folks to use a particular version of Pygments.

**Comment by joerg-vandervlies** [comment]
I think I know now what's going on. Let me show you.

So this is how the snippets used to look in my project. I'm using the rtd theme and the line numbers were generated with a table:
![image](https://user-images.githubusercontent.com/28155731/106396846-d1f6e000-640a-11eb-8a77-0e96f60384e0.png)
Note that the highlighted lines are fully highlighted from left to right, not only the text portion.

When I read that Sphinx will switch to inline numeration within the next two versions I tried it and it looked like this:
![image](https://user-images.githubusercontent.com/28155731/106396937-3f0a7580-640b-11eb-8f4b-0899bedb4c4d.png)

The unexpected line wraps are the result of this small css rule:
```
.rst-content div[class^=highlight] pre .hll {
    display: block;
    margin: 0 -12px;
    padding: 0 12px;
}
```

Its purpose is to make highlighted lines or highlighted blocks look better. The approach was not a problem when the `span` tags with class `hll` had their own lines in the `pre` block, but now that they have to co-exist with the prepended line numbers, it doesn't work as intended any more.

For comparison: this is how the code snippet looks when generated directly with the `pygmentize` command:
![image](https://user-images.githubusercontent.com/28155731/106397218-82191880-640c-11eb-8adf-4e4fdbcd1dbc.png)

```
pygmentize -f html -l http -o test.html -O style=lovelace,linenos=inline,full=True,hl_lines="2 7 14 15 16 17" http-response.txt
```
(This is the test file: [http-response.txt](https://github.com/pygments/pygments/files/5900594/http-response.txt))

Next I tried to find a non-invasive (i.e. css only) way to correct the display, but to no avail. The way the html tags are nested makes it impossible to style a complete line as shown in the first image. After a lot of experiments I finally found a nice solution that requires only a minimal change in the way the html tags are rendered.

Currently, the `linenos` element is placed outside the highlighted line:
![image](https://user-images.githubusercontent.com/28155731/106397671-d9b88380-640e-11eb-935a-0b21e1c0e221.png)

The solution is easy, just place it inside:
![image](https://user-images.githubusercontent.com/28155731/106397717-0a98b880-640f-11eb-9659-da4d27328319.png)

I tried it and if I _disable that theme specific css rule_, the result looks like this after rebuilding everything:
![image](https://user-images.githubusercontent.com/28155731/106397763-4d5a9080-640f-11eb-979e-fd42100274db.png)
It looks exactly like the output from `pygmentize`.

If I _enable the theme specific rule_ again, it looks like this:
![image](https://user-images.githubusercontent.com/28155731/106397804-8d217800-640f-11eb-85a0-5d9a9acf35c6.png)
That's how it was supposed to look like from the beginning.


I think the suggestion 
- is the smallest possible change I can think of right now
- works independently of Pygments styles or themes
- does not break any existing solution
- lets theme designers working on top of Pygments control the appearance to their liking

What do you think?

kind regards
Jörg


P.S.: you may have noticed that the line numbers have opaque backgrounds which looks quite ugly, especially in dark themes like `monokai`, but I did not want to address two topics in a single issue ;)

**Comment by Anteru** [comment]
Thanks for the detailed investigation. I agree that putting the span tag into the highlight one makes more sense -- could you please prepare a PR for this? It should be fairly easy, and you seem to have all the testing infrastructure in place already :)

**Comment by Anteru** [comment]
Can you please give https://github.com/pygments/pygments/tree/fix/1698-lineos-wrapping a try and see if that works for you?

**Comment by joerg-vandervlies** [comment]
Hi,

I have to confess that I never wrote a single line of Python, so I'm glad you prepared a fix. :)


monokai, first attempt:
![image](https://user-images.githubusercontent.com/28155731/106959418-e99bd480-673a-11eb-85e0-b02fc762fb5d.png)

I added a little bit of css to correct the line number colors:
```
span.linenos {
	color: inherit;
	background-color: transparent;
	padding-left: 5px;
	padding-right: 10px;
}
```
Without the css fix, it doesn't look right, especially in the dark themes.

monokai, second attempt:
![image](https://user-images.githubusercontent.com/28155731/106959311-c83ae880-673a-11eb-89a8-c49c23bdda43.png)


And that's how the snippets look like now. I used a few different styles to test your fix.

lovelace:
![image](https://user-images.githubusercontent.com/28155731/106958861-37640d00-673a-11eb-9497-d5a1d325dcf0.png)

default:
![image](https://user-images.githubusercontent.com/28155731/106958936-4fd42780-673a-11eb-9c31-79d656a82fd2.png)

perldoc:
![image](https://user-images.githubusercontent.com/28155731/106959060-78f4b800-673a-11eb-87cc-854a4e4fdc6d.png)

bw:
![image](https://user-images.githubusercontent.com/28155731/106959134-8ca01e80-673a-11eb-9408-fbe81362f4ce.png)

fruity:
![image](https://user-images.githubusercontent.com/28155731/106959213-ad687400-673a-11eb-9699-9be3940d65a3.png)


The fix in the HTML formatter works great. Thank you!

It would be perfect if you could also apply the small change in the css.

thank you and kind regards
Jörg

**Comment by Anteru** [comment]
The CSS fix shouldn't be necessary, as this indicates a deeper underlying issue. The `linenos` style is defined to use:
```python
self.style.line_number_color,
self.style.line_number_background_color
```

If that's off, that indicates the style is not setting that correctly. That said, it's easy to fix it in post if you want with a CSS rule. What I did is change the style defaults to match your CSS rules (so line numbers look "neutral") instead of forcing them to black/white. This doesn't fix `linenospecial`, but at least it can be fixed locally in the style (or via CSS rules.)

**Comment by joerg-vandervlies** [comment]
I understand and agree.

Thank you again and I'm looking forward to the release
Jörg
