### ISSUE TITLE
PostgreSQL lexer problems

### ISSUE THREAD

**Issue by nikchha** [pygments/pygments#1723]
Hi,

I really like your library and use them together with minted in my LaTeX documents. I would like to highlight a PostgresSQL schema but have some problems with the syntax highlighting.

I tried the following lexers (which one should be used?): `PL/pgSQL`, `PostgreSQL console (psql)`, `PostgresSQL SQL dialect`

`PL/pgSQL` and `PostgresSQL SQL dialect` highlight some column names and `PostgreSQL console (psql)` only highlights the first line. Is there a problem with the lexers? Or am I using them the wrong way? 

### `PL/pgSQL`

![image](https://user-images.githubusercontent.com/37020365/108873906-ea1de180-75fb-11eb-9193-d4ef58760b9e.png)

### `PostgreSQL console (psql)L`

![image](https://user-images.githubusercontent.com/37020365/108873970-f9049400-75fb-11eb-8104-ae7b9fb54601.png)

### `PostgresSQL SQL dialect`

![image](https://user-images.githubusercontent.com/37020365/108874042-0faaeb00-75fc-11eb-8a1f-70728a18ef31.png)

Thank you very much !

**Comment by Anteru** [comment]
For SQL, you should use "PostgresSQL SQL dialect". PostgreSQL console is for interactive console sessions, and PL/pgSQL is for procedural functions ([PL/pgSQL language](https://www.postgresql.org/docs/current/plpgsql.html)). If all you want is basic SQL statement highlighting, "PostgresSQL SQL dialect" is the right choice.
