### ISSUE TITLE
Octave comment block

### ISSUE THREAD

**Issue by CameraEngineer** [pygments/pygments#1726]
It looks as though the large comment block doesn't appear to recognize the key characters to initiate a comment when highlighting with octave.
![image](https://user-images.githubusercontent.com/65438903/109214660-5836e580-776f-11eb-8906-f3c48003422c.png)

Looking at the octave documentation, it can be done two ways.

Thanks!

**Comment by birkenfeld** [comment]
Thanks for the review, both types of block comments are now recognized.
