### ISSUE TITLE
Remove stale branches in git repo

### ISSUE THREAD

**Issue by kurtmckee** [pygments/pygments#1732]
Hello, while browsing the branches I found that a number of branches have been left in the repo.

It appears many are multiple years old, and some have already been merged. Would you consider removing the stale and/or merged branches as you have time?

Thank you so much for considering this request!

**Comment by Anteru** [comment]
Absolutely. I'll try to give it a few cycles soon, I thought most open branches were due to old PRs that got ported and which are waiting to get merged ... but cleaning the backlog is definitely becoming increasingly necessary.

**Comment by kurtmckee** [comment]
Looks like the stale branches have decreased. Closing now. Thanks @Anteru!
