### ISSUE TITLE
AutoIt <> AutoHotkey lexer

### ISSUE THREAD

**Issue by mlipok** [pygments/pygments#1733]
Please split this:
https://github.com/pygments/pygments/blob/master/pygments/lexers/automation.py

in two separate files:
https://github.com/pygments/pygments/blob/master/pygments/lexers/autoit.py
https://github.com/pygments/pygments/blob/master/pygments/lexers/autohotkey.py

**Comment by birkenfeld** [comment]
Why? The location of a lexer is not very relevant, and we don't have a policy for one lexer per module.

**Comment by kurtmckee** [comment]
It appears this ticket can be closed.

**Comment by mlipok** [comment]
> Why? The location of a lexer is not very relevant, and we don't have a policy for one lexer per module.

Because `AutoIt` and `AutoHotkey` are two different languages with completely different syntax.

**Comment by Anteru** [comment]
I don't see the problem? We have plenty of languages with different syntax in the same file if they're somewhat related, and that applies here as well. See `data.py` or `esoteric.py` for instance.
