### ISSUE TITLE
Latex unable to render

### ISSUE THREAD

**Issue by mtheiss** [pygments/pygments#1734]
In 2.8.0 Latex is unable to render a simple document (pdflatex -halt-on-error -shell-escape demo.tex) like
```latex
\documentclass{article}

\usepackage{minted}

\begin{document}
    X \mintinline{http}|abc| X
\end{document}
```
with the message:
```
! Missing number, treated as zero.
<to be read again> 
                   -
l.2 \PYG{err}{abc}
```
Might be related to #1710

**Comment by birkenfeld** [comment]
please take a look @jfbu

**Comment by jfbu** [comment]
@birkenfeld 

This is a bug of minted which seems to assign catcode 11 to the `-` character in this context. It is not a bug of Pygments. I will investigate more later the minted aspect of this

(clearly this is the same as #1731 previous report)

but I can't now and only did enough to get to the conclusion I reported.

We could fix it via ``\setlength{\fboxsep}{\string -\fboxrule}`` (mind the space after `\string`)  or TeX syntax `\foxbsep=\string -\fboxrule` (space after `\string`, else du to minted bug, TeX would be a control sequence with name `\string-` where `-` is part of the name).

With the above I get successful build of provided test document. But this should be a temporary hotfix as this is a `minted` bug and should be reported to `minted` maintainer. Should I make PR with it?

**Comment by birkenfeld** [comment]
Thanks so much for the investigation!
