### ISSUE TITLE
Groovy lexer doesn't handle quoted function names

### ISSUE THREAD

**Issue by alisonatwork** [pygments/pygments#1753]
Noticed when opening a PR on GitHub with Spock framework tests. Spock uses Groovy's support for quoted function names to describe the test in readable language. Unfortunately this is misinterpreted and we lose syntax highlighting for part of the test.

Here is a shorter example which exhibits the problem. The following two snippets should be highlighted the same way:

```groovy
def thisFunctionLooksLikeJava() {
    println "hello"
}

thisFunctionLooksLikeJava()
```

```groovy
def "this is a (long) function"() {
    println "hello"
}

"this is a (long) function"()
```

**Comment by birkenfeld** [comment]
Interesting. You can see here that GitHub is also not happy with the syntax :) Do you want to work on a PR?

**Comment by alisonatwork** [comment]
I don't have a VM with Python on it at the moment to test, but if/when I find the time I'm happy to spin one up and give it a go.

I think the relevant section of the Groovy spec is here: http://groovy-lang.org/syntax.html#_quoted_identifiers I imagine for the vast majority of cases just handling single and double quote would be enough.

**Comment by alisonatwork** [comment]
@birkenfeld I didn't manage to get a Python environment set up to test locally, but with the help of the CI and adding a new test I was able to confirm that the change works as expected without breaking the existing tests. I also made another small fix for Groovy while I was there. See #1765
