### ISSUE TITLE
LatexFormatter: allow digits in `commandprefix`

### ISSUE THREAD

**Issue by muzimuzhi** [pygments/pygments#1770]
Some (third-party) pygments styles, like [base16-pygments](https://github.com/mohd-akram/base16-pygments), use digits in style names (in TeX's convention, csname), and LaTeX package `minted` will use style name as part of `commandprefix`, which result in defining LaTeX control sequences with digits in their names, like `\PYGstyle1@xxx`, which is not supported by TeX's default category code (aka. catcode) settings.

Reports to this problem were added from time to time, see a recent one in https://github.com/gpoore/minted/issues/299 and a 2-year-old one in https://tex.stackexchange.com/q/482623.

In (La)TeX, `\def\cmd0{...}` fails at defining a command `\cmd0`, but a command `\cmd` delimited by `0`. One has to use `\expandafter\def\csname cmd0\endcsname{...}`, or equivalent LaTeX2e internal macro`\@namedef` instead. A proposal following this approach can be seen in https://github.com/muzimuzhi/pygments/commit/c068d4770ab3333101474397ceca1a362910c143. Note this will make the latex style less readable.

@jfbu Please take a look.

------
More words

`minted` has supported hyphen and underscore characters in style names, but the similar workaround (locally changing catcode) won't work for digits because the pygments LaTeX style uses `\def\cmd#1{..}`, in which the `1` must be in its normal catcode.

A more ambitious plan would be to first un-tokenize the `commandprefix`, then use it as part of csname. For example `\@namedef{\detokenize{$(cp)@xxx}}{...}` in place of `\def\$(cp)@xxx{...}`. This will support any active characters (with catcode 13) in csname, without unwanted expansion nor local change of catcode, so will avoid minted compatibility issues like #1734 (in the future if `minted` removes catcode changes).

**Comment by jfbu** [comment]
As I commented with more words (and, perhaps, additional confusion) at https://github.com/muzimuzhi/pygments/commit/c068d4770ab3333101474397ceca1a362910c143#commitcomment-61772415 my opinion on this is:
- digits in LaTeX macro names could indeed be allowed in the style file via the added `\@namedef/\@nameuse` and `\expandafter\let\csname...` complications as have been done in the referred-to commit,
- but for the actual LaTeX mark-up ending up in Verbatim, only reasonable way (if not going into more and more complicated extra stuff) is to keep a neutral prefix such as `\PYG` (as is actually done by https://github.com/gpoore/minted/), thus one would need to tell user of Pygments "*yes you can use digits in command prefix but do this only for `pygmentize -S` and then add some LaTeX extra definition to remap a neutral prefix such as `\PYG` as used in the output mark-up to the more complicated prefix of the style file*" (notice that this is the https://github.com/gpoore/minted/  way of doing these things, and fancy prefixes can be passed over to `\pygmentize -S` but "fancy" currently only means "with `_` or `-`", and not only is the  https://github.com/gpoore/minted/  way of doing this currently not functional with digits, it also required Pygments to make a specific patch to its LaTeX formatter #1735 already.
- the sole motivation for this whole thing is from https://github.com/gpoore/minted/ current design.
 
The way-out is to change the minted design, not Pygments.

**Comment by jfbu** [comment]
I have made a PR at minted to solve there the issue of Pygments style names with digits (or other characters not suitable to be used inside LaTeX macro names): https://github.com/gpoore/minted/pull/317

**Comment by muzimuzhi** [comment]
This has been handled on `minted` side. Since `minted` [v2.6](https://github.com/gpoore/minted/releases/tag/v2.6), released on 2021-12-24
> Pygments style names may now contain arbitrary non-whitespace characters.

Also as [@jfbu pointed out](https://github.com/muzimuzhi/pygments/commit/c068d4770ab3333101474397ceca1a362910c143#commitcomment-61754772) the approach proposed in current PR is neither complete nor elegant. I'm closing this PR.
