### ISSUE TITLE
support new Python "soft keywords": match, case and _

### ISSUE THREAD

**Issue by taleinat** [pygments/pygments#1797]
Python 3.10 introduces pattern-matching blocks, in which the `match`, `case` and `_` "soft keywords" are considered keywords only in specific parts of the syntax. See [the docs](https://docs.python.org/3.10/reference/compound_stmts.html#the-match-statement) for more details.

However, the list of Python keywords in `lexers/python.py` doesn't include these, nor does the Python lexer appear to have any other way of supporting these keywords.

**Comment by nedbat** [comment]
@taleinat doesn't need to be told, but others might: here is how IDLE chose to support the soft keywords: https://github.com/python/cpython/pull/25851/

For coverage.py's HTML report, I used the ast module to find the start of match/case statements to help.
