### ISSUE TITLE
SQL not correctly highlighted

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#181]
(Original issue 402 created by None on 2009-03-29T10:36:48+00:00)

cf. http://pygments.org/demo/1583/

Original query:

{{{
select
  c.relname,
  l.mode,
  l.granted as lock_held,
  l.pid, s.usename as user,
  s.datname as database,
  s.current_query
from
  pg_class c,
  pg_locks l,
  pg_stat_activity s
where
  c.oid = l.relation AND s.procpid = l.pid
}}}

Reported by guest

**Comment by Anteru** [comment]
(Original issue was assigned to gbrandl)

**Comment by Anteru** [comment]
(Original comment by thatch on 2009-06-21T22:11:57+00:00)

Hmm. Georg, ideas?

**Comment by Anteru** [comment]
(Original comment by birkenfeld on 2011-01-03T16:52:58.195761+00:00)

Oh well, the SQL lexer needs to be quite a bit more context sensitive.  That's difficult though because of the wide range of slightly incompatible dialects...

**Comment by Anteru** [comment]
(Original comment by roskakori on 2016-03-28T20:40:43.351889+00:00)

If I understand the specific issue correctly, the ticket creator objects to "user" and "database" being rendered as `token,Keyword`. Wouldn't it already be an improvement to render the next token after "as" and "." as `token.Name`?

Of course, this still won't catch code like
```sql
select user, database from some_table
```
or
```sql
select u user, d database from some_table
```

**Comment by kurtmckee** [comment]
I recommend closing this ticket.

* The ticket is 11 years old.
* Tracking non-reserved keywords across SQL dialects and parsing the grammar to determine if it should be a keyword or a schema object name or an alias may be very costly.

Therefore I recommend closing this ticket.
