### ISSUE TITLE
Feature request: expose custom style via environment variable or dot-file

### ISSUE THREAD

**Issue by gbpoole** [pygments/pygments#1810]
Hi there,

I've been enjoying using pygments to format my terminal pager (cat, more, etc.) outputs.  I use the Molokai colour scheme and have made a custom style class for that.  Works great.

Problem is: every time I make a new Python environment, I have to copy my custom colour scheme to the styles subpackage.  This is a real pain!  Would you consider adding the functionality to expose a custom style class in a fixed location: either a defined dot-file or a file pointed to by an environment variable?

**Comment by gbpoole** [comment]
I could just offer my molokai.py file if you'd like.

**Comment by Anteru** [comment]
I'm not opposed to the idea. It's a valid use case and assuming it can be added with a not-too-intrusive patch (that can be somehow tested!) I'd be happy to review it. OTOH: Adding a new style is a no-brainer as well, if you're set by having molokai in the core Pygments package, we can do that as well and it's probably more beneficial to the community at large.

**Comment by gbpoole** [comment]
Ok, after some more digging around, I understand now that the way to manage this sort of thing is via the Pygments pluging functionality.  I've now created a Pygments Molokai style plugin which can be found [here](https://pypi.org/project/pygments-molokai/
).

It can be installed via:

`pip install pygments-molokai`
