### ISSUE TITLE
legal nitpick: Test example file not licenced for use in nuclear facilities

### ISSUE THREAD

**Issue by encukou** [pygments/pygments#1831]
(Disclaimer/full disclosure: I am not a lawyer. I do work at Red Hat.)

A Java test example file has this in its licence blob:

https://github.com/pygments/pygments/blob/3e9fe3a99ae3f4250e1d3788f5f3b4cc0c21e6ac/tests/examplefiles/java/Intro.java#L31-L33

What does this mean? Imagine corporate lawyers raising eyebrows.
Technically, this might break the [Open Source definition](https://opensource.org/osd) (No Discrimination Against Fields of Endeavor), making Pygments hard to test in the more careful distros.

Could this this file be, ehm, nuked?
It would be nice to replace it with a more clearly licensed file; is there anything such a replacement should feature?

**Comment by Anteru** [comment]
Yes, that looks ... not right. You don't have a suitable replacement file by any chance you'd be willing to contribute?

**Comment by Anteru** [comment]
I just looked at the file and there's not much interesting coverage in there. Nuked!

**Comment by encukou** [comment]
Thank you!
