### ISSUE TITLE
Multiline shell (with backslash) is highlighted incorrectly

### ISSUE THREAD

**Issue by jessetan** [pygments/pygments#1832]
The following piece of shell is incorrectly syntax highlighted. Only the first line is correctly highlighted, the rest is gray:
```
$ echo "foo \
    bar"
```
This is happening since version 2.8.0 and also happens in the online demo page on pygments.org: https://pygments.org/demo/?lexer=console&code=%24%20echo%20%22foo%20%5C%0A%20%20%20%20bar%22
The last correct version was 2.7.4

Example effect for Sphinx documentation with Pygments version 2.9.0
![Screenshot 2021-06-04 at 16 57 38](https://user-images.githubusercontent.com/3284111/120822270-8a1dcc00-c556-11eb-880d-6e67c31ec7d9.png)

Example effect for Sphinx documentation with Pygments version 2.7.4
![Screenshot 2021-06-04 at 16 57 01](https://user-images.githubusercontent.com/3284111/120822200-75413880-c556-11eb-83eb-f0ad6bb7507c.png)

**Comment by jessetan** [comment]
Diffing between 2.7.4 and 2.8.0. lead me to #1672.
The change for this type of input which does not contain the PS2 prompt (`>`) may have been intentional, or the usecase was never considered.

**Comment by birkenfeld** [comment]
Yeah, it's a bit unfortunate.  I can understand why it's bothersome to show the secondary prompt, especially with long lines.

If it's possible without too many problems to reinstate the old behavior for this use case, I'm +1.
