### ISSUE TITLE
Add trivial lexer for output (using Token.Generic.Output for the complete code block)

### ISSUE THREAD

**Issue by doerwalter** [pygments/pygments#1835]
If I have the following Sphinx source:

```rest
	Do the following in your Python shell:

	.. sourcecode:: pycon

		>>> for i in range(3):
		...	print(i)
		...
		0
		1
		2

	You can also run the following code as a script:

	.. sourcecode:: pycon

		for i in range(3):
			print(i)

	This will output:

	.. sourcecode:: text

		0
		1
		2
```

the output in the first code snippet is marked up with `Token.Generic.Output`, but the output of the second code snippet is marked up with `Token.Text` (in fact it isn't marked up at all).

In my current style the result looks like this:

![grafik](https://user-images.githubusercontent.com/1387028/121018079-4fa67000-c79e-11eb-815d-7890613a27e4.png)

i.e. both outputs look different. I could of course use the `console` lexer for the second output and hope that the lexer doesn't find anything that it will interpret as a prompt. The better solution however would be to have a new lexer that simply outputs everything marked up with the token `Token.Generic.Output`.

Code for that might look something like this:

```python
class OutputLexer(lexer.Lexer):
	"""
	Simple lexer that highlights everything as output.
	"""
	name = 'Text output'
	aliases = ['output']
	filenames = ['*.txt']
	mimetypes = ['text/plain']
	priority = 0.005

	def get_tokens_unprocessed(self, text):
		yield 0, token.Generic.Output, text

	def analyse_text(text):
		return OutpuLexer.priority
```

If this is accepted I can work on a pull request implementing `OutputLexer`.

**Comment by birkenfeld** [comment]
Sounds good, it should be very similar to the TextLexer. But don't give it a priority, please. It should only be used when explicitly requested.

**Comment by doerwalter** [comment]
Done: https://github.com/pygments/pygments/pull/1836
