### ISSUE TITLE
Token types for unusual concepts?

### ISSUE THREAD

**Issue by Jean-Abou-Samra** [pygments/pygments#1840]
For background, I would like to write a LilyPond lexer for Pygments. (This would be like #1371, but I am not confident with the PR because it reuses GPL-licensed work, so I'm carefully not looking at it.)

LilyPond (https://lilypond.org) is a music typesetter rather than a programming language. Most of its concepts are completely different from those the builtin tokens provide:

- Pitches,
- Durations,
- Dynamics,
- Context names,
- Grob (graphical object) names,
- Built-in music functions,
- Built-in markup commands,
- etc.

What would be the way to handle those? Should I try abuse the existing tokens, or use new ones and support them in one single style? If (as I suspect) the second option is preferred, should I create a new style or extend the default one?

**Comment by Anteru** [comment]
If you use completely new token names, no style will match. However, if you're planning to add a new style at the same time, I don't see why you can't have unique token types as well. This seems niche enough that it's unlikely someone will want to highlight C++ and LilyPond on the same page using the same style. Ideally of course you'd use some known token types and refine them further so the default style kind of makes sense and your custom style brings out all the nuances in the language.

**Comment by Jean-Abou-Samra** [comment]
Thanks, this answers the question. I'll go the route of defining a new style. There are actually some tools using LilyPond for APIs in other languages, like [Abjad](https://abjad.github.io/index.html), whose documentation mixes LilyPond code with those languages (e.g., https://abjad.github.io/appendices/lilypond-context-concatenation.html). I guess this is rare enough, and looks more like a feature request for Sphinx to allow per-language styles than anything else.
