### ISSUE TITLE
Rust linting bug

### ISSUE THREAD

**Issue by halbGefressen** [pygments/pygments#1843]
The Rust linter appears to highlight variable names incorrectly if they start with the `break` keyword: 
https://pygments.org/demo/?lexer=rust&code=pub%20struct%20TranslationData%20%7B%0A%20%20%20%20pub%20does_main_return%3A%20bool%2C%0A%20%20%20%20pub%20function_name%3A%20String%2C%0A%20%20%20%20pub%20args%3A%20Vec%3CString%3E%2C%0A%20%20%20%20pub%20variables%3A%20HashMap%3CString%2C%20usize%3E%2C%0A%20%20%20%20pub%20variables_valid%3A%20Vec%3CVec%3C(String%2C%20bool)%3E%3E%2C%0A%20%20%20%20pub%20break_stack%3A%20Vec%3CString%3E%2C%0A%20%20%20%20pub%20label_table%3A%20Vec%3CString%3E%2C%0A%20%20%20%20pub%20functions%3A%20HashMap%3Cast%3A%3AIdentifier%2C%20ast%3A%3AFuncArgs%3E%2C%0A%7D

**Comment by birkenfeld** [comment]
Thanks for the report!
