### ISSUE TITLE
Fine-grained error locations in Python tracebacks

### ISSUE THREAD

**Issue by Jean-Abou-Samra** [pygments/pygments#1850]
With the [acceptance](https://mail.python.org/archives/list/python-committers@python.org/thread/3WDJNOW2SPTPCKUGLG2ANBWZZEYTT6F6/) of [PEP 657](https://www.python.org/dev/peps/pep-0657/), "Include fine-grained error locations in tracebacks", a Python traceback will look like this:

```
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    x['a']['b']['c']['d'] = 1
    ^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

The `PythonTracebackLexer` will need some adjustments. Currently, it highlights the carets are operators (thinking it is reading Python code).

**Comment by Jean-Abou-Samra** [comment]
What would be an appropriate token type for the carets? `Token.Punctuation`? `Token.Text`? `Token.Generic.Traceback`? A new type?

**Comment by Anteru** [comment]
`Token.Punctuation` seems sensible. There's no style which would highlight them separately ... you could do `Token.Punctuation.Marker` or something which would get styled as `Token.Punctuation` as a fallback, and if more lexers start doing this, we might eventually styles pick this up (GCC, Clang and Rust use the same mechanism AFAIK.)

**Comment by Jean-Abou-Samra** [comment]
Thanks for the hint. I've opened #1852.
