### ISSUE TITLE
Fortran keywords composed by two words not highlighted

### ISSUE THREAD

**Issue by ecasglez** [pygments/pygments#1865]
There are two statments that are not properly highlighted by the Fortran Lexer:

* `goto` is only highlighted if there is no space between go and to. However, `go to` is also accepted by the Fortran standard, and it should be highlighted by pygments. "Go" and "To" can be used as name for variables, so they should only be highlighted when "go" preceedes "to".

* `do concurrent`. First of all, the word `concurrent` is misspelled in fortran.py where it is written with 3 R (`CONCURRRENT`). Fixing that typo it highlights well the `do concurrent` statement. However, "concurrent" itself can be used as a variable name which shouldn't be highlighed. I mean CONCURRENT should only by highlited when it follows a DO, like `DO CONCURRENT`.

I have tried to fix both trying regexp in file fortran.py but I did not succeed. Following a comment by Anteru in pull request #1861 I tried to make it work with a variable number of spaces between the two works. For example I tried adding `'go[ ]*to'` in fortran.py but it didn't work.

**Comment by amitkummer** [comment]
Thank you for the detailed description!

If you still have the time/energy/will for fixing this, I think something like this rule should do the trick for a `go to` with a space:

```python
(r'(go)(\s*)(to)', bygroups(Keyword, Whitespace, Keyword))
```

**Comment by blu-base** [comment]
@Anteru i guess, this issue is closable =)

**Comment by Anteru** [comment]
Yes. good catch! I do go over all PRs before a release and look for related issues that haven't been referenced so I would have hopefully found that before the next release :)
