### ISSUE TITLE
Terraform lexer does not support HCL heredoc syntax

### ISSUE THREAD

**Issue by offbyone** [pygments/pygments#1909]
I am using pygments 2.10.0 to highlight a terraform config containing this:

```hcl
resource "local_file" "tf_ansible_vars_file_new" {
  content  = <<-DOC
    # Ansible vars_file containing variable values from Terraform.
    # Generated by Terraform mgmt configuration.

    iot_credential_provider_endpoint: ${data.aws_iot_endpoint.credentials.endpoint_address}
    iot_credential_role_alias: ${aws_iot_role_alias.cert-dns.alias}
    DOC
  filename = "./vars/tf_ansible_vars_file.yml"
}
```

What I get out of it is the attached image. 
![image](https://user-images.githubusercontent.com/181693/136423245-1167b880-828c-4bf5-ab23-02ea22973a52.png)

**Comment by offbyone** [comment]
Hm. Those heredocs are quite a bit different; Terraform's are a lot like bash's syntax. I'll see if I can find an example.

**Comment by michaelbrewer** [comment]
Looks like this is not completely closed as Terraform support `<<` format as well see: https://www.terraform.io/language/expressions/strings#heredoc-strings
