### ISSUE TITLE
A lexer for org-mode ?

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [pygments/pygments#1913]
Emacs' `org-mode` can use `minted` to export source code in various languages to LaTeX ; this option gives much better results than either `verbatim` output or `listings` (which chokes on non-ASCII...).

However, a glaring exception is that Org's own markup language doesn't export correctly via `minted`(or `listings`, BTW) because `minted` uses `pygments` and the latter doesn't have a lexer for `org`. In consequence, `org` code blocks (which have their uses...) rendering is seriously botched in exported LaTeX...

Somebody seems to have [done the job](https://github.com/or/pygments-orgmode-lexer), but I have been unable to make head or tail of the installation and or instructions for use.

Could this lexer be integrated into `pygments` ?

**Comment by kickingvegas** [comment]
Count me in for wanting to see Emacs `Org-mode` file support as well!

**Comment by mcepl** [comment]
Hmm, changelog for https://github.com/pygments/pygments/releases/tag/2.18.0 claims the orgmode lexer is now included, but it doesn't seem to work:

```sh
tumbleweed-pkg:orgmode (master *) $ pygmentize TODO.org 
Error: no lexer for filename 'TODO.org' found
tumbleweed-pkg:orgmode (master *) $ pygmentize -L|grep -i org
Pygments version 2.15.1, (c) 2006-2023 by Georg Brandl, Matthäus Chajdas and contributors.
* xorg.conf:
    Xorg (filenames xorg.conf)
tumbleweed-pkg:orgmode (master *) $ 
```

**Comment by jeanas** [comment]
Well, "Pygments version 2.15.1".

**Comment by birkenfeld** [comment]
Looking at that credits line, @jeanas feel free to add yourself there!

**Comment by mcepl** [comment]
Yes, I am sorry, there was Pygments package left behind in `~/.local/lib/`.
