### ISSUE TITLE
Switch docs theme

### ISSUE THREAD

**Issue by amitkummer** [pygments/pygments#1920]
When writing some documentation I noticed some stuff about the theme:

1. Some pages (for example [this one](https://pygments.org/docs/lexerdevelopment/) and [this one](https://pygments.org/docs/cmdline/)) have a big space between paragraphs at the top of the page. 
2. IMO stylistically it can be improved. Things like a new font, different style for code blocks (also for inline code), and different margins can make the documentation itself more readable and also more attractive (I think it looks a bit old currently).

Point one seems to happen because of some css `float` directives. Refactoring those floats to flex boxes can help, but it can also be solved by switching to a different theme.

Point two is entirely subjective, but the easiest and most obvious solution is changing themes.

If you like this idea, please choose a theme and optionally style customizations you would like to be done to it, and I will happily make a PR with the switch.

Personally I think choosing the [read the docs](https://sphinx-themes.org/sample-sites/sphinx-rtd-theme/#) theme and doing some small style customizations like in the [Ansible docs](https://docs.ansible.com/ansible/latest/index.html) can turn out nicely, as everyone knows and loves this theme.

**Comment by Anteru** [comment]
I'm not too keen on completely switching the style, but I'm quite open to spot fixes if there are particularly concerning pages. There have been some changes recently which fixed the large gaps on the pages. Stylistically, I'd be curious to see a page which is particularly troubling to read or a suggestion which font would be better. `PT Sans` is quite readable, is there some page where you think it's causing issues?

**Comment by amitkummer** [comment]
Thanks for closing this and sorry for being slow to respond. I absolutely understand the decision to keep the current theme.

I think I will try to experiment with some minor style changes. If I find something interesting I will bring it up.

**Comment by Anteru** [comment]
No worries. If you find something I'll reopen, I just didn't see any further issues with the website and figured I can close for now.
