### ISSUE TITLE
Is any benchmark/accurate for guess_lexer_for_filename available?

### ISSUE THREAD

**Issue by Zackhardtoname** [pygments/pygments#1950]
I have been wondering about the performance difference between Pygments and alternatives like [go-enry](https://github.com/go-enry/go-enry).

I am mainly concerned about the accuracy the [guess_lexer_for_filename](https://github.com/pygments/pygments/blob/3ef93d89ebb04373d2887b6be45b482c0887d9d2/pygments/lexers/__init__.py#L240) function in Pygments in identifying the correct programming languages by filename and file content. Is there any benchmark or general experiences from usage available? 

I also notice that there's not a build-in way to customize the matching rules so advanced users would need to write some custom code, which is fine.

**Comment by Zackhardtoname** [comment]
[guesslang](https://guesslang.readthedocs.io/en/latest/contents.html#how-does-guesslang-guess) has a nice benchmark and open sourced [their benchmark tool](https://github.com/yoeo/guesslangtools).

**Comment by Anteru** [comment]
No, there is no benchmark. If you go by filename it should be pretty accurate as there aren't that many languages colliding on the same ending, but "general" guessing based on the contents is not benchmarked. I think this is something we need to improve eventually, but it's a monumental undertaking and nobody volunteered yet to tackle this.

**Comment by Zackhardtoname** [comment]
Actually I did find [a nice human-labeled dataset](https://github.com/smola/language-dataset) giving us a benchmark comparing it with other solutions like Linguist and go-enry.
The end result is that according to the human labels, **Pygments is right 76.18%**, Linguist is right 91.50% of the time. 2% of linguist’s error could be corrected by pygments

Sample code I used for getting the percentages:
```python
import os

import yaml
from collections import Counter, defaultdict

with open("language-dataset/data/dataset.yml", "r") as stream:
    try:
        res = yaml.safe_load(stream)
    except yaml.YAMLError as exc:
        print(exc)

num_total = 0
inconsistent = 0
allkey = {key for dictio in res["files"].values() for key in dictio["annotations"]}
all_linguist_keys = {key for key in allkey if key.startswith("linguist")}
all_diff_cases = defaultdict(list)
all_diff_lang = Counter()

for name, repo in res["files"].items():
    annotations = repo["annotations"]
    if "linguist" in annotations and "pygments-filename" in annotations:
        ground_truth = annotations.get("human-smola", annotations.get("human-ajnavarro"))
        if ground_truth and ground_truth != "Unknown":
            num_total += 1
            ground_truth = ground_truth.lower()
            to_eval = annotations["pygments-filename"].lower()
            if ground_truth != to_eval:
                if "xml" not in ground_truth and ("c" in ground_truth or (ground_truth not in to_eval and to_eval not in ground_truth)):
                    inconsistent += 1
                    all_diff_cases[os.path.basename(ground_truth)].append(annotations)
                    all_diff_lang[ground_truth] += 1
    # if "linguist" not in annotations and all_linguist_keys.intersection(annotations.keys()):
    #     print(annotations.keys())
    #     break
print(1 - inconsistent / num_total)
print(all_diff_lang.most_common())
```
