### ISSUE TITLE
add alias "cs" for csharp

### ISSUE THREAD

**Issue by drewburlingame** [pygments/pygments#1962]
https://github.com/pygments/pygments/blob/master/pygments/lexers/dotnet.py#L50

Github supports `cs`, `c#` and `csharp` as seen in the examples below.  Other tooling also supports `cs`.  One such tool is [MarkdownSnippets](https://github.com/SimonCropp/MarkdownSnippets) which 
can be used to copy snippets from source code into documents. The language used defaults from the file extension, which is reasonable for many languages.

Can a `cs` alias be added to the dotnet csharp lexer?  It looks as simple as adding the alias to the line I linked to above.  I didn't find tests for the aliases.  Should I create a PR?

``` cs 
var s = "lala"
```

``` c#
var s = "lala"
```

``` csharp
var s = "lala"
```

**Comment by drewburlingame** [comment]
@birkenfeld why was this closed?  Does it not make sense for pygments to support `cs` as an alias?

**Comment by birkenfeld** [comment]
Sorry, I didn't add a comment. It was closed by the commit that added the alias :)

**Comment by drewburlingame** [comment]
Ah, I see now.  That's great.  Thank you.  I'm not familiar with the release cycle for pygments.  When do you think this would be available for use?

**Comment by Anteru** [comment]
Certainly this year, hopefully this month. I'm trying to get the next release prepared but no guarantees as I'm quite busy.

**Comment by drewburlingame** [comment]
Thanks @Anteru and thanks for all the work you do.
