### ISSUE TITLE
JsonLexer module moved?

### ISSUE THREAD

**Issue by BSVogler** [pygments/pygments#1964]
The docs refer to `pygments.lexers.data.JsonLexer` for the JSON Lexer: https://pygments.org/docs/lexers/#lexers-for-data-file-format

However, with my local installation (2.10.0), it seems to have been moved to `pygments.lexers.JsonLexer`. Is the documentation outdated or is something wrong with my installation?

**Comment by Anteru** [comment]
It's here: https://github.com/pygments/pygments/blob/master/pygments/lexers/data.py

It may be _also_ available as `pygments.lexers.JsonLexer` but the location in the documentation is correct.
