### ISSUE TITLE
Lexing from middle of code

### ISSUE THREAD

**Issue by matkuki** [pygments/pygments#1975]
Hi,

I'm trying to get `Pygments` working with an IDE and there is a problem with some lexers that handle multiline tokens (Comment.Multiline, String.Doc, ...) in a way that does not change stack state, like CLexer and it's derivatives.
When parsing code like this, there is no problem:
```c
/*
 *  These are my multiline
 *  comments at the 
 *  start of the file
 */

int main() {
    // some code
}
```
But when lexing code that does **not** start at the beginning, like so:
```c
 *  comments at the 
 *  start of the file
 */

int main() {
    // some code
}
```
there is no way to set a starting state for the lexer, as CLexer does not handle multiline comments by changing the stack state, it uses a single `re` expression to parse it.

Is there a way to parse the second example, so that the comment at the top is highlighted correctly?

P.S.:
Found this issue that seems to be relevant: https://github.com/pygments/pygments/issues/816

Thanks
Matic

**Comment by matkuki** [comment]
Can anyone say why multiline tokens are in some lexers done with a single regular expression like so:
```python
tokens = {
    'root': [
        ...
        (r'/(\\\n)?[*](.|\n)*?[*](\\\n)?/', Comment.Multiline), # From DLexer in 'lexers/d.py'
    ],
```
and in other lexers with a state change:
```python
    'root': [
        ... ,
        (r'/\*', Comment.Multiline, 'nestedcomment'), # From CrocLexer in 'lexers/d.py'
        ... ,
    ],
    ...
    'nestedcomment': [
        (r'[^*/]+', Comment.Multiline),
        (r'/\*', Comment.Multiline, '#push'),
        (r'\*/', Comment.Multiline, '#pop'),
        (r'[*/]', Comment.Multiline),
    ],
```
Performance? Less code?

Thanks

**Comment by birkenfeld** [comment]
Basically it depends on the implementor, new states are often only used if regexes cannot do the trick.

Since Pygments is not designed for your usecase, there hasn't been a rule in place that each line must be matched with a new rule.

**Comment by matkuki** [comment]
Thanks for the explanation @birkenfeld
