### ISSUE TITLE
Bad C syntax highligh

### ISSUE THREAD

**Issue by marxin** [pygments/pygments#1995]
Please consider:

```c
void __builtin_aarch64_set_fpcr (unsigned int);
void __builtin_aarch64_set_fpsr (unsigned int);
void __builtin_aarch64_set_fpcr64 (unsigned long long);
unsigned __builtin_aarch64_get_fpsr64 ();
void __builtin_aarch64_set_fpsr64 (unsigned long long);

unsigned int __builtin_aarch64_get_fpsr ();
long long __builtin_aarch64_get_fpcr64 ();
unsigned int __builtin_aarch64_get_fpcr ();
```

Demo: https://pygments.org/demo/?lexer=c&code=void%20__builtin_aarch64_set_fpcr%20(unsigned%20int)%3B%0Avoid%20__builtin_aarch64_set_fpsr%20(unsigned%20int)%3B%0Avoid%20__builtin_aarch64_set_fpcr64%20(unsigned%20long%20long)%3B%0Aunsigned%20__builtin_aarch64_get_fpsr64%20()%3B%0Avoid%20__builtin_aarch64_set_fpsr64%20(unsigned%20long%20long)%3B%0A%0Aunsigned%20int%20__builtin_aarch64_get_fpsr%20()%3B%0Along%20long%20__builtin_aarch64_get_fpcr64%20()%3B%0Aunsigned%20int%20__builtin_aarch64_get_fpcr%20()%3B

as seen the last 3 function names are not highlighted. That's not correct:
![Screenshot from 2021-12-22 11-50-18](https://user-images.githubusercontent.com/2658545/147081368-62643cbb-d601-4939-9fef-d9be9e3e93d0.png)

Thanks for help.

**Comment by amitkummer** [comment]
Thank you for the feedback! This is also reported in #1729 (last code snippet in main post). 

I think this should be a relatively easy fix. I will try to find time for it.

**Comment by marxin** [comment]
> I think this should be a relatively easy fix. I will try to find time for it.

Good, thank you for it!
