### ISSUE TITLE
JSON Lexer produces Error tokens when whitespace surrounds ":" char

### ISSUE THREAD

**Issue by jamesls** [pygments/pygments#2010]
The JSON lexer will produce Error tokens if whitespace surrounds the `:` char.  Repro:

```python
from pygments.lexers.data import JsonLexer
from pprint import pprint


lexer = JsonLexer()
pprint(list(lexer.get_tokens('{"foo" : "bar"}')))
```

Current behavior:

```
[(Token.Punctuation, '{'),
 (Token.Name.Tag, '"foo"'),
 (Token.Error, ' '),                 # <---- causes an exception to be raised
 (Token.Punctuation, ':'),
 (Token.Text.Whitespace, ' '),
 (Token.Literal.String.Double, '"bar"'),
 (Token.Punctuation, '}'),
 (Token.Text.Whitespace, '\n')]
```

Previous behavior:

```
[(Token.Punctuation, '{'),
 (Token.Name.Tag, '"foo"'),
 (Token.Text, ' '),
 (Token.Punctuation, ':'),
 (Token.Text, ' '),
 (Token.Literal.String.Double, '"bar"'),
 (Token.Punctuation, '}'),
 (Token.Text, '\n')]
```

I believe this was introduced in b4f05832abfefc37f75e341e44e5650c6391aa18.  Now that a whitespace token is being used instead of text, the lexer will hit the fallback cause of producing an Error token:

https://github.com/pygments/pygments/blob/fb3edec4978f44ab097e36b165fa0ee0cbba5f13/pygments/lexers/data.py#L589-L597

I noticed this through Sphinx, where any JSON code block that has whitespace around `:` produces this warning:

```
myfile.rst:Could not lex literal_block as "json". Highlighting skipped.
```

**Comment by Anteru** [comment]
@blu-base Would you mind taking a look at this?

**Comment by Anteru** [comment]
I think 88ed195d6d3623b8bdc9c7590bccb5dfeb3a7cf7 fixes this, but it would be good if someone could double-check.

**Comment by blu-base** [comment]
Just as i was typing my response, you commited already =)

**Comment by blu-base** [comment]
I'm going to check it tomorrow-

> I think [88ed195](https://github.com/pygments/pygments/commit/88ed195d6d3623b8bdc9c7590bccb5dfeb3a7cf7) fixes this, but it would be good if someone could double-check.

I am going to check it tomorrow.

**Comment by Anteru** [comment]
He, sorry, I actually meant to create a PR, but messed up and pushed to `master`, but also realized that this is probably the right fix. If you could take another look that would be much appreciated!

**Comment by Anteru** [comment]
With the latest coverage added in https://github.com/pygments/pygments/commit/a5c32c8a1e9c33b70187718abafb5f2fe96bac31 I feel reasonably confident that this is going to work ... I'll prepare a new release as this is a quite serious regression.

**Comment by Anteru** [comment]
Looks like the check was actually incorrect. I changed it in e0c828ff08f143e0627467706573708d9cad0441 and that's what I'll release later today as 2.11.1. @blu-base If you want to enjoy the end of the year and skip checking feel free to do so, I think it's well tested by now.
