### ISSUE TITLE
[Question] Why `Keyword.Type` does not apply specified 'nobold'?

### ISSUE THREAD

**Issue by ox42e9b** [pygments/pygments#2023]
I'm trying to make my own style for code listings in `lualatex`/`beamer` presentation using `minted` package.
This is what I put in `MyStyle` class into `.styles` field.
```python
Keyword:             'bold #FFFFFF', 
Keyword.Type:        'nobold',
```
The problem is that `'nobold'` doesn't apply to expected patterns like `int`, `double`, etc.
They are highlighted just like Keyword (bold). How can I change the behaviour?

----------------------------------------------------
version is `2.11.1`, trying to highlight `C` code.

**Comment by Anteru** [comment]
The `default` style uses `nobold` and that works fine. From a quick glance at the HTML and LaTeX formatters, they both use similar logic to create bold output. Do you have a repro case we could try out? I.e. a code snippet to run on? Can you reproduce the same issue with the `default` style?

**Comment by ox42e9b** [comment]
Hello. I've just tried using default theme and it seems it also behaves wrong.
Here is a screenshot of what I get *(background is black in my presentation)*.
![wrong-highlight](https://user-images.githubusercontent.com/45260168/148379495-f72a875c-ec1f-4473-8eb3-e2f28ae44bae.png)

**Comment by ox42e9b** [comment]
I've tried to use `pygmentize` from the CLI to generate `HTML` output on the same code snippet - it works, `int`, `char` are not bold now. If you wonder if they are bold on the above screenshot - yes, because if I remove `bold` from `Keyword` they become normal.

**Comment by ox42e9b** [comment]
I applied changes from [pull request](https://github.com/pygments/pygments/pull/1391)
into latex lexer and now it works as expected.
Here is the screenshot:
![highlight-good](https://user-images.githubusercontent.com/45260168/148409251-a7beac01-c69d-4bbb-8c08-d277bd603372.png)

-------------------
So I would recommend to accept this pull request

**Comment by jfbu** [comment]
I encountered also the "`nobold` is ignored in LaTeX" effect at #1989.
