### ISSUE TITLE
[Question] How does analyze_text() work?

### ISSUE THREAD

**Issue by dinhanhx** [pygments/pygments#2029]
## The context
https://github.com/pygments/pygments/blob/cd3ad20dfc8a6cb43e2c0b22b14446dcc0a554d7/pygments/lexers/__init__.py#L310-L316

I was curious for how `guess_lexer()` work. I understand it just try all possible lexers and give probability for each lexer. Then it returns the most feasible one. 

**BUT** 
take an example of `analyze_text()` for Python 
https://github.com/pygments/pygments/blob/cd3ad20dfc8a6cb43e2c0b22b14446dcc0a554d7/pygments/lexers/python.py#L396-L398

Here it returns the output of `shebang_matches()` which return `True` or `False` 
https://github.com/pygments/pygments/blob/cd3ad20dfc8a6cb43e2c0b22b14446dcc0a554d7/pygments/util.py#L161-L165

## The question
If `analyze_text()` only return True and False (which are 1 and 0). How can it return a value that is between the range as said [in the doc](https://pygments.org/docs/api/#pygments.lexer.Lexer.analyse_text)?

**Comment by Leistungsabfall** [comment]
Take a look at the Markdown lexer for example:

https://github.com/pygments/pygments/blob/master/pygments/lexers/markup.py#L262-L271

    def analyse_text(text):
        if text[:2] == '..' and text[2:3] != '.':
            return 0.3
        p1 = text.find("\n")
        p2 = text.find("\n", p1 + 1)
        if (p2 > -1 and              # has two lines
                p1 * 2 + 1 == p2 and     # they are the same length
                text[p1+1] in '-=' and   # the next line both starts and ends with
                text[p1+1] == text[p2-1]):  # ...a sufficiently high header
            return 0.5

Returning a float value is absolutely fine.

**Comment by dinhanhx** [comment]
So that mean different lexers will have different way to analyze text (obviously) but with different probability. I think I guess it.

**Comment by dinhanhx** [comment]
But how people determine those values? Like the one in markdown? Those are pretty magic to me

**Comment by birkenfeld** [comment]
> If analyze_text() only return True and False (which are 1 and 0). How can it return a value that is between the range as said in the doc?

This uses the fact that True and False are still integers in Python, so they can be compared to floats.

> But how people determine those values? Like the one in markdown? Those are pretty magic to me

It's not even magic, it's pretty arbitrary unfortunately. They have mostly been optimized so that at least guessing with a known filename is relatively reliable.

**Comment by dinhanhx** [comment]
Thank for answering @birkenfeld and @Leistungsabfall
