### ISSUE TITLE
Highlight ... (Ellipsis) in python lexer

### ISSUE THREAD

**Issue by sblondon** [pygments/pygments#2032]
The builtin constant `Ellipsis` is highlighted as [`Token.Name.Builtin.Pseudo`](https://github.com/pygments/pygments/blob/master/pygments/lexers/python.py#L239).
However, the `...` [equivalent](https://docs.python.org/3/library/constants.html#Ellipsis) is considered as 3 `Token.Operator` (like `os.open()`):

```python
>>> from pygments.lexers import get_lexer_by_name
>>> Lexer = get_lexer_by_name('python3')
>>> tokens = Lexer.get_tokens("os.open")
>>> list(tokens)
[(Token.Name, 'os'), (Token.Operator, '.'), (Token.Name, 'open'), (Token.Text, '\n')]
>>> tokens = Lexer.get_tokens("...")
>>> list(tokens)
[(Token.Operator, '.'), (Token.Operator, '.'), (Token.Operator, '.'), (Token.Text, '\n')]
```

I think `Token.Literal` would be a better choice. I did not choose `Token.Name.Builtin` because it's not listed as a builtin in the builtins python (https://docs.python.org/3/library/constants.html).

With previous example, it would become:
```python
>>> tokens = Lexer.get_tokens("...")
>>> list(tokens)
[(Token.Literal, '...'), (Token.Text, '\n')]
```

What do you think about:
 - the idea?
 - the `Token` class?

I can do a PR if you're interested.

**Comment by Anteru** [comment]
Is there an argument to make it a `Token.Literal` beyond "correctness"? In an example like this:

```python
x = y[Ellipsis, 0]
x = y[..., 0]
```

We currently highlight `.` and `,` in two separate colors in most styles. I'm not convinced the suggested change is making things significantly better, but then again this is rarely used to start with so I'm ok merging a PR which turns `...` into `Token.Literal` if it provides value add.

**Comment by sblondon** [comment]
To be honest, I'm less convinced by what I say in January.

If I remember well, I was surprised the dot character has the same color in `instance.method()` and `...`. However, I don't think there is value added by such change because the dots are never near each others.

I think this issue can be closed.
