### ISSUE TITLE
Syntax highlighting issue in SuperCollider language with nested comments /* /* */ */

### ISSUE THREAD

**Issue by Xon77** [pygments/pygments#2033]
Nested comments with /* */ does work in SuperCollider language, but not with Github pages with SuperCollider language.

I did a small example to show it: 
[https://github.com/Xon77/Live4Life/blob/Nov2021/4Live4Life_Project/Nested_Comments_Formatting.scd](url)

This is the first time I publish a code on GitHub, and only have some experience in SuperCollider.
So, I an unable for now to send a pull request for this issue. Just to report.
If someone knows how to do it, thanks!

Many thanks,

Christophe

**Comment by birkenfeld** [comment]
Sorry, but GitHub is not using Pygments (anymore).
