### ISSUE TITLE
C++14 quote-separation of numeric literals not working

### ISSUE THREAD

**Issue by Craie** [pygments/pygments#2034]
In C++14 you can separate digit groups in numeric literals with single quotes:

    42'012'593L

This is showing up as an error box.  Also, shouldn't the L here show up highlighted differently?  Not sure about that...

I'm using pygmentize 2.3.1 under minted for highlighting in a LaTeX document on my Linux box.

Please let me know if there are other details I'm leaving out.

**Comment by birkenfeld** [comment]
Thanks for the report, this is already fixed in newer versions. (Tip: You can check out the behavior of the most recent version on https://pygments.org/demo/).
