### ISSUE TITLE
Exponential slowdown parsing Genshi templates with unfinished tags in comments

### ISSUE THREAD

**Issue by chipx86** [pygments/pygments#2068]
As of Pygments 2.11.0, when parsing an XML file using the Genshi lexer, comments that include an unclosed/unfinished tag can result in substantial slowdown.

Take the following sample XML document:

```xml
<?xml version="1.0"?>

<project>
  <!-- <move -->

  <target>
    <x />
    <x />
    <x />
    <x />
    <x />
    <x />
    <x />
    <x />
    <x />
    <x />
    <x />
    <x />
    <x />
    <x />
    <x />
    <x />
    <x />
    <x />
  </target>
</project>
```

Running this with `time pygmentize -l genshi test.xml` takes about 3 seconds locally.

Add one more `<x />` to the list, and that becomes 6 seconds. One more, 12 seconds. Then 24. 48. And so on.

This was first encountered in a real-world Ant buildfile. The above XML file is the simplest repro case I could devise.

If you change the comment to include an open or terminated tag (`<!-- <move> -->` or `<!-- <move/> -->`), the problem goes away.

I've bisected the Pygments code, and can verify that this regressed with commit 337dddef92b69d3a1e88fa450bef55149d24c1d9.

I've also verified that this is still an issue as of the latest commit on `master` (be3e35557cccf8c6477602f6341ba1b7ca468793).

**Comment by birkenfeld** [comment]
@Anteru you made the referenced commit - although I can't immediately see the reason for the backtracking...

**Comment by Jean-Abou-Samra** [comment]
#2069 fixes this. As far as I can see, the comment is still not recognized, but that seems a separate problem with the Genshi lexer. At least, it doesn't take ages to terminate.
