### ISSUE TITLE
case value not highlighting in C++

### ISSUE THREAD

**Issue by Craie** [pygments/pygments#2076]
When listing multiple case values that aren't literals but constants on a single line in C++ (perhaps others?), the value is not highlighted as it is when listing each case and value on a separate line.

An MWE:

```
    switch ( CE )
    {
        case value:
        {
            // code for this value
        } break;
        case value: case value:
        {
            // code for these values
        } break;
        default:
        {
            // code for any other values
        } break;
    }
```

Note:  I'm using pygmentize 2.11.2 under minted 2.5 and tcolorbox 4.22 in LaTeX.  But the situation is the same from the command-line.

**Comment by amitkummer** [comment]
Thank you for the report! This is probably my fault. I introduced some changes to how labels are handled in #2022.

I am going to further investigate this, and also see if I can add some comments explaining the current `label` rule I introduced, as it's a little cryptic.
