### ISSUE TITLE
Comments in JSON cannot be highlighted correctly

### ISSUE THREAD

**Issue by TripleCamera** [pygments/pygments#2083]
# Description
Comments in JSON cannot be highlighted correctly. However, it works fine on the Demo on the official website.  

# Steps to Reproduce
1. Install pygments via pip: `pip install pygments`
2. Write a program according to the [Docs](https://pygments.org/docs/quickstart/):
```python
from pygments import *
from pygments.lexers import *
from pygments.formatters import *

code = '''
{
  // This is a comment.
  // 这是一条注释。
  "key": "value"
}
'''
print(highlight(code, JsonLexer(), HtmlFormatter()))
print(highlight(code, JsonLexer(), SvgFormatter()))
```
3. Run the program and get the following output. Notice that the comments are wrapped with `err`.
   ![jsonc_test_output1](https://user-images.githubusercontent.com/66164427/157054404-67357ef9-1c37-440b-8fd5-7d7a92074bae.png)
4. To preview the results more easily, replace `HtmlFormatter` with `SvgFormatter`. Then run again and get the image:
   ![jsonc_test_output2](https://user-images.githubusercontent.com/66164427/157054497-fe10f2b9-8a21-4997-a9bb-dc3e05a83ed0.svg)
5. Additionally, paste the code on the online [Demo](https://pygments.org/demo/). You can see that it works properly:
   ![jsonc_test_demo](https://user-images.githubusercontent.com/66164427/157054560-c6878655-157b-493e-9f91-bbdc87b2fe1b.png)

#  Additional Info
How did I find out this bug? At first, I found out that the [MediaWiki SyntaxHighlight Extension](https://www.mediawiki.org/wiki/Extension:SyntaxHighlight), cannot highlight comments in JSON incorrectly. So I tested its dependency, pygments, and found this bug.

**Comment by birkenfeld** [comment]
We changed the JSON lexer recently (https://github.com/pygments/pygments/pull/2049) to support comments, even if they are not part of the JSON spec and you should *not* be putting comments in your JSON documents.

The website demo always uses the latest master, that's why it works.

**Comment by TripleCamera** [comment]
Thank you for answering. It's my fault, I didn't read through older issues.
