### ISSUE TITLE
JavaScript: weird multi-line template string highligting

### ISSUE THREAD

**Issue by egor-tensin** [pygments/pygments#2092]
I have a file which is highlighted using the currently latest Pygments 2.11.2. It has multi-line template strings in it, which are highlighted incorrectly. See for example https://egort.name/git/wireguard-config/tree/assets/js/main.js?id=20d5e850a8f61b42a84acc212c14c0f13f2a2773#n671. The lines that start with `#` are part of the template literal, but it seems Pygments thinks they're comments?

At some point, all hell breaks loose, and highlighting breaks completely: https://egort.name/git/wireguard-config/tree/assets/js/main.js?id=20d5e850a8f61b42a84acc212c14c0f13f2a2773#n895.

**Comment by Jean-Abou-Samra** [comment]
For all styles I know, output appearing with a red border color means the lexer couldn't recognize the input.

**Comment by Anteru** [comment]
I can't reproduce this using the raw text using the demo on pygments.org. So it looks like this was fixed between 2.11.2 and the current git `master`.
