### ISSUE TITLE
Demo missing styles

### ISSUE THREAD

**Issue by Krinkle** [pygments/pygments#2104]
Confirmed in Firefox 98 and Chromium 99. It appears stylesheets aren't loaded. This makes it difficult to use the demo to verify whether the lexing is working correctly, for example.

https://pygments.org/demo/?lexer=php&style=xcode&formatter=html&code=if+%28+extension_loaded%28+%27excimer%27+%29+%26%26+isset%28+%24_GET%5B%27forceflame%27%5D+%29+%29+%7B%0A%09%24prof+%3D+new+ExcimerProfiler%28%29%3B%0A%09%24prof-%3EsetPeriod%28+0.1+%2F+1000+%29%3B+%2F%2F+Every+0.1ms%0A%09%24prof-%3EsetEventType%28+EXCIMER_REAL+%29%3B%0A%09%24prof-%3Estart%28%29%3B%0A%09register_shutdown_function%28+function+%28%29+use+%28+%24prof+%29+%7B%0A%09%09%24prof-%3Estop%28%29%3B%0A%09%09%24title+%3D+MW_ENTRY_POINT+.+%27.php+%27+.+gmdate%28+%27Y-m-d+H%3Ai%3As%27+%29+.+%27+UTC%27%3B%0A%09%09%24pipe+%3D+popen%28+%22%2Fusr%2Flocal%2Fbin%2Fflamegraph.pl+--title%3D%5C%22%24title%5C%22+%3E+%2Fvar%2Fwww%2Fhtml%2Fw%2Fdocs%2Fflamegraph.svg%22%2C+%27w%27+%29%3B%0A%09%09fwrite%28+%24pipe%2C+%24prof-%3EgetLog%28%29-%3EformatCollapsed%28%29+%29%3B%0A%09%7D+%29%3B%0A%7D%0A

**Comment by Jean-Abou-Samra** [comment]
This is not a styling issue but a lexing issue. Your PHP code doesn't start with `<?php`, which the lexer requires by default as documented at https://pygments.org/docs/lexers/#lexers-for-php-and-related-languages. You need to pass `-Ostartinline` on the command line to enable it, or to add the missing tag. There is no option for that on the demo currently.

**Comment by Krinkle** [comment]
Thank you. I learned something today.
