### ISSUE TITLE
CSS lexer: Add more property names?

### ISSUE THREAD

**Issue by voussoir** [pygments/pygments#2113]
Hi, thanks for this great library.

Today, `pointer-events` caught my attention as Pygments does not highlight it. The list of recognized property names is [here](https://github.com/pygments/pygments/blob/5b24b4ed57704955aab39d4d778cd6e8e57e3185/pygments/lexers/css.py#L32) with 372 entries from [the list at w3.org](https://www.w3.org/Style/CSS/all-properties.en.html).

I checked the CSS package for Sublime Text and found [these 503 entries](https://pastebin.com/raw/GWiQ3NDj). Of course, I'm not suggesting that Sublime is the source of truth here, it's simply a convenient point of reference for me. I'd like to understand the discrepancy between these lists. `pointer-events` is fully cross compatible according to [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events) and presumably many other widely used names are on the list of differences.

`inset` is on w3 as Working Draft but absent from Pygments.

`max-lines` is on w3 as Working Draft but present in Pygments.

Could more of these names be added to Pygments's lexer, or are they excluded for a reason?

Thank you.

**Comment by amitkummer** [comment]
These are definitely needed to be added to the lexer.

It also looks like some properties are located in a different list [here](https://github.com/pygments/pygments/blob/5b24b4ed57704955aab39d4d778cd6e8e57e3185/pygments/lexers/css.py#L128), which could also be a part of this potential refactoring.

**Comment by birkenfeld** [comment]
I agree. Best case would be an automatic way to update the list of properties from a web source, like we do for the builtins of several other languages (see the various `_xxx_builtins.py` modules)
