### ISSUE TITLE
Demo not working on website 

### ISSUE THREAD

**Issue by NBuhinicek** [pygments/pygments#2137]
Hey

Trying to highlight some code on the demo page - https://pygments.org/demo/ - but it doesn't work. The highlight loader is just spinning the whole time.

There is an error in the console - 
<img width="1108" alt="Screenshot 2022-05-12 at 15 08 20" src="https://user-images.githubusercontent.com/42773765/168082365-3ec4aa3c-b213-49e4-9b62-b2840340ff94.png">

**Comment by Jean-Abou-Samra** [comment]
For me, it works in Firefox and Falkon, but I have the same issue in Chrome.

**Comment by Jean-Abou-Samra** [comment]
> Tried with the python cmd line tool but can't figure out how to copy the highlighted code from terminal to keynote sweat_smile

Is your issue that Ctrl-C does not copy anything? In terminals, Ctrl-C means "interrupt". You typically need Shift-Ctrl-C to copy.

**Comment by Jean-Abou-Samra** [comment]
I just checked my Firefox version, and it's also 100.0, so I have no idea what this problem might be linked to :-(

**Comment by Jean-Abou-Samra** [comment]
I suppose you could export it as HTML (`pygmentize -f html -Ofull,style=xcode -l yourlanguage > out.html`) and copy from the resulting HTML.

**Comment by birkenfeld** [comment]
No problems here, neither FF nor Chrome... otherwise I could try to debug it.

**Comment by birkenfeld** [comment]
Could you copy/screenshot the console output *from the top*? I suspect the initial error messages could be more helpful.
