### ISSUE TITLE
Agda lexer interprets ' in module name as error

### ISSUE THREAD

**Issue by fgaz** [pygments/pygments#2163]
This Agda code shouldn't result in any lexing errors, `A'` and `B'` are valid module names:

```agda
module A' where

module B' = A'
```

But pygments interprets the `'` as start of character:

https://pygments.org/demo/?lexer=agda&style=default&formatter=html&code=module+A%27+where%0A%0Amodule+B%27+%3D+A%27

![image](https://user-images.githubusercontent.com/8182846/174083465-ee9f8c62-4178-46fd-8e25-05a8b775be56.png)
![image](https://user-images.githubusercontent.com/8182846/174083544-e3e5c93d-8bd9-4fa5-918f-7fc7559b5bdc.png)

**Comment by birkenfeld** [comment]
Thanks for the report!
