### ISSUE TITLE
Docs - Rebuilding Mapping File

### ISSUE THREAD

**Issue by flywire** [pygments/pygments#2169]
I don't understand why I can't make mapfiles.

Following docs trying to update map file after adding alias to existing lexer:

```
Microsoft Windows [Version 10.0.19043.1766]

C:pygments>make mapfiles
make: *** No rule to make target `mapfiles'.  Stop.

C:pygments>make -v
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i686-pc-msys
```

---

[Adding and testing a new lexer](https://pygments.org/docs/lexerdevelopment/#adding-and-testing-a-new-lexer)

> To prepare your new lexer for inclusion in the Pygments distribution, so that it will be found when passing filenames or lexer aliases from the command line, you have to perform the following steps.
>
> First, change to the current directory containing the Pygments source code. ...

$ `cd pygments`
...

> Finally the lexer can be made publicly known by rebuilding the lexer mapping:

$ `make mapfiles`

**Comment by flywire** [comment]
The docs should be revised to reflect this.

After changing `pygments\lexers\dotnet.py` the following worked:

```
Microsoft Windows [Version 10.0.19043.1766]

C:pygments\lexers>python ./_mapping.py
...
pygments.lexers.dotnet
...
=== 533 lexers processed.
```

**Comment by Jean-Abou-Samra** [comment]
I suspect that you are not in the right directory. When you clone the repository, you get a folder with files like `README.rst`, `CHANGES`, `AUTHORS`, `tox.ini`, etc., and the actual source code is contained in a `pygments/` subfolder of this folder. You need to run `make mapfiles` in the root folder, where the `Makefile` is located, not in the subfolder.

**Comment by Jean-Abou-Samra** [comment]
I've added a note about this in 4bd02e2c3443f972033e9ef7e85b601891020eef. I'm closing this issue, as I'm 99% sure this was the problem; if it wasn't, please reopen.
