### ISSUE TITLE
Styles default_style not working

### ISSUE THREAD

**Issue by flywire** [pygments/pygments#2184]
https://pygments.org/docs/styledevelopment/#creating-own-styles
> _default_style_ is the style inherited by all token types.

See https://github.com/pygments/pygments/pull/2168#issuecomment-1179714177

It's used in three standard styles ([lilypond.py](https://github.com/pygments/pygments/blob/master/pygments/styles/lilypond.py), [lovelace.py](https://github.com/pygments/pygments/blob/master/pygments/styles/lovelace.py) and [vim.py](https://github.com/pygments/pygments/blob/master/pygments/styles/vim.py)) but it does nothing, with `vim` style left to `token`.

**Comment by flywire** [comment]
How about stripping it globally from the styles and docs?

**Comment by birkenfeld** [comment]
Yeah, let's get rid of it.
