### ISSUE TITLE
new lexer request: eventscripts (with patch)

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#219]
(Original issue 440 created by ojii on 2009-09-23T15:03:51+00:00)

I wrote a lexer for Eventscripts Classic (ESC). More information about the language on http://www.eventscripts.com/pages/Main_Page

**Comment by Anteru** [comment]
(Original issue was assigned to tshatch)

**Comment by birkenfeld** [comment]
I'm closing all requests for lexers/formatters without a patch/PR.
