### ISSUE TITLE
Put out new release with recently added styles

### ISSUE THREAD

**Issue by aabmets** [pygments/pygments#2201]
Yeah so umm, you have added a ton of styles and even documented them on your homepage, but 
these are not yet available for public use, because they are not included in the current 
release of Pygments, version 2.12.

Therefore I would suggest to make these styles available through the package repository by 
publishing a new release which includes these styles, so people who wish to use them 
won't have to hack them manually into their projects.

**Comment by birkenfeld** [comment]
The new release is in the works.
