### ISSUE TITLE
Add support for CloudWatch Logs Insights query language

### ISSUE THREAD

**Issue by kurtmckee** [pygments/pygments#2216]
CloudWatch Logs Insights supports [a query language](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CWL_QuerySyntax.html) that doesn't appear to be implemented in Pygments yet.

> ### Note:
>
> I intend to implement this and will track progress here.

## Target support

* commands (like `filter` and `sort`)
* log field references (like `@message`, `json.sub.key.0.msg`, and `` `non-alphanumeric &@ field name` ``)
* pipe separators (like `sort @timestamp | limit 10`)
* aliases (like `@message as msg`)
* comments (starting with `#` and running to end-of-line)
* strings (like `"hello"` and `'world'`)
* numbers (like `10` and `99.9`)
* time periods (like `10m` and `24h`)
* regular expression patterns (using `/regex/` instead of quotation marks)
* regular expression flags (using `/(?i)regex/`)
* operators (including arithmetic, Boolean, and comparison operators)
* functions (like `count()` and `strlen()`)

## Sample queries

```
fields @message
    | parse @message "[*] *" as loggingType, loggingMessage
    | filter loggingType = "ERROR"
    | display loggingMessage
```

```
fields @timestamp, @message, accountId
# | filter accountId not like "7983124201998"
| sort @timestamp desc
| limit 20
```

```
filter @message like /Exception/ 
    | stats count(*) as exceptionCount by bin(1h)
    | sort exceptionCount desc
```

```
parse @message /user=(?<user2>.*?), method:(?<method2>.*?),
    latency := (?<latency2>.*?)/ | stats avg(latency2) by @method2, 
    @user2
```

**Comment by ifaisalalam** [comment]
Was this support added?

**Comment by kurtmckee** [comment]
I didn't add support for this and closed this feature request because I didn't anticipate having time to do so. (Support might have been added, but I'm simply saying I didn't write any code for that.)
