### ISSUE TITLE
New lexer: Tubaina AFC syntax

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#222]
(Original issue 443 created by None on 2009-09-30T20:27:57+00:00)

I want to contribute a lexer to the project to highlight Tubaina's AFC syntax. Tubaina is a simple markup language (like Markdown and others) to write books and booklets. It's an opensource project:

   http://sourceforge.net/projects/tubaina

Here is an example file written in AFC on github:
   http://github.com/caelum/vraptor/blob/master/vraptor-site/src/guide/en/02-intro-ten-minutes.afc

I wrote a simple lexer to this and want to contribute. The code is here: 
       http://paste.pocoo.org/show/142307/

And here is a simple afc test file:
      http://paste.pocoo.org/show/142310/

Reported by sergiolopes

**Comment by Anteru** [comment]
(Original issue was assigned to thatch)

**Comment by Anteru** [comment]
(Original comment by None on 2009-10-14T17:27:17+00:00)

> When the .afc file says xml, does it really mean jsp? Part of the examplefile contains something that's very illegal in xml.  The only remaining issue is that jsp != xml.  After that's fixed, we can merge it.

AFC doesn't have a special tag to JSP or even simple HTML. In pratice the [xml] tag is used by everyone that needs something with XML-like syntax. Maybe we should use the more flexible HtmlLexer to [xml] tags instead of the XmlLexer.

**Comment by Anteru** [comment]
(Original comment by thatch on 2009-10-08T18:02:30+00:00)

I'm attaching the diff after I've done basic cleanups.

When the .afc file says xml, does it really mean jsp? Part of the examplefile contains something that's very illegal in xml.  The only remaining issue is that jsp != xml.  After that's fixed, we can merge it.

Georg: I did spot-checking for import cycles and I think it's ok.

**Comment by Anteru** [comment]
(Original comment by tshatch on 2015-10-17T14:18:00.524979+00:00)

Tubaina is still in active development, on https://github.com/caelum/tubaina

vraptor4 no longer uses this syntax, it seems, so we're missing an example file.

**Comment by birkenfeld** [comment]
I'm closing all requests for lexers/formatters without a patch/PR.
