### ISSUE TITLE
PythonConsoleLexer has broken traceback highlighting if no module location provided in traceback

### ISSUE THREAD

**Issue by dbader** [pygments/pygments#2226]
## Example 1 (broken)

Input:

```python
>>> exec('"')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 1
    "
     ^
SyntaxError: EOL while scanning string literal
```

Result:
<img width="804" alt="Screen Shot 2022-09-09 at 4 54 46 PM" src="https://user-images.githubusercontent.com/306708/189460110-ee98164b-4e40-4fda-8b12-7beb723a9adb.png">

👆 Notice the two missing lines in the output, starting with the `Traceback (most recent call last):` line. This is a "real" traceback generated by the Python 3.9 REPL.

## Example 2 (okay)

Adding a module location to the 2nd file location (`, in <module>`) restores the missing "Traceback ..." line and renders as expected:

```python
>>> exec('"')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 1, in <module>
    "
     ^
SyntaxError: EOL while scanning string literal
```

Result:
<img width="801" alt="Screen Shot 2022-09-09 at 4 56 35 PM" src="https://user-images.githubusercontent.com/306708/189460091-1b0884fc-cdaf-444c-b470-5cf517e3fb57.png">

Adding a comma (`,`) after the 2nd `File "<string>", line 1` is enough to make the "Traceback ..." line appear (although it won't get the correct highlighting):

<img width="791" alt="Screen Shot 2022-09-09 at 4 59 47 PM" src="https://user-images.githubusercontent.com/306708/189460284-02d2e432-cec8-49aa-bb4c-06c01dce3d1c.png">

## Versions

* pygments version: `2.13.0`
* Also tested on https://pygments.org/demo/ 2022-09-09

**Comment by birkenfeld** [comment]
Thanks for the report!
