### ISSUE TITLE
C# - too many tokens from operators and numbers

### ISSUE THREAD

**Issue by wiktorInny** [pygments/pygments#2256]
import pygments
from pygments.lexers import get_lexer_by_name

source='''
int a = 5;
int b = 15;
if (a == 5)
    b++;
'''

lexer = get_lexer_by_name("csharp", stripall=True)
pygmentsTokens = list(lexer.get_tokens_unprocessed(source))
print(pygmentsTokens)

Operator == produce 2 tokens =, operator ++ too.
Number 15 produce two number tokens: 1 and 5.

**Comment by birkenfeld** [comment]
Thanks for the report!
