### ISSUE TITLE
PowerShell Session Multiline Wrong Highlighting

### ISSUE THREAD

**Issue by iansedano** [pygments/pygments#2262]
It seems that using the "PowerShell Session" highlighter won't pick up multiline constructs, and renders anything after the first line as output.

For instance:

```pwsh
PS> python -m doctest `
> -o DONT_ACCEPT_TRUE_FOR_1 `
> -o ELLIPSIS options.txt
```

Renders like this in https://pygments.org/demo/

![image](https://user-images.githubusercontent.com/38072365/197960843-e176b447-da10-406e-8b14-0eccafe60be0.png)

I initially thought it might be the backtick as the line continuation character, but it seems that any multiline construct is not picked up properly, for example:

```pwsh
PS>  $Params = @{
>     Height = 50
>     Width  = 50
>     Depth  = 50
>     Name   = 'My Widget'
>     ID     = '10dbe43f-0269-48b8-96cb-447a755add55'
> }
```

![image](https://user-images.githubusercontent.com/38072365/197961031-350d14e7-98c6-42fa-9638-155dc074fe0d.png)

Or

```pwsh
PS>  ls |
> grep "python"
```

![image](https://user-images.githubusercontent.com/38072365/197961076-a4b33f12-4a79-4975-859c-e5fd6ae50899.png)

---

On my command line emulator (Windows Terminal), it looks something like this with PowerShell Core:

![image](https://user-images.githubusercontent.com/38072365/197962114-0bb23bc1-d092-4e24-abbc-77e5aec199a7.png)

On the old Windows PowerShell, with conhost.exe, it looks like this:

![image](https://user-images.githubusercontent.com/38072365/197962296-b96ff6ce-6611-400a-9ee7-9d5700d757a7.png)

**Comment by birkenfeld** [comment]
Thanks for the report, can you check if the PR fixes it for you?

**Comment by iansedano** [comment]
Thanks for the super fast response! That fixes it for us!

**Comment by birkenfeld** [comment]
Thanks!
