### ISSUE TITLE
pygments/lexers/sql.py: Invalid keyword 'C'

### ISSUE THREAD

**Issue by luobei42** [pygments/pygments#2272]
sql.py contains a keyword "C" around line 394, that's probably a copy-and-paste error from a keyword list. I checked, there is no ANSI SQL keyword "C".

**Comment by Anteru** [comment]
That list is quite weird anyways. The best I can tell is that it's the union of all keywords from multiple SQL databases, as can be seen here: https://www.drupal.org/docs/develop/coding-standards/list-of-sql-reserved-words

I'm not sure what to do about this though. We could produce an "ANSI standard list" but there are surely people out there relying on the broader list to work, so I'm inclined to keep it as-is.
