### ISSUE TITLE
Add lexer for Portugol language

### ISSUE THREAD

**Issue by LorhanSohaky** [pygments/pygments#2299]
Portugol is a simplified programming language based on Pascal language. This language is used for teach programming for people that speak Portuguese but don't understand English.

https://www.apoioinformatica.inf.br/produtos/visualg/linguagem

**Comment by denilsonsa** [comment]
And this is the list of the keywords from that language: https://www.apoioinformatica.inf.br/produtos/visualg/item/29-referencias-da-linguagem-de-programacao-do-visualg
