### ISSUE TITLE
Confirming output change in Python + Terminal introduced in 2.14

### ISSUE THREAD

**Issue by Gallaecio** [pygments/pygments#2313]
The output of the following code:

```python
from pygments import highlight
from pygments.formatters import TerminalFormatter
from pygments.lexers import PythonLexer

text = "{'a': 1}"
highlighted = highlight(text, PythonLexer(), TerminalFormatter())
print(repr(highlighted))
```

Has changed from 2.13 to 2.14:

```bash
$ pip install pygments==2.13
[…]
Successfully installed pygments-2.13.0
$ python test.py 
"{\x1b[33m'\x1b[39;49;00m\x1b[33ma\x1b[39;49;00m\x1b[33m'\x1b[39;49;00m: \x1b[34m1\x1b[39;49;00m}\n"
$ pip install pygments==2.14
[…]
Successfully installed pygments-2.14.0
$ python test.py 
"{\x1b[33m'\x1b[39;49;00m\x1b[33ma\x1b[39;49;00m\x1b[33m'\x1b[39;49;00m: \x1b[34m1\x1b[39;49;00m}\x1b[37m\x1b[39;49;00m\n"
```

There is an extra `\x1b[37m\x1b[39;49;00m` at the end now, between } and the new line character.

I imagine this is related to the C family changes mentioned in the release notes, as nothing else about Python or Terminal is mentioned there. But none of their definition seems to match this change: both are about functions, and although one mentions braces it mentions them in a comment after a function.

Is this change intended, or a bug? I am not familiar enough with terminal coloring syntax to tell, and from the terminal rendering I do not see an actual change. I wonder if that extra `\x1b[37m\x1b[39;49;00m` is meant to “reset” coloring as to no affect later text. Otherwise, it seems like it might be a bug.

**Comment by Anteru** [comment]
The Terminal formatter hasn't been touched in a while. Python has improved whitespace handling, and comparing the raw tokens I see:
```bash
(test) anteru@borealis:~/envs$ pygmentize -l python -f tokens /tmp/test.py
Token.Punctuation       '{'
Token.Literal.String.Single     "'"
Token.Literal.String.Single     'a'
Token.Literal.String.Single     "'"
Token.Punctuation       ':'
Token.Text      ' '
Token.Literal.Number.Integer    '1'
Token.Punctuation       '}'
Token.Text      '\n'
(test) anteru@borealis:~/envs$ pip install pygments==2.14
Collecting pygments==2.14
  Using cached Pygments-2.14.0-py3-none-any.whl (1.1 MB)
Installing collected packages: pygments
  Attempting uninstall: pygments
    Found existing installation: Pygments 2.13.0
    Uninstalling Pygments-2.13.0:
      Successfully uninstalled Pygments-2.13.0
Successfully installed pygments-2.14.0
(test) anteru@borealis:~/envs$ pygmentize -l python -f tokens /tmp/test.py
Token.Punctuation       '{'
Token.Literal.String.Single     "'"
Token.Literal.String.Single     'a'
Token.Literal.String.Single     "'"
Token.Punctuation       ':'
Token.Text      ' '
Token.Literal.Number.Integer    '1'
Token.Punctuation       '}'
Token.Text.Whitespace   '\n'
```

I thus assume this is part of the improved whitespace handling (and as you can see in the example above, we're not done yet, as there's another `Token.Text` containing whitespace ...), and the `TerminalFormatter` is setting up the background & foreground color for whitespace (I think.) In any case, I don't see the bug as the output looks the same?

**Comment by Gallaecio** [comment]
I’m glad it was an intended change. Thank you for confirming.

> In any case, I don't see the bug as the output looks the same?

I agree.

I do wonder if the Python whitespace handling improvements should be mentioned in the changelog for 2.14. I also wonder why the line break at the end is `Token.Text.Whitespace` now while the actual space in the code remains as `Token.Text`.

However, feel free to close this issue. Thank you!

**Comment by Anteru** [comment]
As to while the whitespace in the text isn't fixed: Because I didn't get around to it yet :) The Python lexer is among the oldest in the project and hence was written before we started paying more attention to `Text.Whitespace`. Retrofitting it is non-trivial.

The changelog doesn't mention it as a dozen or so lexers had improvements to whitespace handling and single-character tokens not being merged correctly, but given this shouldn't affect the output negatively, nor have a lot of visual impact, and wasn't contributed by a contributor I didn't it's worth mentioning... it's part of the regular maintenance :)
