### ISSUE TITLE
PythonConsoleLexer bug: reordered traceback text

### ISSUE THREAD

**Issue by dbader** [pygments/pygments#2329]
## Example:

Lexer: `PythonConsoleLexer` (Python console session)

Input:

```
Traceback (most recent call last):
    ...
KeyboardInterrupt
```

Result:

```html
<div class="demo-highlight"><pre><span></span><span class="nc">KeyboardInterrupt</span>
<span class="gt">Traceback (most recent call last):</span>
<span class="w">    </span><span class="o">...</span>
</pre></div>
```

<img width="801" alt="Screen Shot 2023-01-31 at 10 09 23 AM" src="https://user-images.githubusercontent.com/306708/215846601-694d15f9-0b15-4ca5-b280-87a46893fa87.png">

👆 Notice how the `KeyboardInterrupt` gets moved up above the `Traceback` line in the output

## Versions
* pygments version: 2.14.0
* Also tested on https://pygments.org/demo/ 2023-01-31

**Comment by dbader** [comment]
Might be related to #2226?

**Comment by birkenfeld** [comment]
Thanks for the report!
