### ISSUE TITLE
new lexer request: parrot pir (with patch)

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#237]
(Original issue 458 created by None on 2009-12-11T22:09:58+00:00)

I'd really like to see support for Parrot's PIR (Parrot Intermediate Representation) language. So much so that I wrote a prelimary ParrotLexer myself and will attach the diff.

It works good enough for some tutorial pages on my own site (best samples at [http://coolnamehere.com/geekery/parrot/learn/07-writing-subroutines.html]). I'm not going to pretend this is the bestest lexer ever, but it should give you guys a start.

Reported by brianwisti

**Comment by Anteru** [comment]
(Original issue was assigned to tshatch)

**Comment by Anteru** [comment]
(Original comment by None on 2009-12-23T19:43:32+00:00)

`example-07-03.pir` is the most complicated PIR file I've used this patch for. Output from my own run is visible near the bottom of [http://coolnamehere.com/geekery/parrot/learn/07-writing-subroutines.html this page].

`pirric.pir` is a more complicated PIR app from the Parrot `examples/pir` folder. I have not tested the patch against this file, but I added it in case a larger file like this is useful to you in some way.

**Comment by Anteru** [comment]
(Original comment by thatch on 2009-12-23T19:18:06+00:00)

Trac expects a `diff -u`, but I see the data as well and that won't be an issue in applying the patch.

I'll take a look at it soon and give more feedback -- could you help by providing a complicated example file that we can include for tests?

**Comment by Anteru** [comment]
(Original comment by None on 2009-12-11T22:16:14+00:00)

The diff doesn't display properly in Trac, but it's there. I think I'll need to look a little more closely at how Trac wants a diff generated. Sorry about that.

**Comment by birkenfeld** [comment]
I'm closing all requests for lexers/formatters without a patch/PR.
