### ISSUE TITLE
Fuzz pygments for XSS?

### ISSUE THREAD

**Issue by jvoisin** [pygments/pygments#2423]
Now that pygments is [fuzzed on OSS-Fuzz]( https://github.com/google/oss-fuzz/tree/master/projects/pygments ), would it be worth to add an extra steps to the BBCodeFormatter and HtmlFormatter formatters to:

- validate that the produced xhtml is correctly formatted?
- validate that the only html tags are `<span>` and their only attributes are `class`?

**Comment by Sam2567** [comment]
Hello, I'm a student from the University of Adelaide. I’m working with a group of five students. We are looking forward to contributing this project. We are interested in working on this issue if it is still available.

**Comment by jvoisin** [comment]
Feel free to go ahead with it and to mark me for code review :)

**Comment by jvoisin** [comment]
I meant to say that we might want to have those checks *as part of* the fuzzers running on OSS-Fuzz. I agree that we don't want it into Pygments itself, sorry for the miscommunication :/
