### ISSUE TITLE
Add Lexer for NVIDIA PTX

### ISSUE THREAD

**Issue by Matt711** [pygments/pygments#2431]
I'm interested in adding a Lexer for [NVIDIA PTX](https://docs.nvidia.com/cuda/parallel-thread-execution/#instructions) for a project I'm working on. I see that there's some documentation [here](https://pygments.org/docs/lexerdevelopment/) for adding a new Lexer. Would this be okay to add to the Pygments library?

**Comment by Anteru** [comment]
Sure, we're always happy to include new lexers for new languages! Please create a PR so we can review it.
