### ISSUE TITLE
jump to definition.

### ISSUE THREAD

**Issue by tigros** [pygments/pygments#2466]
Great project, I'm using it in my C# app.

It just dawned on me, why not put links which jump to the definition if it's in the same source file? So vars and functions and... 

What do you think?

Thanks!

**Comment by tigros** [comment]
my app just displays all kinds of stuff in a WebBrowser control (which is IE basically), so static, and it's doing great with pygmetize.

I guess you're right though it's not for any language, I was thinking C#/C++, seems feasible for those kinds of languages and would be a really cool feature if you ask me! Alot of work tho granted..

**Comment by birkenfeld** [comment]
Sorry, but I concur, this is definitely out of scope. Especially for languages that are as complex as C++, there is no way to provide this with any accuracy without a full blown parser.
