### ISSUE TITLE
Discrepancy in Java Lexing (number of tokens) between pip versions Pygments==2.11.2 and Pygments==2.15.1

### ISSUE THREAD

**Issue by LakshyAAAgrawal** [pygments/pygments#2514]
I try to lex the same Java code snippet using Pygments, by using the following code (snippet embedded):
```python3
from pygments.lexers import JavaLexer
text = 'sneakyThrow(t);\n                    return null;\n                } finally {\n                    // No need to clear/reset\n                    // - environment variables\n                    // - system properties\n                    // - thread context classloader\n                    // because each function runs on its own dedicated thread\n                }\n            }'
tokens = list(JavaLexer().get_tokens(text))
print(len(tokens))
```

On version 2.15.1, the number of tokens is 40, whereas in version 2.11.2, it is 35. The difference mostly pertains to whitetext tokens, however.

**Comment by LakshyAAAgrawal** [comment]
Thank you for your prompt response. I appreciate your work on Pygments. I used the above snippet as part of some sanity tests in my project, to ensure Pygments is working as per my assumptions. I was not sure if this difference in token counts between versions was intentional or not, so I thought it would be better to report it.

I understand that Pygments is a dynamic and continuously improving project. I believe it would be great to have some documentation making it explicit that such changes are expected, and when such changes are expected.

**Comment by Anteru** [comment]
We're constantly improving the lexers, and whitespace changes have been done multiple times (and called out in the changelog.) Any change to a specific lexer is also called out, and there have been changes to the Java lexer between those two releases. I'm not sure what else you'd like to see here -- there is no documentation stating that the lexing is fixed and will never change, and accuracy improvements are continuously happening. Those changes are thus expected at all times, but they're generally always spelled out in the changelog.
