### ISSUE TITLE
Support `Mojo`

### ISSUE THREAD

**Issue by Moosems** [pygments/pygments#2515]
With Pygments supporting nearly every language known to mankind, I think it would be nice to see support for the Python-superset [Mojo](https://docs.modular.com/mojo/).

**Comment by Anteru** [comment]
Indeed, but keep in mind that the contributors neither have the expertise with said language, nor the bandwidth to develop additional lexers. We rely on community contributions to expand the lexer corpus. Maybe this is something you'd like to give a try? You can probably start off the Python lexers and extend them accordingly, assuming it is a superset?

**Comment by JonathonReinhart** [comment]
FYI #2691 was merged, but it did not automatically close this issue.

**Comment by Moosems** [comment]
Thanks @JonathonReinhart!
