### ISSUE TITLE
new lexer request: scalate ssp (with patch)

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#252]
(Original issue 473 created by None on 2010-01-29T15:05:59+00:00)

Here is a simple patch to add support for Scalate SSP files which is a scala based template engine...

http://scalate.fusesource.org/

Currently it just reuses the JSP lexing which gives a quick win, making SSP files look quite nice at least. We could improve further by combining the Scala lexer in as well

Reported by jstrachan

**Comment by Anteru** [comment]
(Original comment by thatch on 2010-07-26T18:26:48+00:00)

Sorry it's not in yet, I'll need some more time to look over the patch.  Particularly whether using the JspLexer will cause any problems with scala syntax -- the big thing being that it can parse everything without Error tokens (I agree with you, that it gets 90% of the way there, although some types may be incorrect).  We also need to double-check the analyse_text method to make sure it will play nice with the other lexers.

**Comment by Anteru** [comment]
(Original comment by None on 2010-07-26T14:06:33+00:00)

moved to 1.4 as 1.3 is already done

**Comment by Anteru** [comment]
(Original comment by None on 2010-07-26T14:04:30+00:00)

any chance this patch could be applied please?

**Comment by Anteru** [comment]
(Original comment by None on 2010-02-18T09:20:49+00:00)

Sorry about that - forgot to add a sample page to my patch - I've just added test.ssp; I placed this in the tests/examplefiles and when running...

./pygmentize tests/examplefiles/test.ssp 

pretty prints it quite nicely

**Comment by Anteru** [comment]
(Original comment by thatch on 2010-02-06T01:52:48+00:00)

Looks pretty good.  Could you provide an example file under a suitable license?

**Comment by birkenfeld** [comment]
I'm closing all requests for lexers/formatters without a patch/PR.
