### ISSUE TITLE
Ansi escape character doesn't work

### ISSUE THREAD

**Issue by Sneezy123** [pygments/pygments#2542]
I'm writing a discord bot which renders code. I wrote a lexer and it works fine. 

The problem: When I use `highlight()` to highlight my string, it outputs something like `\x1b[37m# % H\x1b[39;49;00m\x1b[37m\x1b[39;49;00m\n`

Se the escape characters: `\x1b`. What I need though is `\u001b`. How can I get the desired escape character and if I can't, please add the option to change it.

**Comment by birkenfeld** [comment]
You're using TerminalFormatter I assume? It doesn't output the 4 character string `\x1b` literally, just the one control character (escape). That representation is just how Python represents that character when using repr() on a string.
