### ISSUE TITLE
Add support for CMake bracket arguments

### ISSUE THREAD

**Issue by petwu** [pygments/pygments#2549]
It would be nice if the CMake lexer supported [bracket arguments](https://cmake.org/cmake/help/latest/manual/cmake-language.7.html#bracket-argument). Example:

```
message([==[
this is a
multiline argument
]==])
```

Related to #2338 but #2354 only implements bracket comments, not bracket arguments.

**Comment by birkenfeld** [comment]
Thanks for the report!
