### ISSUE TITLE
Check that lexers produce the same output as the input 

### ISSUE THREAD

**Issue by jeanas** [pygments/pygments#2578]
On https://github.com/pygments/pygments/pull/2531, I just noticed missing groups in rules using `bygroups()`, making the lexer lose part of the input. (I've seen it on other PRs too.)

We do have this test in `test_basic_api.py`:

```python
    assert txt == test_content, "%s lexer roundtrip failed: %r != %r" % \
        (cls.name, test_content, txt)
```

but it only runs on random input.

Let's at least do that when highlighting the tests in `tests/snippets/` and `tests/examplefiles/`.

**Comment by Anteru** [comment]
That's a good idea. I also wonder if we can automatically check `bygroups`, after all, if we know how many groups there are, that must match the parameter list. After compiling a regex, `groups` should tell us the number of groups, which then needs to match up with introspection. Not saying we shouldn't run the roundtrip on all example files, but this could be added similar to `regexlint`.

**Comment by birkenfeld** [comment]
Two comments:

* Checking completeness of the output can already be done while generating the golden output
* I thought `regexlint` already checked for this (wrong number of groups)?
