### ISSUE TITLE
`case` in Python not always highlighted

### ISSUE THREAD

**Issue by Marrin** [pygments/pygments#2590]
The current version seems to have a problem with Python's `case` keyword. In the following example the second `case` isn't highlighted:

```python
match spam:
    case Some(x):
        print(f"found {x}")
    case None:
        print("found nothing")
    case _:
        assert False
```

See the online demo:

https://pygments.org/demo/?lexer=python&style=default&formatter=html&code=match+spam%3A%0A++++case+Some%28x%29%3A%0A++++++++print%28f%22found+%7Bx%7D%22%29%0A++++case+None%3A%0A++++++++print%28%22found+nothing%22%29%0A++++case+_%3A%0A++++++++assert+False

**Comment by birkenfeld** [comment]
Thanks for the report!
