### ISSUE TITLE
Add a mIRC Lexer

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#262]
(Original issue 483 created by patx on 2010-03-13T16:18:31+00:00)

I know alot of people who use would like to use a mIRC highlighting. So adding it as a lexer, I think, would be a good idea.

**Comment by Anteru** [comment]
(Original comment by thatch on 2010-05-06T00:41:19+00:00)

How would this be different from the existing !IrcLexer?

**Comment by Anteru** [comment]
(Original comment by TKWare on 2012-01-09T22:26:33.306373+00:00)

mIRC scripting language uses its own syntax. See http://en.wikipedia.org/wiki/MIRC_scripting_language

Looking at IrcLexer, its primary use seems to be parsing raw messages from an IRC daemon.

**Comment by Anteru** [comment]
(Original comment by ShawnSmith on 2012-09-19T19:15:06.562920+00:00)

Any idea when this will be added?

**Comment by Anteru** [comment]
(Original comment by ShawnSmith on 2012-09-19T19:15:52.969520+00:00)

Issue #709 was marked as a duplicate of this issue.

**Comment by Anteru** [comment]
(Original comment by birkenfeld on 2013-01-09T15:16:24.670873+00:00)

Generally, we don't write new lexers ourselves anymore; they have to be contributed.

**Comment by Anteru** [comment]
(Original comment by tshatch on 2015-11-03T15:18:39.353090+00:00)

Could you explain your usecase?  Are you trying to translate the color codes to html?

**Comment by birkenfeld** [comment]
I agree.
