### ISSUE TITLE
PIL.ImageDraw.ImageDraw has no more textsize, it was replace by textlength

### ISSUE THREAD

**Issue by ettoreleandrotognoli** [pygments/pygments#2629]
pygments==2.17.2
pillow==10.2.0

https://stackoverflow.com/a/77070043

Pygments code:
https://github.com/pygments/pygments/blob/e7cdd638d93d187afa3d5696e4fa60cf065238aa/pygments/formatters/img.py#L636

Pillow code:
https://github.com/python-pillow/Pillow/blob/6956d0b2853f5c7ec5f6ec4c60725c5a7ee73aeb/src/PIL/ImageDraw.py#L657C9-L657C19

**Comment by birkenfeld** [comment]
See #2623.
