### ISSUE TITLE
[Bug] TexLexer uses inaccurate definition for command tokens

### ISSUE THREAD

**Issue by nvlang** [pygments/pygments#2637]
The `TexLexer` class from [`pygments/lexers/markup.py`](https://github.com/pygments/pygments/blob/master/pygments/lexers/markup.py) posits that (La)TeX commands are of the format `\\([a-zA-Z]+|.)`:

https://github.com/pygments/pygments/blob/e2f206a35bee1f8642f3c4948f1a436b60d5abd2/pygments/lexers/markup.py#L300

This, however, is inaccurate. For example, in [`expl3`](https://ctan.org/pkg/expl3) packages, one will often find lines like this:

```latex
\new_dim:n \l_@@_example_dim
```

For commands such as these, the colon, underscore, and @ characters should all be considered valid parts of the command names.

However, inside math environments, these characters should not be considered valid parts of command names, since, for example, `\alpha_i` is not a single command, but rather "`\alpha` with subscript `i`" (in LaTeX, equivalent to `\alpha\sb{i}`).

Of course, these claims disregard some exceptional cases (for example, an `expl3`-style command being used inside math mode), but I believe accurately describes the expected syntax highlighting for the vast majority of situations.

I'll make a PR to change the definition in `TexLexer`, but I'm not familiar with the inner workings of the Pygments library, so I'm not sure if the changes will have the intended effects (in particular, I don't know if the changes in the definition of the command tokens will affect the syntax highlighting inside math mode as well). For that, and any other part of this issue, your input would be much appreciated. Thank you!

**Comment by eric-wieser** [comment]
Should this be designed such that the new syntax is only recognized after `\ExplSyntaxOn`?

**Comment by nvlang** [comment]
> Should this be designed such that the new syntax is only recognized after `\ExplSyntaxOn`?

Personally, I wouldn't opt for that, for the following reasons:
- `expl3` syntax is valid in certain places even if no `\ExplSyntaxOn` switch is declared beforehand (e.g., in `expl3` packages and document classes, `\ExplSyntaxOn` is called implicitly, and so won't appear in the source code)
- The code snippet to be highlighted may be an excerpt of an `\ExplSyntaxOn`/`\ExplSyntaxOff` block, and as such not contain those switches, while still being written in `expl3` syntax
- Aside from the issue of conflicts with math mode syntax (as [mentioned before](https://github.com/pygments/pygments/issues/2637#issue-2116539712)), I can't think of many instances where the @, underscore, and colon characters being considered valid "command tokens" would cause any problems / unexpected behavior. There _are_ some small ones (e.g., outside of expl syntax mode, colons may sometimes naturally succeed commands without arguments, as in `text \LaTeX: text`; in this case, the colon is not part of the `\LaTeX` command, but the intended behavior of the proposed changes would highlight the colon as if it _were_ a part of the `\LaTeX` command), at least with the colon character (the @ and underscore characters aren't usually used outside of command names and math mode, as far as I know), but I don't think they're particularly common.

**Comment by birkenfeld** [comment]
I agree with @nvlang - it seems unlikely that giving those characters a permanent letter catcode will cause severe mishighlightings, and on the other hand is useful in highlighting not only `expl3` code but also "normal" LaTeX after `\makeatletter`.
