### ISSUE TITLE
Chances of Path Traversal vulnerability in code

### ISSUE THREAD

**Issue by KarthickRaja2002** [pygments/pygments#2639]
Hi, 

In version 2.13.0, a file in path **"pygments/cmdline.py"** have some chances for **Path Traversal** vulnerability. The details of issues are quoted below.

1. Path Traversal

> 349
>         infn = argns.INPUTFILE
> 350
>         try:
> cancel
> 351
>             with open(infn, 'rb') as infp:
> 352
>                 code = infp.read()
> 353
>         except Exception as err:
> 354
>             print('Error: cannot read infile:', err, file=sys.stderr)
> 355
>             return 1
 
In line no. 351, it is opening a file which is from **System arguments** which may lead to Directory/Path Traversal attack as it is an untrusted input.

2. Path Traversal

> 404
>     outfn = argns.o
>            ...
>            ...
> 441
>         try:
> 442
>             outfile = open(outfn, 'wb')
> 443
>         except Exception as err:
> 444
>             print('Error: cannot open outfile:', err, file=sys.stderr)
> 445
>             return 1

In line no. 442, it is opening a file which is from **System arguments** which may lead to Directory/Path Traversal attack as it is an untrusted input.

Kindly fix this issue.
Thanks in Advance.

Regards,
Karthick Raja N.

**Comment by jeanas** [comment]
This is not a bug or a vulnerability. We definitely want `pygmentize ../foo` to work. The input file name is assumed trusted. If the `pygmentize` script is run on a server and the file name is user-provided, then it is the responsibility of the caller to sanitize it.
