### ISSUE TITLE
awk: ternary operator

### ISSUE THREAD

**Issue by verhovsky** [pygments/pygments#2687]
```
BEGIN {a = 5;b=6; print (a==b)? "a==b" : "a!=b"}
```

https://pygments.org/demo/?lexer=awk&style=solarized-light&formatter=html&code=BEGIN+%7Ba+%3D+5%3Bb%3D6%3B+print+%28a%3D%3Db%29%3F+%22a%3D%3Db%22+%3A+%22a%21%3Db%22%7D

**Comment by birkenfeld** [comment]
Thanks for the report!
