### ISSUE TITLE
Add support for Expr language

### ISSUE THREAD

**Issue by antonmedv** [pygments/pygments#2705]
Hey, 

What about adding support for Expr language (https://expr-lang.org)?

Related https://github.com/expr-lang/expr/issues/646

**Comment by Anteru** [comment]
We (the maintainers) unfortunately don't have the bandwidth to add new lexers for new languages. We highly encourage new contributions though by domain experts (like you - people who know the language they care about!) and hope our contribution guide can help you get started: https://pygments.org/docs/contributing/

**Comment by antonmedv** [comment]
Got it, thanks. Will create a PR.
