### ISSUE TITLE
new lexer request: jflex (with patch)

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#274]
(Original issue 495 created by None on 2010-04-19T14:03:47+00:00)

I have written a lexer for the JFlex input language, to be added to Pygments.

JFlex (http://jflex.de/) is a lexical analyzer generator (also known as scanner generator) for Java, written in Java.

Reported by romildo

**Comment by Anteru** [comment]
(Original comment by tshatch on 2015-10-17T14:21:57.624926+00:00)

JFlex appears to still be an active project.

**Comment by birkenfeld** [comment]
I'm closing all requests for lexers/formatters without a patch/PR.
