### ISSUE TITLE
Add `deb822` format lexer for `*.sources` files

### ISSUE THREAD

**Issue by chrysle** [pygments/pygments#2747]
`deb822` is a newer format to specify system-wide Debian package repositories on Ubuntu in specific fragments (under **/etc/apt/sources.list.d/*.sources**) and an alternative to **sources.list**, for which a lexer does already exist. It is supported by APT itself since version _1.1_, but lacked support in most of Ubuntu's graphical package management utilities – until Ubuntu decided to remove the **sources.list** in favour of the new format in the recently released version 24.04. Most tools have since been catching up with the decision, thus it should be quite useful to create a new lexer for the format (technical specification [here](https://discourse.ubuntu.com/t/spec-apt-deb822-sources-by-default/29333)) and possibly deprecate the **sources.list** lexer.

**Comment by sblondon** [comment]
`sources.list` is currently used in Debian so deprecating seems to be a premature action. I don't know if the replacement of `sources.list` by `*.sources` files is an Ubuntu-project only.

**Comment by sblondon** [comment]
After discussing with Debian Developers, `deb822` is currently supported by Debian (Bullseye and perhaps older versions too) but is not enabled by default. `deb822` will replace `sources.list` format in the future for repository.

**Comment by birkenfeld** [comment]
Even if the format itself is deprecated by Debian, that's no reason to deprecate its lexer in Pygments. It's going to be in use for a long time still. (Also, we currently have no mechanism to deprecate lexers in the first place...)

Regarding the new format, would it make sense to add `*.sources` to the control file lexer for now?

**Comment by chrysle** [comment]
> Even if the format itself is deprecated by Debian, that's no reason to deprecate its lexer in Pygments. It's going to be in use for a long time still. 

Agreed.

> Regarding the new format, would it make sense to add `*.sources` to the control file lexer for now?

Not really, as a Debian `control` file uses `deb822` syntax, but has [completely different fields](https://www.debian.org/doc/debian-policy/ch-controlfields.html#list-of-fields) than `*.sources` files; these are listed in the [`sources.list` manpage](https://manpages.debian.org/bookworm/apt/sources.list.5.en.html#THE_DEB_AND_DEB-SRC_TYPES:_GENERAL_FORMAT). But the current control file lexer may well be used as a template, probably I'll have some time to work on that soon.

**Comment by sblondon** [comment]
> > Even if the format itself is deprecated by Debian, that's no reason to deprecate its lexer in Pygments. It's going to be in use for a long time still.

Yes, `sources.list` will be usable for years. If some lexers should be removed from Pygments, I think other ones are better candidates (for example, `HybrisLexer`). It's a different topic so I don't think more discussion are necessary.


> > Regarding the new format, would it make sense to add `*.sources` to the control file lexer for now?
> 
> Not really, as a Debian `control` file uses `deb822` syntax, but has [completely different fields](https://www.debian.org/doc/debian-policy/ch-controlfields.html#list-of-fields) than `*.sources` files; these are listed in the [`sources.list` manpage](https://manpages.debian.org/bookworm/apt/sources.list.5.en.html#THE_DEB_AND_DEB-SRC_TYPES:_GENERAL_FORMAT). 

The manpage `sources.list` shows several examples of the content of a `*.sources` file. There is an interesting one:

```
Types: deb
URIs: https://deb.debian.org
Suites: stable
Components: main contrib non-free non-free-firmware
Signed-By:
 -----BEGIN PGP PUBLIC KEY BLOCK-----
 .
 mDMEYCQjIxYJKwYBBAHaRw8BAQdAD/P5Nvvnvk66SxBBHDbhRml9ORg1WV5CvzKY
 CuMfoIS0BmFiY2RlZoiQBBMWCgA4FiEErCIG1VhKWMWo2yfAREZd5NfO31cFAmAk
 IyMCGyMFCwkIBwMFFQoJCAsFFgIDAQACHgECF4AACgkQREZd5NfO31fbOwD6ArzS
 dM0Dkd5h2Ujy1b6KcAaVW9FOa5UNfJ9FFBtjLQEBAJ7UyWD3dZzhvlaAwunsk7DG
 3bHcln8DMpIJVXht78sL
 =IE0r
 -----END PGP PUBLIC KEY BLOCK-----
```

The `DebianControlLexer` lexer works mainly well, thanks to the [default field](https://github.com/pygments/pygments/blob/35732f8a538ed7faa9ca90d48bb02ae882793bef/pygments/lexers/installers.py#L294) which catches whatever field.
However:
 - it's more complicated than it needs to be: `maintainer`, `package_list`, ... cases are not needed for example
 - the `Signed-By` is not properly managed because several lines match the same field.

So writing a specific lexer seems to be a better idea.

> I'll have some time to work on that soon.

Great! If you lost interest or don't have time in the future, don't hesitate to say it, I will do it in such case.

**Comment by sblondon** [comment]
@chrysle do you work on the lexer (or do it soon)? If not, I will do it.

**Comment by sblondon** [comment]
I've written it in #2788
