### ISSUE TITLE
CSS Classes, Quotes-Choices

### ISSUE THREAD

**Issue by Torello-Java** [pygments/pygments#2776]
Well, I am a Java based HTML-Guy.  I don't know how more to elaborate.  You can see http://JavaHTML.Torello.Directory - if you would like.  There's a ton of "pygmentize" stuff that I use in my work.  I'm heading in the direction of writing a Syntax HiLiter of my own.  It's going to be strictly for the languages that I HiLite, though, namely: CSS, HTML & Java.  I'm not planning to try writing my own "Java-Script" Syntax-HiLiter.

However, background information abot me part being over, I am still planning and intending to use "pygments.orgP for my Syntax-HiLiting.  I used a Cache of my own devising for saving existing / already-hilited `.java`-Source and `.html`-Source.  I don't "re-hilite" files very often.  As of 2 days ago, however, I have switched to the Command-Line `pygmentize` program that I downloaded using `pip`.  I'm almost done with a Java-Adapter for `pygmentize` which I will likely be using profusely in my project.

Now, as I said, I write a lot of HTML-Parsing code, and I have a feature request for your Tool, `pygmentize`.  I've never written a feature request on Git-Hub before, since I don't use it much, but I'm going to try with you guys.  Note this was "ChatGPT's Idea" - just so you know.

So here goes... Is there any possible / feasible way to CONTROL the names of the CSS-CLASSES you guys use?  Is there likely on the even-horizon amongst you all - that I could simply pass some kind of `-ClassNames` switch to `pygmentize` that allows me to specify some kind of `.properties`-File (or `.json` File) that maps the CSS-Class names that you use, to CSS-Class Names of my own choice?

I can do this myself with my HTML-Parser, and though it would be pretty fast - it would still consume unnecessary Processor-Cycles that I would prefer to eliminate.  If there were a simple, straight-forward and direct way to choose the CSS-Class Names that are used inside of my Syntax-HiLited `.java` Source-Files (as HTML) - then I wouldn't have to do any Post-Processing on the `pygmentize`-Generated HTML-Files that I use.  This would help optimize and speed my programs on my side of the fence.

I have asked ChatGPT (who helps all the time) profusely, and Mr. GPT seemed to remain steadfast that the only way I could get such a feature would be to:

    1. Fork `pygmentize` and do it myself (btw, I cannot read or write a single variable-name in Python)
    2. Use the Java-Based HTML-Parser I have, and change the CSS-Class Names myself
    3. Write a `GitHub` Feature request and pray for rain.

This is the first such request I've made on Git-Hub.  I have already written the code to do it myself (in Java), but it's extra overhead I don't really need.

Let Me Know.  Best Regards.

P.S. There is simply no way I could include HTML in a release that uses Class-Names like CLASS="p", CLASS="cm", CLASS="n" or CLASS="w"!   I cannot "steal" those Clases from my users.

**Comment by Torello-Java** [comment]
[https://chatgpt.com/share/621458a6-e8f2-4651-8a28-d6196a204d80](https://chatgpt.com/share/621458a6-e8f2-4651-8a28-d6196a204d80)

**Comment by birkenfeld** [comment]
Hi there! While I'm impressed by ChatGPT's output, as usual, it gives you incomplete or insufficient truth with 100% conviction here. Therefore, once you know the basics, consulting [the documentation](https://pygments.org/docs/formatters/#HtmlFormatter) is the better choice - if one exists, that is.

In this case, the `classprefix` option does what you want, and can be used for both highlighting and the `-S` invocation.

**Comment by Torello-Java** [comment]
A Class-Prefix is neither what I wanted, nor what I asked about...`.  But all right, some curt remark after all that effort I put into writing you... OK... But you are sayigiving me an answer - with 100% conviction -  that is not correct nor what I wrote.

Good Luck... Best Wishes, but I'm sorry I have written to this account - I should expect no less from Americans...

**Comment by birkenfeld** [comment]
Well, your main question was "Is there any possible / feasible way to CONTROL the names of the CSS-CLASSES you guys use?" and I gave you the best way to have at least partial control - there is no possibility to completely change those names. But it seemed to me that your root issue is that the classes are too short and unspecific, and that a prefix like `pygments-` giving `pygments-p`, `pygments-cm` and similar would address this.

To map the class names to something completely different, you'd have to write some Python code subclassing the HTML formatter. I haven't seen a good enough use case to implement it in the stock formatter class.

(Not sure how you concluded we're Americans by the way.)

**Comment by Torello-Java** [comment]
Well, your suggestion has worked.  I added  "-O", "classprefix=PZ-" to my Java-Adapter invocation.
People who condemn A.I. really - really - make me angry.  You're not a software engineer?  Chat-GPT gives me advice all the time, and it does amaze me sometimes.  The only possible way to have made me angrier would been to have used the word "StackOverflow" in your response.
BTW, my Source-Code is extremely dependent on `pygmentize`, (it embarrasses me a little bit).  I have on my "To-Do" list to write a Syntax-Hiliter, for Java, HTML & CSS - since I have Parsers I've written myself and use for those languages.
Sorry for over-reacting.  I've used a REST End-Point of `pygments.org` for 6 years.
-Best, Ralph.
P.S.  Here's what Mr. GPT told me about the "classprefix" switch.  You suggested to "read the docs" before asking A.I. - well, that's what A.I. does all day - read software docs...
https://chatgpt.com/share/ccd1fcb5-5ee3-4c30-8322-2ab7cfe03822



    On Friday, August 30, 2024 at 02:35:42 AM PDT, Georg Brandl ***@***.***> wrote:  
 
 


Well, your main question was "Is there any possible / feasible way to CONTROL the names of the CSS-CLASSES you guys use?" and I gave you the best way to have at least partial control - there is no possibility to completely change those names. But it seemed to me that your root issue is that the classes are too short and unspecific, and that a prefix like pygments- giving pygments-p, pygments-cm and similar would address this.

To map the class names to something completely different, you'd have to write some Python code subclassing the HTML formatter. I haven't seen a good enough use case to implement it in the stock formatter class.

(Not sure how you concluded we're Americans by the way.)

**Comment by birkenfeld** [comment]
Great - the most important thing is that you got what you needed. On the topic of AI - while I certainly don't outright condemn it, I reserve the right to be skeptical of its outputs, and even more of its overall impact on society. But that's probably not a discussion to have on a GitHub issue :smile:
