### ISSUE TITLE
Outdated documentation "Using Pygments in ReST documents".

### ISSUE THREAD

**Issue by gmilde** [pygments/pygments#2777]
Pygments is used for code highlighting in rST documents since  [Docutils release 0.9](https://docutils.sourceforge.io/RELEASE-NOTES.html#toc-entry-25) (2012-05-02).

There is no need for a custom directive.
Use the ["code" directive](https://docutils.sourceforge.io/docs/ref/rst/directives.html#code) for code blocks and the ["code" role](https://docutils.sourceforge.io/docs/ref/rst/roles.html#code) for inline code.

The `docutils.utils.code_analyzer` module contains the interface and used in the `docutils.parsers.rst.directives.body.CodeBlock` directive class.
In contrast to Pygments' `external/rst-directive.py`, the code is parsed to "Docutils Document Tree" elements and hence usable with all output formats supported by Docutils.

The [syntax_highlight](https://docutils.sourceforge.io/docs/user/config.html#syntax-highlight) configuration setting can be used to switch from a hierarchy of long token type names to short token type names (for use with [Pygments-generated stylesheets](https://pygments.org/docs/cmdline/#generating-styles)).

**Comment by birkenfeld** [comment]
Thanks, indeed that has been unnecessary for a long time.
