### ISSUE TITLE
Ruby strings are sometimes parsed into combinations of characters, and sometimes split into strings

### ISSUE THREAD

**Issue by CameronWang-cell** [pygments/pygments#2790]
issued_code = """
# Alternate format.
sprintf('%#g', 100000000000)  # => "1.00000e+11"
sprintf('%#g', 0.000000000001)  # => "1.00000e-12"
sprintf('%#G', 100000000000)  # => "1.00000E+11"
sprintf('%#G', 0.000000000001)  # => "1.00000E-12"
"""

**Comment by birkenfeld** [comment]
I'm sorry, it's not clear what the issue here is. Can you please elaborate?
