### ISSUE TITLE
Style not taken into account in formatters?

### ISSUE THREAD

**Issue by LoicRiegel** [pygments/pygments#2792]
### Problem

It looks like the style is not taken into account!
Or am I missing something?? ❓ ❗ 
Thanks in advance for your help

### Steps to reproduce

Install pygments 2.18.0

With CLI:
```
pygmentize -f html -O style=colorful,linenos=1 -l python test.py
<div class="highlight"><table class="highlighttable"><tr><td class="linenos"><div class="linenodiv"><pre><span class="normal">1</span></pre></div></td><td class="code"><div><pre><span></span><span class="nb">print</span><span class="p">(</span><span class="s2">&quot;hello&quot;</span><span class="p">)</span>
</pre></div></td></tr></table></div>

pygmentize -f html -O style=bw,linenos=1 -l python test.py
<div class="highlight"><table class="highlighttable"><tr><td class="linenos"><div class="linenodiv"><pre><span class="normal">1</span></pre></div></td><td class="code"><div><pre><span></span><span class="nb">print</span><span class="p">(</span><span class="s2">&quot;hello&quot;</span><span class="p">)</span>
</pre></div></td></tr></table></div>
```

In python REPL:
```
>>> code = """print("hello")"""

>>> highlight(code, lexers.PythonLexer(), formatters.TerminalFormatter(style="bw"))
'\x1b[36mprint\x1b[39;49;00m(\x1b[33m"\x1b[39;49;00m\x1b[33mhello\x1b[39;49;00m\x1b[33m"\x1b[39;49;00m)\x1b[37m\x1b[39;49;00m\n'

>>> highlight(code, lexers.PythonLexer(), formatters.TerminalFormatter(style="sas"))
'\x1b[36mprint\x1b[39;49;00m(\x1b[33m"\x1b[39;49;00m\x1b[33mhello\x1b[39;49;00m\x1b[33m"\x1b[39;49;00m)\x1b[37m\x1b[39;49;00m\n'
```

##### Observed

Formatters with different styles output the same.

##### Expected 

Formatters with different styles produce different outputs based on the style

**Comment by birkenfeld** [comment]
There's two different things to note here why the style apparently doesn't change the output:

- the HTML formatter (by default) outputs no actual styling, just CSS classes that map to token types. You need to generate the respective stylesheet with `pygmentize -S`. Or give the `noclasses` option.
- the `terminal` formatter is a special case; it only uses the 16 standard ANSI colors which can't be easily mapped from different styles, so it has only two fixed color sets (light and dark). Use the `terminal256` formatter instead, it will use the style option.

**Comment by LoicRiegel** [comment]
Okay, thank you for your help @birkenfeld
