### ISSUE TITLE
ActionScript and MXML Syntax Highlighting

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#289]
(Original issue 510 created by None on 2010-06-21T14:51:02+00:00)

The current syntax highlighting for AS3 and MXML is pretty bad. Could you add specific highlighting for .as and .mxml files? In addition, if time is an issue, a stopgap option is to just map .as files to whatever you use to highlight .java files, and map .mxml files to your current .xml highlighter. The highlighting isn't perfect, but it's better than the current setup. Thanks.

Reported by guest

**Comment by Anteru** [comment]
(Original comment by None on 2010-06-29T02:07:30+00:00)

Sure, here are two examples using .mxml and .as file extensions on Gist:

http://gist.github.com/456685#file_pygments_usercontroller.as
http://gist.github.com/456685#file_pygments_userform.mxml

And the same two files with .xml and .java extensions. You can see the XML one has a lot more highlighting, though the actual AS3 code within it is one giant comment block, and the .java one has at least a bit of highlighting although it is still very sparse:

http://gist.github.com/383055#file_quickswiz_usercontroller3.java
http://gist.github.com/383055#file_quickswiz_userform2.xml

There are actually a lot of AS3 and Flex projects on Github/Gist now, so anything you can do to help out on this will be greatly appreciated.

**Comment by Anteru** [comment]
(Original comment by thatch on 2010-06-28T23:12:35+00:00)

Could you provide examples that demonstrate how bad the lexers are? I don't see anything obvious in the lexers (although the mxml lexer does require cdata blocks for your code, which isn't documented).

**Comment by Anteru** [comment]
(Original comment by None on 2010-10-24T00:18:24.609886+00:00)

Just curious if there is any plan to improve the AS3 and MXML support?

**Comment by kurtmckee** [comment]
Based on how Pygments highlights the Actionscript 3 source that was linked to ten years ago, it seems like this issue may not be current.

I recommend closing this ticket, as it seems out-of-date and was last updated ten years ago.

**Comment by birkenfeld** [comment]
Thanks Kurt!
