### ISSUE TITLE
Multiple highlight style features in the HTML formatter

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#290]
(Original issue 511 created by tarek on 2010-06-23T13:01:26+00:00)

It would be nice to support several highlights styles, by providing several sequences of lines, each one with a style.

The use case I had was to highlight a source code with 3 different colors in a coverage tool.

Thanks for the nice tool !

**Comment by Anteru** [comment]
(Original comment by tshatch on 2016-06-02T03:35:15.869821+00:00)

Hi Tarek, sorry this sat so long without a reply. Are you ssaying you might want to give a repeated color,start,end?

**Comment by kurtmckee** [comment]
This ticket is a feature request that received a MOREINFO request. No additional comments were provided.

I recommend closing this ticket due to its age.

**Comment by birkenfeld** [comment]
Yup.
