### ISSUE TITLE
Pygments sets wrong inputenc if utf8 is used

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#291]
(Original issue 512 created by None on 2010-06-25T15:59:29+00:00)

If you pygmentize an utf 8 encoded file to LaTeX, pygmentize will create a line

{{{ \\usepackage[utf-8]{inputenc} }}}

which is wrong. Instead there should be a line similar to;

{{{ \\usepackage[utf8]{inputenc} }}}

Reported by fuzxxl

**Comment by Anteru** [comment]
(Original issue was assigned to gbrandl)

**Comment by Anteru** [comment]
(Original comment by None on 2010-11-10T16:23:17.250288+00:00)

I can confirm this bug. At first i thought it was a bug in latex as pacaked for debian -- but simply changing the usepackage-line as above, results in a tex-file that compiles without error.

This should be a one-line (one byte, techincally) fix -- getting it into pygments would be very much appreciated.

**Comment by Anteru** [comment]
(Original comment by e12e on 2010-11-10T17:05:41.516747+00:00)

In HEAD, the default encoding chosen is 'latin1', unless "self.encoding" is set. This is in pygments/formatters/latex.py. In older versions this whas set to 'utf-8'. A simple way of patching this to work with utf8 is appended below. Not sure what the best way to do this -- a more comprehensive mapping of python encoding names to (La)TeX encding names might be needed.

Unfortunately some more work is needed, as apparently self.encoding is *still* set to 'latin1' for documents that are encoded in utf-8 (testet with a js-file in utf8 with Norwegian characters -- note that these are in latin1 as well -- but the resulting latex-file does *not* work -- the utf-8 characters are embeded as utf8 not latin1).

Hence the patch below "defaults" to utf-8 (again) -- however as stated self.encoding is still incorrectly set to latin1 in some other part of the library.

**Comment by Anteru** [comment]
(Original comment by tshatch on 2010-12-21T07:35:33.862417+00:00)

I believe I see the bug.  Could you provide a short test file that demonstrates the bug, so we can include it in the distribution?

**Comment by kurtmckee** [comment]
This bug may be fixed. The current LaTeX formatter uses 'utf8' (no hyphen) if `self.encoding` is false-y. In addition, some mappings from Python encodings to LaTeX encodings are included:

```python
encoding = self.encoding or 'utf8'
# map known existings encodings from LaTeX distribution
encoding = {
    'utf_8': 'utf8',
    'latin_1': 'latin1',
    'iso_8859_1': 'latin1',
}.get(encoding.replace('-', '_'), encoding)
```

I recommend closing this bug because it seems to have been fixed.

**Comment by birkenfeld** [comment]
Great, thanks for investigating!
