### ISSUE TITLE
LSL Lexer Addidion

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#293]
(Original issue 514 created by None on 2010-07-02T21:51:51+00:00)

Hia - as part of a search to find a code repository for LSL, the scripting language used in Second Life, github referred us to pygments to create a lexer which would then be used within github/trac

Such a lexer already exists, and just needs including!

http://code.google.com/p/pygments-lsl-lexer/

Thanks, Mobius

Reported by guest

**Comment by Anteru** [comment]
(Original issue was assigned to gbrandl)

**Comment by Anteru** [comment]
(Original comment by tshatch on 2010-12-22T06:45:08.071915+00:00)

Hmm. There's quite a bit to do, here are the big ones:

* Must have a file under an appropriate license that we can include for tests
* Clarify (or provide a link for) the syntax for strings and string escapes -- it looks like the lexer is based on the Python lexer but I'm not sure that it should be.
* Clarify whether we can relicense the module as BSD, to match the rest of Pygments.  I'll probably need to contact the author and see if that's possible, if the first two are solved.

**Comment by birkenfeld** [comment]
Google code (and link to new repo) is dead.
