### ISSUE TITLE
Lexer for UMN Mapserver mapfiles

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#297]
(Original issue 518 created by None on 2010-07-29T11:40:20+00:00)

http://mapserver.org/

I have started a mapfile lexer. 

One objective (for me) was, that it works for a line-based highlighting approach, i.e. without much context (I use it in an editor component).

The keyword list still requires completion.

Reported by relet

**Comment by Anteru** [comment]
(Original issue was assigned to gbrandl)

**Comment by Anteru** [comment]
(Original comment by tshatch on 2010-12-21T08:32:18.495536+00:00)

I see.  You need it to work in Sphinx to build your docs.  I think that should be accomplishable as a plugin lexer, and I see you have some version working on your site.  Is there anything we can help with?

**Comment by kurtmckee** [comment]
This ticket has not been updated in ten years. I recommend closing due to its age.

**Comment by birkenfeld** [comment]
Agreed.
