### ISSUE TITLE
java highlight doesn't understand generics

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#303]
(Original issue 524 created by capitol on 2010-08-16T15:17:07+00:00)

This piece of code doesn't get highlighted properly:

public interface myDAO {
  List<String> getValue(String kind);

  String getCategory(String id);
}

The first function doesn't get hilighted as a function.

**Comment by Anteru** [comment]
(Original issue was assigned to gbrandl)

**Comment by Anteru** [comment]
(Original comment by tshatch on 2010-12-21T07:17:01.332079+00:00)

Agreed.  We've historically had problems keeping function detection regexes to be fast, so this may require some thought.  IIRC Java syntax allows the same sort of nesting as C++, so you might have a

    Foo<Map<Integer, String>, Double> func(String x);

Needs some more thought.

**Comment by Anteru** [comment]
(Original comment by capitol on 2010-12-21T08:43:27.097492+00:00)

I agree, I wouldn't try to parse recursive things with regular expressions.

If i would do it in python i would most likely do it with the library pyparsing.

**Comment by Anteru** [comment]
(Original comment by bethard on 2015-05-05T20:33:44.484952+00:00)

While you can't solve all of the cases, lots of instances of Java generics are not recursive; they look like the `List<String>` example above. What about a special-case for this very common, non-recursive pattern, something like `r"(<[^>]*>)?"`?

FWIW, I ran into a similar issue with `new Something<X, Y>()` not being recognized as a constructor call (via Jekyll, which is using pygments.rb 0.6.1 == Pygments 2.0 AFAICT).

**Comment by kurtmckee** [comment]
It appears that the original issue ("The first function doesn't get hilighted as a function") is now fixed:

![image](https://user-images.githubusercontent.com/39996/92287266-eb811380-eece-11ea-8b6a-62754ecc531f.png)

I recommend closing this ticket because it seems to be fixed.

**Comment by birkenfeld** [comment]
Looks ok.
