### ISSUE TITLE
clojure (comment) macro is ignored

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#315]
(Original issue 608 created by None on 2010-10-27T13:14:27.921887+00:00)

In clojure words inside the comment macro are treated as comments and should not be highlighted.

e.g. in 

(comment The word for is not a keyword inside a comment) 

the 'for' should not be highlighted.

**Comment by Anteru** [comment]
(Original comment by tshatch on 2010-12-21T08:37:46.325018+00:00)

Can comments nest or span lines in clojure?

**Comment by kurtmckee** [comment]
I'm not clear how to handle this situation. The Clojure documentation states that `comment` is not a true comment. It is still read in its entirety by the compiler and must be 100% valid. However, after reading the block the compiler doesn't generate any code. Therefore I'm not convinced that `comment` should be tokenized as comment text. [source](https://clojuredocs.org/clojure.core/comment)

In addition to appearing invalid, the ticket is ten years old. I recommend closing the ticket.

**Comment by birkenfeld** [comment]
Let's do it.
