### ISSUE TITLE
new lexer request: clay (with patch)

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#339]
(Original issue 632 created by tsion on 2011-02-01T02:17:10.023130+00:00)

I have written a lexer for the [[http://claylanguage.org|Clay programming language]] based off of the Java lexer and my own gtksourceview language file for Clay. Attached are the lexer file and a Clay source file I used for testing the lexer. 

The lexer is hosted on GitHub at https://github.com/tsion/clay-pygments-lexer.

The MIME type 'text/x-clay' has been submitted to freedesktop.org for inclusion: https://bugs.freedesktop.org//show_bug.cgi?id=33740.

**Comment by Anteru** [comment]
(Original comment by None on 2011-02-01T17:34:24.032294+00:00)

I made a small change to the lexer. The most up to date version can be found at https://github.com/tsion/clay-pygments-lexer/raw/master/clay_lexer.py.

**Comment by Anteru** [comment]
(Original comment by tsion on 2011-02-01T17:35:34.060110+00:00)

Sorry, that last comment should have been me. I got logged out somehow.

**Comment by Anteru** [comment]
(Original comment by tshatch on 2011-03-17T07:27:01.888324+00:00)

I took a quick look at the git repo and it looks good so far.  I'll take a look soon and get it included.  Is there a certain shebang, or anything else unique that would typically be at the top if the file that could be used for language guessing, when necessary?

**Comment by Anteru** [comment]
(Original comment by None on 2011-03-17T22:00:52.229123+00:00)

Nope, no shebang or anything like that, Clay is always compiled ahead of time.

**Comment by birkenfeld** [comment]
I'm closing all requests for lexers/formatters without a patch/PR.
