### ISSUE TITLE
add Dark Basic

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#348]
(Original issue 641 created by None on 2011-02-22T17:08:22.874939+00:00)

Dark Basic is a simple langage "basic", for build 3D games:

http://en.wikipedia.org/wiki/DarkBASIC

and

http://en.wikipedia.org/wiki/DarkBASIC_Professional

**Comment by Anteru** [comment]
(Original comment by tshatch on 2011-03-21T00:16:55.199696+00:00)

From a very cursory glance at the wikipedia/wikibooks examples, it looks like basic syntax with a few more functions.  Can you clarify whether your request is for content changes (like new builtins) or simply for a new file extension to be added to the existing basic lexer?

**Comment by Anteru** [comment]
(Original comment by tshatch on 2011-03-21T00:16:55.913100+00:00)

double post

**Comment by birkenfeld** [comment]
I'm closing all requests for lexers/formatters without a patch/PR.
