### ISSUE TITLE
new lexer request: csv

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#349]
(Original issue 642 created by Y0Gi on 2011-02-25T09:31:57.523578+00:00)

I'd like to see the addition of a CSV lexer so I can highlight CSV data in blog posts, wiki articles, and documentation. It's basically about displaying delimiter characters, quoting characters, and the actual data differently to be easier to skim through.

**Comment by Anteru** [comment]
(Original comment by tshatch on 2011-03-17T07:20:33.860895+00:00)

This is likely to have the same problems that our sql lexer has -- namely that there are multiple, incompatible standards.

**Comment by Anteru** [comment]
(Original comment by stephen-paul-chappell on 2014-08-26T14:49:02.395631+00:00)

Maybe there should be a lexer for each dialect of CSV and SQL?

**Comment by birkenfeld** [comment]
I'm closing all requests for lexers/formatters without a patch/PR.
