### ISSUE TITLE
new lexer request: masm

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#356]
(Original issue 649 created by yontoryu on 2011-03-25T12:01:01.150604+00:00)

MASM is the Microsoft Macro Assembler :

I know there is already a NASM highlighter, but MASM is quite different. For example comment like this :

```
#!nasm

comment & This is a comment.
          That works on MASM.&
```
Does not work on NASM, because it's a MASM directive.

There are also a lot of macros in the MASM library, and of course they are not supported by NASM. 

The MASM community is quite big (as big as an Asm community can be...), so i think many people would like to have a code highlighter for it.

Thank you.

**Comment by Anteru** [comment]
(Original comment by birkenfeld on 2013-01-09T15:19:32.402813+00:00)

Generally we accept contributed lexers, but don't write ones ourselves.

**Comment by birkenfeld** [comment]
I'm closing all requests for lexers/formatters without a patch/PR.
