### ISSUE TITLE
new lexer request: ProC and ProC++ (with patch)

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#362]
(Original issue 655 created by imednev on 2011-03-30T11:15:11.159682+00:00)

Since we use Oracle Pro*C and Pro*C++ we needed to add syntax-highlighting for them.

In the attached .diff files you can see the proposed enhancements.

Please, let us know what you think about that, as it would be great if this is included in the future releases of Pygments.

**Comment by birkenfeld** [comment]
I'm closing all requests for lexers/formatters without a patch/PR.
