### ISSUE TITLE
new lexer request: fasm (assembler)

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#369]
(Original issue 662 created by droiddev on 2011-05-02T03:55:47.872629+00:00)

Please, add FASM ( http://www.flatassembler.net/index.php ) syntax/highlight support

**Comment by Anteru** [comment]
(Original comment by droiddev on 2011-07-11T14:25:52.032086+00:00)

here is snippet example http://pygments.org/demo/19769/?style=native

FASM syntax is similar to NASM:

here is perl-scripts converting FASM to NASM and NASM to FASM
http://rudy.mif.pg.gda.pl/~bogdro/inne/nasm2fasm.txt 
http://rudy.mif.pg.gda.pl/~bogdro/inne/fasm2nasm.txt

**Comment by birkenfeld** [comment]
I'm closing all requests for lexers/formatters without a patch/PR.
