### ISSUE TITLE
new lexer request: arm assembler

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#385]
(Original issue 678 created by droiddev on 2011-07-11T14:20:08.097434+00:00)

Here is an examples of such highlight (using snippets from ida pro)

https://www.droid-developers.org/wiki/Secure_Services
https://www.droid-developers.org/wiki/CPCAP

here its source on PHP/Geshi http://paste.pocoo.org/show/436107/

**Comment by Anteru** [comment]
(Original comment by tshatch on 2012-11-01T16:44:56.035577+00:00)

The pastebin entry is gone, but I don't think it would be much help since GeSHI is GPL.

**Comment by birkenfeld** [comment]
I'm closing all requests for lexers/formatters without a patch/PR.
