### ISSUE TITLE
new lexer request: FBP workflows (with patch)

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#405]
(Original issue 698 created by bergie on 2011-09-09T12:54:57.372971+00:00)

.fbp files are used for defining workflows for Flow-Based Programming engines like NoFlo (https://github.com/bergie/noflo).

Attached is a lexer for the format.

**Comment by birkenfeld** [comment]
I'm closing all requests for lexers/formatters without a patch/PR.
