### ISSUE TITLE
new lexer request: spip (with patch)

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#410]
(Original issue 703 created by Maieul on 2011-09-19T15:54:59.339560+00:00)

I made a Lexer for the language of the french CMS SPIP.

I propose it : https://github.com/maieul/spip-pygments.

Must I push it on the hg repository ?

**Comment by Anteru** [comment]
(Original comment by Maieul on 2013-11-16T19:04:16.862957+00:00)

Hi, some news ?

**Comment by Anteru** [comment]
(Original comment by tshatch on 2016-06-01T06:59:54.794065+00:00)

(This issue got overlooked for far too long.)  If you're still interested in having it included, I would appreciate a link to the part of SPIP (either code or documentation) that defines this format.  Do the files really use .html as the extension?

**Comment by Anteru** [comment]
(Original comment by camilstaps on 2016-06-01T07:14:58.793770+00:00)

Syntax for loops ('boucles'): http://www.spip.net/en_article2042.html  
Syntax for tags ('balises'): http://www.spip.net/en_article2055.html

In general, SPIP is ill-documented in English (French docs are somewhat better, still not great) and it can be a pain to work with. (There are also several issues in the code, which has been moved to http://zone.spip.org/trac/spip-zone/browser/_contribs_/pygments. I can better comment on those when a pull request has been created.) However, in general this looks like a nice addition.

**Comment by Anteru** [comment]
(Original comment by Maieul on 2016-06-01T07:59:09.112736+00:00)

Yes, It really use .html as extension. The two links of Camil explain the syntax, and are  covered 90 % of the code. But for the need of developing this module, I used http://programmer.spip.net/ and all the fragment of code where well formated.

**Comment by birkenfeld** [comment]
I'm closing all requests for lexers/formatters without a patch/PR.
