### ISSUE TITLE
new lexer request: sweet

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#425]
(Original issue 718 created by joaomdmoura on 2011-12-14T04:28:50.254240+00:00)

Hello,
I have a project of a precompiled language called Sweet (https://github.com/joaomdmoura/sweet) this is already released with a v0.1.0, and i would to like to implement it on pygments, but i really dont have idea about how can i do this, git hub recommend me open a  issue here asking for it...then here am I :)
Thanks in advanced.

**Comment by Anteru** [comment]
(Original comment by None on 2012-03-01T01:59:50.199191+00:00)

The sweet language already is at version 0.4.6, the new release will be at 0.5.7, there is already almost 300 downloads, I've published a post about it at joaomdmoura.com/posts/2

**Comment by birkenfeld** [comment]
I'm closing all requests for lexers/formatters without a patch/PR.
