### ISSUE TITLE
Wishlist: support Org?

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#426]
(Original issue 719 created by sharyanto on 2011-12-14T14:49:56.445866+00:00)

Hi,

Any plans to support Org?

More about Org format: http://orgmode.org/

Thanks,
Steven

**Comment by Anteru** [comment]
(Original issue was assigned to tshatch)

**Comment by Anteru** [comment]
(Original comment by tshatch on 2014-05-17T01:26:16.477957+00:00)

If you can point us to something describing the syntax, then sure.

**Comment by Anteru** [comment]
(Original comment by xparx on 2015-08-05T19:39:14.837669+00:00)

Hi,
I hope this is something useful to to you for implementing support for [org-mode sytax](http://orgmode.org/worg/dev/org-syntax.html).

There is an issue here on BB that at least show some traction for this [here](https://bitbucket.org/site/master/issues/6569/support-org-mode-for-readme-files-bb-7757), so hopefully you can find some time to add it.

adding a link to what is org's own parser. May be it is helpful to you, [org-elements](http://orgmode.org/worg/exporters/org-element-docstrings.html)
 
Regards, A

**Comment by Anteru** [comment]
(Original comment by unhammer on 2015-10-14T08:18:25.010819+00:00)

https://github.com/gollum/gollum/blob/ab42c0c0dfc9879f73312ad2c804875b510a414c/lib/gollum/public/gollum/javascript/editor/langs/org.js seems to be gollum's org-mode handling

**Comment by Anteru** [comment]
(Original comment by rustom on 2015-10-14T12:55:57.628115+00:00)

@tshatch: If you can point us to something describing the syntax, then sure.


http://orgmode.org/worg/dev/org-syntax.html

**Comment by Anteru** [comment]
(Original comment by tshatch on 2015-10-17T01:04:31.624236+00:00)

I agree this would be useful, thanks for the links.  I'll try to get to it for the April 2016 release.

**Comment by Anteru** [comment]
(Original comment by germanemotiv on 2015-12-17T07:44:08.788481+00:00)

I would like to get support for this :) Github does and it is very handy.

**Comment by Anteru** [comment]
(Original comment by None on 2015-12-30T15:14:41.495033+00:00)

pls add i thought it is already supported :crying_cat_face:

**Comment by Anteru** [comment]
(Original comment by malcook on 2016-01-08T19:35:46.637923+00:00)

+1, and, an implementation suggestion:

[pandoc](http://pandoc.org/) can be used to convert both markdown and org to html on the fly.

The following is an extract from an Apache .config file that allows for such conversions when docs are served by Apache.  I imagine something similar might work for bitbucket configuration.

```
#!shell

       # mec: Interpret markdown files to html on the fly                                                                                                                                                                                
        ExtFilterDefine markdown-to-html mode=output \                                                                                                                                                                                    
                intype=text/markdown outtype=text/html cmd="/n/local/bin/pandoc -f markdown  -t html"                                                                                                                                     
                ## --email-obfuscation=references                                                                                                                                                                                         
        SetOutputFilter markdown-to-html                                                                                                                                                                                                  
        AddType text/markdown .md                                                                                                                                                                                                         
        ##.markdown .md .Rmd                                                                                                                                                                                                              
        # mec: Interpret orgmode files to html on the fly                                                                                                                                                                                 
        ExtFilterDefine orgmode-to-html mode=output \                                                                                                                                                                                     
                intype=text/orgmode outtype=text/html cmd="/n/local/bin/pandoc -f org  -t html"                                                                                                                                           
                ## --email-obfuscation=references                                                                                                                                                                                         
        SetOutputFilter orgmode-to-html                                                                                                                                                                                                   
        AddType text/orgmode .org  
```

**Comment by Anteru** [comment]
(Original comment by scott_harney on 2016-03-03T16:24:37.363828+00:00)

+1 for this addition. thanks

**Comment by Anteru** [comment]
(Original comment by buenchaval on 2016-06-15T08:35:33.388944+00:00)

please add this. org-mode is awesome. thanks!

**Comment by Anteru** [comment]
(Original comment by digash on 2017-07-20T15:07:11.954741+00:00)

(+ 1)

**Comment by Anteru** [comment]
(Original comment by kaushalmodi on 2017-08-04T17:33:57.329518+00:00)

+1 please.

I am using Pygments with Hugo static site generator, and at the moment the Org source blocks are not recognized as code blocks.

**Comment by Anteru** [comment]
(Original comment by amitthk on 2018-01-13T03:53:46.151994+00:00)

+1

**Comment by Anteru** [comment]
(Original comment by kaushalmodi on 2018-08-01T18:15:16.856712+00:00)

I just implemented the [Org mode syntax highlighting][1] in the Go Chroma syntax highlighter (whose syntax is very much similar to Pygments'). Folks interested in Org mode syntax highlighting can switch to Chroma or port over that lexer from that PR to Pygments :)

[1]: https://github.com/alecthomas/chroma/pull/156

**Comment by kurtmckee** [comment]
As noted in the comments, it is possible to port Org mode support from Chroma (which is a Go port of Pygments) back to Pygments. However, this ticket has been open for nine years and nobody has chosen to implement this.

I recommend closing this ticket.
