### ISSUE TITLE
Support ANSI (ECMA-48) color-coded text input

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#477]
(Original issue 770 created by mgorny on 2012-05-14T06:18:43.247173+00:00)

I feel like many pastebin users would appreciate such a feature in pygments: reading (already colored) data stream with ECMA-48 color codes embedded (like console program output) and outputting it in any format pygments support.

I guess such a feature would require adding a new token types to represent console colors.

If there's interest in this, I can assemble a patch for it.

**Comment by Anteru** [comment]
(Original comment by tshatch on 2012-11-12T23:04:42.629400+00:00)

I'd be interested in at least a 16-color version of this.  Some of the other codes (like bold, reverse, etc) might overcomplicate it however.  Can you get a basic version ready to review in the 1.7 time frame (guessing 6 months out)?

**Comment by Anteru** [comment]
(Original comment by mgorny on 2012-11-13T05:15:04.206501+00:00)

Yes, I think I can. Unless I forget ;).

**Comment by Anteru** [comment]
(Original comment by tshatch on 2013-05-10T01:35:36.912696+00:00)

How's it coming?

**Comment by Anteru** [comment]
(Original comment by mgorny on 2013-05-10T07:00:57.332637+00:00)

I'm sorry but I'm overburdened with work all the time, and this one doesn't come as a priority to me. I will be happy to work on this but I don't know when I'll have a free hand.

**Comment by Anteru** [comment]
(Original comment by dejanm on 2014-11-20T20:25:36.473941+00:00)

I was looking into this too. Seems to be somewhat botched. Michał, do you still intend to work on such a feature?

**Comment by Anteru** [comment]
(Original comment by mgorny on 2014-11-20T20:44:11.394289+00:00)

I'm sorry but I can't afford to work on this in any foreseeable future.

**Comment by Anteru** [comment]
(Original comment by dejanm on 2014-11-26T14:55:02.287765+00:00)

I started working on this, but I'm not entirely sure how to proceed. My first idea was to replace ANSI color codes with RGB color codes, but I'm not sure how to do that, i.e. how to insert those RGB color codes into the output. Can a lexer do that kind of preprocessing?

Or is it necessary to have this kind of token rules:

(r'%s(3[0-7])m(.*?)%s%s' % (esc, esc, reset_re), ansi2rgb)

where ansi2rgb would lookup and yield appropriate color tokens. If so, where would we define these tokens? All tokens are defined in various styles, but that seems like an overkill.

**Comment by Anteru** [comment]
(Original comment by mgorny on 2014-11-26T17:27:51.797432+00:00)

Well, my initial idea was to introduce new token types representing the 16 standard colors, then mapping them to real colors via style. This would also allow overriding colors properly for light background.

**Comment by Anteru** [comment]
(Original comment by cpitclaudel on 2015-02-03T04:48:26.202820+00:00)

I'd be interested in this too. This would make it easy to typeset colorized script output in latex files, via minted.

**Comment by Anteru** [comment]
(Original comment by dejanm on 2015-02-03T15:10:06.472786+00:00)

On Tue, Feb 03, 2015 at 04:48:27AM -0000, Clément Pit--Claudel wrote:

This is something I put together which could give me usable
output from files generated by the script(1) program:

https://bitbucket.org/dejanm/pygments-main/branch/ansicolors

However, it supports only 8 colors (30m-37m) and can parse only
color codes which are not combined with other graphic control
codes.

It would be rather difficult to make a general graphics code
parser with regular expressions, but I'm still not sure how to
implement more complex parsers. Comments and suggestions would be
very appreciated.

**Comment by Anteru** [comment]
(Original comment by tshatch on 2015-10-07T14:30:31.865077+00:00)

I would suggest using r'\x1b(.*?)m' as your pattern and using a callback that does the parsing.  I can help further by email if you'd like.

**Comment by Anteru** [comment]
(Original comment by dejanm on 2015-10-15T08:15:30.064576+00:00)

Many thanks for the suggestions. I'm a bit swamped right now, but
will get back to this eventually. (famous last words)

**Comment by kurtmckee** [comment]
This ticket's goal is to have Pygments translate existing ANSI color codes to other formats (like HTML) while retaining the existing colors. This doesn't seem to match Pygments' goal, which is to create tokens based on meaning (not based on colors).

I recommend closing this ticket.

**Comment by birkenfeld** [comment]
We do have the 16 "ansi" colors in the style nowadays, so making a lexer for the 16 base colors would be feasible.

**Comment by kurtmckee** [comment]
To be clear, both the original poster and I think this would require new tokens. I anticipate they will have names like `Token.Color.RedIntenseOnWhiteIntense` or `Token.Color.WhiteNormalOnBlackNormal`. Then each of the styles, like fruity and monokai, would need to be updated to render the color tokens.

It's definitely feasible to do this, but the non-semantic color tokens don't seem "correct" to me.

**Comment by birkenfeld** [comment]
True. Let's not do this then.

**Comment by kdeldycke** [comment]
For the record, there is a third party plugin for Pygments that is adding ANSI color support at: https://github.com/chriskuehl/pygments-ansi-color
