### ISSUE TITLE
Add a LESS lexer

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#487]
(Original issue 780 created by emilecantin on 2012-06-07T15:31:16.998199+00:00)

It would be great to have a LESS ( http://lesscss.org ) lexer. There's not much difference from CSS, mainly single-line comments and variables that begin with @.

**Comment by Anteru** [comment]
(Original comment by birkenfeld on 2013-01-09T15:21:02.047965+00:00)

We would be happy to accept a contribution.

**Comment by Anteru** [comment]
(Original comment by jaredly on 2013-03-29T23:44:45.570668+00:00)

Could you just use the Scss lexer?

**Comment by Anteru** [comment]
(Original comment by david-xie on 2016-02-05T00:55:33.590568+00:00)

@birkenfeld what's the status of this ticket?

**Comment by Anteru** [comment]
(Original comment by masklinn on 2017-07-03T09:37:38.496442+00:00)

@david-xie there is now a LessCSSLexer, however it seems to be a pretty straight CSS lexer (which is problematic due to e.g. Sphinx unconditionally using raiseonerror when highlighting):

* no support for single-line comments #1342
* no support for rules nesting #1330 (@bittucket I assume you didn't have the time to work on your PR?)

**Comment by birkenfeld** [comment]
I'm closing all requests for lexers/formatters without a patch/PR.
