### ISSUE TITLE
Generic Lexer

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#499]
(Original issue 792 created by None on 2012-07-25T11:01:35.717500+00:00)

As a user of pygments I would like to be able to highlight code of a not yet existing or stable language through the use of a not yet existing //generic// lexer where they keywords to highlight and patterns form literal and such are passed as lexer arguments.

A usage with the code block in github wiki would look like this
```
 ```generic keywords=if,then,else literals='[a-Z]+
 <code here>
 ```
```

**Comment by Anteru** [comment]
(Original comment by birkenfeld on 2012-08-19T08:35:09.819370+00:00)

Nice idea, but needs an implementation :)

**Comment by birkenfeld** [comment]
I'm closing all requests for lexers/formatters without a patch/PR.
