### ISSUE TITLE
SMTP Header Lexer

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#515]
(Original issue 808 created by nickl on 2012-10-02T15:21:18.711536+00:00)

Since we've been spoilt with HTTP header highlights it is only disappointing not to be able to colour-code SMTP or e-mail headers. 

Not that this is going to solve global warming or anything but it would be an equal travesty if expectation doesn't match the level of the bar you've already set so high, agreed?

Tx for an awesome work of art, I have pygmenst hardwired into less (a trues to bob custom compile to remove warnings and ignore ENV setting) and even though there are probably faster solutions, I'd much rather see some colour than none. Keep up the good work guys!! 

P>S> Special tx for the encoding fix =D, you rock!!!

**Comment by Anteru** [comment]
(Original comment by birkenfeld on 2013-01-09T15:25:00.432780+00:00)

This is certainly a valid request; we are open for contributions :)

**Comment by Anteru** [comment]
(Original comment by bjourne on 2013-02-02T15:36:41.652965+00:00)

The "properties" lexer works fine for colorizing headers.

**Comment by Anteru** [comment]
(Original comment by nickl on 2013-02-02T23:47:47.183167+00:00)

Affirmed, properties lexer does do something, even though it's mostly in the same colour. Why would it not be detectable with -g though? Any ideas?

**Comment by kurtmckee** [comment]
This lexer request is eight years old. I recommend closing it.
