### ISSUE TITLE
Lexer for CMakeLists.txt is guessed incorrectly

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#523]
(Original issue 816 created by sijk on 2012-10-21T23:28:14.507932+00:00)

Files named CMakeLists.txt are correctly assigned a CMakeLexer if you use `get_lexer_for_filename`. They are incorrectly assigned a TextLexer if you use `guess_lexer_for_filename`. 

    #!python
    In [2]: guess_lexer_for_filename('CMakeLists.txt','')
    Out[2]: <pygments.lexers.TextLexer>

    In [3]: get_lexer_for_filename('CMakeLists.txt')
    Out[3]: <pygments.lexers.CMakeLexer>

Given `CMakeLists.txt` is a more specific name than `*.txt` it seems to me that both functions should return a CMakeLexer.

**Comment by Anteru** [comment]
(Original comment by tshatch on 2012-11-06T15:55:30.873680+00:00)

Let's look at this for 1.61.  I suspect it's because CMakeLexer doesn't have an analyse_text method.

**Comment by Anteru** [comment]
(Original comment by scopatz on 2014-03-14T23:48:31.659275+00:00)

I am still seeing this issue.

**Comment by Anteru** [comment]
(Original comment by jaingaurav2 on 2014-04-14T22:06:21.371151+00:00)

Neither of the lexers have a analyse_text method. I think the solution would require a 'bonus' score for explicit filename pattern matches as done in get_lexer_for_filename

**Comment by Anteru** [comment]
(Original comment by jaingaurav2 on 2014-04-14T22:35:09.324152+00:00)

What is supposed to be the difference between guess_lexer_for_filename and get_lexer_for_filename? Both take a filename and code to analyse.

**Comment by Anteru** [comment]
(Original comment by sijk on 2014-04-14T23:35:40.465133+00:00)

@jaingaurav2: [get_lexer_for_filename](http://pygments.org/docs/api/#pygments.lexers.get_lexer_for_filename) doesn't take text to analyse; it just maps file names/extensions to lexers. [guess_lexer_for_filename](http://pygments.org/docs/api/#pygments.lexers.guess_lexer_for_filename) takes a filename and text to analyse.

**Comment by Anteru** [comment]
(Original comment by jaingaurav2 on 2014-04-15T02:47:26.020562+00:00)

get_lexer_for_filename seems to take an optional second parameter that can be the text to analyse

**Comment by Anteru** [comment]
(Original comment by sijk on 2014-04-15T03:11:02.967759+00:00)

Hmm sorry, looking at the code you're right. I was going by the [docs](http://pygments.org/docs/api/#pygments.lexers.get_lexer_for_filename) at pygments.org which don't mention a second parameter. That's odd, because get_... was changed to accept that optional parameter in 2009 (#355).

**Comment by roskakori** [comment]
Not sure if it is related to this issue but  `CMakeLexer.analyze_text` has several issues that prevent it from detecting CMakeLists.txt by looking at the code, with the most prominent one being that only single digit versions numbers work. I submitted a fix for that with #1491.
