### ISSUE TITLE
Word wrap for HTML formatter

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#555]
(Original issue 848 created by nathany on 2013-02-16T20:16:06.526099+00:00)

When reading code on mobile devices or at large font sizes, the current solutions use a lot of horizontal panning. I have been experimenting with supporting word wrap -- here is a [mockup](http://www.tint.io/).

At the most basic level, this could be a matter of injecting a `<wbr>` tag after any word separator (eg. `./\()\"'-:,.;<>~!@#$%^&*|+=[]{}~?`\`) that isn't already followed by a space. Using `<wbr>` tells the browser that it *may* insert a line-break, and copy & pasting the code still works as expected.

I'm posting this proposal both to gauge interest, and because several challenges remain before this will work really well.

* Hanging indents and guides, as I currently have them, introduce copy & paste issues and font-dependencies (using em's for indentation, which are based on the height, not width of the font).
* Handling code that has been hard-wrapped, especially when indented beyond the norm (for alignment).
* Detecting long unbreakable words (eg. `http://dowebsitesneedtolookexactlythesameineverybrowser.com/`) and allowing the browser to force a break at any character with `word-break: break-all`.
* Handling line numbers when text is wrapped.
* Integration with the existing Pygments code base. Even just the naming, as there are several options to wrap the output in some additional HTML.
* Internet Explorer support. My tests with IE9/10 fail. I did find a [lengthy document](http://www.cs.tut.fi/~jkorpela/html/nobr.html) that could help.
* I was also experimenting with preventing word wrap when appropriate, to keep the code as valid and readable as possible. This introduces lexer dependencies -- defining where *implied line continuations* are allowed for each language.

I hope this weekend or two of experimentation perks your interest in taking syntax highlighting to the *"next level."* Cheers.

**Comment by Anteru** [comment]
(Original issue was assigned to birkenfeld)

**Comment by Anteru** [comment]
(Original comment by nicorellius on 2013-08-16T16:59:31.426407+00:00)

I think this is a great idea. Would love to see it happen.

**Comment by kurtmckee** [comment]
I recommend closing this ticket because it is seven years old. Also, I don't personally see benefit to word wrapping code on mobile platforms.

**Comment by birkenfeld** [comment]
Yes, this is not going to happen without someone doing the PR.
