### ISSUE TITLE
new lexer request: cshtml (Razor)

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#572]
(Original issue 865 created by rdumont on 2013-03-28T02:24:56.576163+00:00)

I would love to see Pygments support Razor (.cshtml) language. It is now a major templating engine and present in thousands of repositories.

I am trying to implement it myself, but the result isn't too good so far, so a little help would be great!

Thanks.

**Comment by kurtmckee** [comment]
This lexer request is seven years old. I recommend closing it.
