### ISSUE TITLE
`cls` as builtin word for python

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#587]
(Original issue 880 created by dave_mckean on 2013-06-12T23:35:54.451089+00:00)

Should `cls` be added to the builtins state in PythonLexer as is `self`? (As defined in the [agile.py](https://bitbucket.org/birkenfeld/pygments-main/src/7304e4759ae65343d89a51359ca538912519cc31/pygments/lexers/agile.py?at=default#cl-92) lexer)

See [PEP8: Function and method arguments](http://www.python.org/dev/peps/pep-0008/#function-and-method-arguments)

**Comment by birkenfeld** [comment]
I don't think so; it is probably much more often used as a normal variable than as a "position-0" argument for metaclass methods.
