### ISSUE TITLE
new lexer request: Python Server Pages

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#589]
(Original issue 882 created by ypid on 2013-06-23T18:23:28.278309+00:00)

Hi

It should not be to hard to implement support for psp since it is just Python embedded in HTML. It would be great if this could be done.

http://www.modpython.org/live/current/doc-html/pyapi-psp.html

**Comment by kurtmckee** [comment]
I recommend closing this ticket due to its age.

**Comment by birkenfeld** [comment]
Yes, hopefully nobody does PSP anymore :)
