### ISSUE TITLE
new lexer request: LilyPond

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#611]
(Original issue 904 created by jan-warchol on 2013-09-13T15:03:37.540443+00:00)

[GNU LilyPond](lilypond.org) is a program for engraving musical scores. It works like LaTeX, i.e. the music is written in a plain text format compiled by the program.

I know that some programs can highlight LilyPond code (for example [Frescobaldi](frescobaldi.org/), which is written in Python), and that work could probably be reused, but as i've never worked on syntax highlighting before i don't know what exactly would be needed - please let me know and i'll try to help.

**Comment by Anteru** [comment]
(Original comment by dscorbett on 2016-06-02T16:55:35.725645+00:00)

I started working on this lexer a few days ago.

**Comment by birkenfeld** [comment]
I'm closing all requests for lexers/formatters without a patch/PR.
