### ISSUE TITLE
new lexer request: Oracle Utilities Rules Language

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#617]
(Original issue 910 created by jjacobson on 2013-09-27T19:40:50.054097+00:00)

Rules Language is used in Lodestar, now acquired by Oracle, to develop rate schedules and riders in the Utilities industry.

**Comment by Anteru** [comment]
(Original comment by jjacobson on 2013-09-27T19:42:03.669437+00:00)

I'll make an attempt to add the support myself.  But I'm new to Pull Requests and proper "etiquette" on this repo.

**Comment by Anteru** [comment]
(Original comment by tshatch on 2016-06-01T22:34:28.449295+00:00)

(Sorry I didnt notice this sooner) yes, feel free to send a pull request.

**Comment by birkenfeld** [comment]
I'm closing all requests for lexers/formatters without a patch/PR.
