### ISSUE TITLE
new lexer request: ttcn3

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#625]
(Original issue 918 created by None on 2013-10-18T23:58:42.928405+00:00)

Please add to ttcn3 support, It's used in communicating systems. Quite nice and common. Why? http://www.ttcn-3.org/files/ETSI_TTCN3_Tutorial.pdf, and for better quality of phone call :)))

**Comment by birkenfeld** [comment]
I'm closing all requests for lexers/formatters without a patch/PR.
