### ISSUE TITLE
code-block table should be wrapped in a `<div>` tag

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#632]
(Original issue 925 created by None on 2013-11-11T02:14:41.552192+00:00)

In the document of [HtmlFormatter](http://pygments.org/docs/formatters/#htmlformatter), there is an example output snippt when `linenos` option is set to `"table"`. In this example, the `<table>` tag is wrapped in a `<div>` tag with `"highlight"` class.

But current implementation doesn't output the wrapper `<div>`. It generates a bare `<table>` tag with class `"<cssclass>table"`.

Without the wrapping `<div>`, it's hard to styling the table. Say, you cannot easily limit the height of table and make a scroll bar when the number of lines is too large.

I hope that the wrapper `<div>` could be, at least, generated by some configuration.

**Comment by Anteru** [comment]
(Original comment by calfzhou on 2013-11-11T03:16:23.401856+00:00)

Checked the history of `html.py`. In the earliest version, the `<table>` is wrapped by a `<div>`, but [commit 6c43f98](https://bitbucket.org/birkenfeld/pygments-main/diff/pygments/formatters/html.py?diff2=6c43f98f156b&at=trunk) removed the `<div>`.

Looking forward to get the `<div>` back.

You could give the wrapper `<div>` a `width: 100%; overflow: auto;` style, then the whole table could be scroll-able. At least, linenos can vertically scroll with code content. Without the div, I have no idea to limit the table's height and make the two columns scroll synchronously.

**Comment by lilydjwg** [comment]
There is issues with width too, i.e. long lines stretch the table a lot and no scroll bars. I see that MediaWiki instead uses `linenos=inline` and then replaces those numbers with css pseudo elements to avoid being selected. In that way long lines are wrapped.

**Comment by Jean-Abou-Samra** [comment]
Not sure why this issue got auto-closed while the PR is still open ...
