### ISSUE TITLE
new lexer request: brightscript (roku)

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#638]
(Original issue 931 created by maxpete on 2013-11-22T01:03:36.819472+00:00)

Brightscript is the language used in writing Roku apps.

The file extension for brightscript is *.brs.

Here are some examples of implemented brightscript:
https://github.com/computmaxer/roku-hdhomerun

https://github.com/plexinc/roku-client-public

**Comment by birkenfeld** [comment]
I'm closing all requests for lexers/formatters without a patch/PR.
