### ISSUE TITLE
Ruby highlight as comment

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#727]
(Original issue 1020 created by djstrong on 2014-07-26T07:13:45.788873+00:00)

Wrong highlight: http://pygments.org/demo/483258/

**Comment by Anteru** [comment]
(Original comment by tshatch on 2014-10-07T04:57:36.283805+00:00)

In the languages that have regex literals, this is a losing battle.  Punting to 2.1, maybe I'll have some time then to revisit specific examples.

**Comment by kurtmckee** [comment]
This may have been fixed already (unfortunately no code was included so I'm guessing what the problem was).

![image](https://user-images.githubusercontent.com/39996/92313931-fc955780-ef96-11ea-9150-251246a2221c.png)
