### ISSUE TITLE
new lexer request: MaxScript (3dsmax)

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#732]
(Original issue 1025 created by davestewart on 2014-08-14T18:55:32.857767+00:00)

Hi there,

Not sure if it's the done thing to request support for new languages here, but Ivan from GitHub suggested in a support email that I try.

The language in question is **MaxScript**, the scripting language of [autodesk 3dsmax](http://www.autodesk.co.uk/products/3ds-max/overview).

The Language reference is here: [http://docs.autodesk.com/3DSMAX/16/ENU/MAXScript-Help/index.html?url=files/GUID-6FC81BE7-58FF-4C63-8362-0BDCFA9F904C.htm,topicNumber=d30e122065](http://docs.autodesk.com/3DSMAX/16/ENU/MAXScript-Help/index.html?url=files/GUID-6FC81BE7-58FF-4C63-8362-0BDCFA9F904C.htm,topicNumber=d30e122065)

If someone could let me know if that's the way to do it, or if I should attempt to find someone myself who could help with this, that would be great.

Many thanks,

Dave

**Comment by Anteru** [comment]
(Original comment by jokermartini on 2016-08-18T12:51:49.093605+00:00)

Could we get this implemented, github has it now. as well as sublime text editor.

**Comment by birkenfeld** [comment]
I'm closing all requests for lexers/formatters without a patch/PR.
