### ISSUE TITLE
new lexer request: cycript

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#753]
(Original issue 1046 created by tyilo on 2014-10-21T05:53:34.565011+00:00)

The cycript language is a hybrid of Objective-C and JavaScript.

Official website: http://www.cycript.org/

**Comment by kurtmckee** [comment]
This lexer request is six years old, and for a language that appears to have stalled development several years ago.

I recommend closing this ticket due to its age.

**Comment by Anteru** [comment]
Well spotted!
