### ISSUE TITLE
Bash highlighting

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#836]
(Original issue 1129 created by Fusion809 on 2015-07-20T17:42:55.831284+00:00)

Hi, 

I use pygments via the MediaWiki extension [SyntaxHighlight GeSHi](https://www.mediawiki.org/wiki/Extension:SyntaxHighlight_GeSHi) and I've noticed that while pygment bash syntax highlighting highlights `yum` and `apt-get` without issue, it does not highlight for other package managers `dnf`, `emerge`, `equo`, `pacman`, `rpm`, `urpmi` and `zypper`. I am here to suggest that this feature be added. I am a programming noob, especially when it comes to Python so I'm kind of just hoping, almost begging that someone will make this change to pygment for me. 

Thanks for your time,
Brenton

**Comment by Anteru** [comment]
(Original comment by tshatch on 2015-10-17T02:15:53.357564+00:00)

Can you provide an example that demonstrates this well?  I don't find special-casing for either `yum` or `apt-get` in the lexer as of 2.0.2.

**Comment by Anteru** [comment]
(Original comment by tshatch on 2016-06-01T20:48:26.036592+00:00)

@Fusion809 ping for example

**Comment by Anteru** [comment]
(Original comment by sseb35 on 2018-02-21T12:45:46.072134+00:00)

I cannot speak for @Fusion809, but there is a similar issue on MediaWiki tracker [T105817](https://phabricator.wikimedia.org/T105817) where the previous backend GeSHi highlighted differently the programs in command line (see screenshots in the link). This is partly linked to coulours and tastes ([there's no accounting for taste](https://fr.wiktionary.org/wiki/des_go%C3%BBts_et_des_couleurs,_on_ne_discute_pas)).

**Comment by fusion809** [comment]
Not of particular concern to me anymore, as I don't use MediaWiki on a personal server anymore.

**Comment by Anteru** [comment]
Unclear what the problem is and no repro case, closing. If this is an ongoing problem, please file a new issue with a repro case.
