### ISSUE TITLE
Improvement to MATLAB detection (including patch)

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#856]
(Original issue 1149 created by anntzer on 2015-09-18T23:44:54.342124+00:00)

There are a few issues about MATLAB and ObjC being confused.  I would suggest adding the following lines at the beginning of MATLAB's `analyse_text`:
```
        if next(line for line in text.splitlines()
                if not re.match('^\s*%', text)).strip().startswith('function'):
            return 1. # detects function declaration.
```

**Comment by birkenfeld** [comment]
this was done in #1271
