### ISSUE TITLE
new lexer request: openscad

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#886]
(Original issue 1179 created by None on 2015-12-12T08:29:59.807507+00:00)

Hello,

Can you add an openscad lexer ?

Thank you.

**Comment by Anteru** [comment]
(Original comment by tshatch on 2016-06-01T20:39:10.167376+00:00)

Yes.

**Comment by Anteru** [comment]
(Original comment by traverseda on 2018-08-20T16:32:53.662838+00:00)

Any movement on this? It would be nice if someone who already has experience creating lexers could take a crack at it.

**Comment by birkenfeld** [comment]
I'm closing all requests for lexers/formatters without a patch/PR.
