### ISSUE TITLE
Allow Custom Lexers and Formatters to be specified from the CLI

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#893]
(Original issue 1186 created by tprynn on 2016-01-04T22:02:02.865446+00:00)

Our organization uses pygments for highlighting, and would like to be able to write and use a simple custom lexer. This lexer is extremely situational and it doesn't seem to be the kind of thing that would be desirable to include with pygments itself. Instead, we would like to distribute it as a file, which users could then reference from the command line when highlighting:

```
#!bash

pygmentize -L ./custom-lexer.py -f latex -o out.tex code.py
```

Putting off the details for a minute, is this something which is possible and desirable for Pygments? Is there an easier way to get this result? It seems like the other way to have a custom lexer/formatter is to modify Pygments itself (not reasonable for our users).

If this is useful, I would be happy to contribute to Pygments to make it happen. All the details are really up for discussion, but the end-goal would be to make it as simple as possible to use a custom lexer/formatter.

**Comment by Anteru** [comment]
(Original comment by birkenfeld on 2016-02-02T10:02:48.121254+00:00)

Yes, I would add support for this. Can you make a prototype as a PR?

**Comment by Anteru** [comment]
(Original comment by tprynn on 2016-02-04T01:49:56.609817+00:00)

I'm on it.

**Comment by Anteru** [comment]
(Original comment by tshatch on 2016-06-01T20:38:07.521296+00:00)

There was also suggestion to highlight arbitrary keywords/operators/etc... could you detail what you envision custom-lexer.py looking like?

**Comment by Anteru** [comment]
(Original comment by tprynn on 2016-06-02T01:01:36.020644+00:00)

There's a simple example in the pull request: https://bitbucket.org/birkenfeld/pygments-main/pull-requests/559/custom-lexer-formatter-file-loading/diff#Ltests/support/html_formatter.pyT1

The custom lexers/formatters are *exactly* the same as the lexers and formatters which pygments already uses. So you can easily take an existing lexer, subclass it, and extend it with some functionality. Or make your own from scratch. If you copy one of pygment's lexers to your working directory, and include it with the correct cli flags, it will "just work".

**Comment by birkenfeld** [comment]
PR was merged.
