### ISSUE TITLE
C++11's decltype wrongly highlighted

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#907]
(Original issue 1200 created by None on 2016-01-26T16:50:07.238823+00:00)

Please see http://pygments.org/demo/3560316/
Shorter version here:

```
#!C++
constexpr decltype(1) x = 1;

void f() noexcept
{
    constexpr decltype(1) x = 1;
}
```

Please note that both decltypes are highlighted differently.

**Comment by Anteru** [comment]
(Original comment by Anteru on 2019-06-22T19:19:45.805971+00:00)

Looks like the first `decltype` is treated as a function, and from then on everything goes downhill.

**Comment by Anteru** [comment]
Fixed, doesn't reproduce any more.

**Comment by blu-base** [comment]
I can confirm, this does not seem to be an issue anymore. Both decltype have the same token, `Keyword`

Is there a reason not to close this?

**Comment by Anteru** [comment]
I probably just forgot to close, thanks for spotting this!
