### ISSUE TITLE
[Regression] Lexer name "emacs-lisp" undefined as of v2.1

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#914]
(Original issue 1207 created by Krinkle on 2016-02-03T22:26:32.823574+00:00)

In the v2.1, a new Emacs Lisp lexer was added. It moved the mapping for "elisp" and "emacs" from CommonLisp to EmacsLisp, but dropped "emacs-lisp" in the process.

Related:

* https://bitbucket.org/birkenfeld/pygments-main/commits/811926b573b7#chg-pygments/lexers/_mapping.py
* https://bitbucket.org/birkenfeld/pygments-main/issues/976/add-short-name-for-emacs-lisp

**Comment by Anteru** [comment]
(Original comment by birkenfeld on 2016-02-03T22:42:19.536825+00:00)

Thanks for the report!

**Comment by Anteru** [comment]
(Original comment by birkenfeld on 2016-02-03T22:42:21.735954+00:00)

Closes #1207: add back "emacs-lisp" alias for Elisp lexer.

→ <<cset 19090b01054e>>

**Comment by birkenfeld** [comment]
interesting, this issue should be closed...
