### ISSUE TITLE
Ansys APDL lexer

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#955]
(Original issue 1248 created by None on 2016-06-21T11:30:16.990347+00:00)

Hi,

As requested by another user on github
https://github.com/gpoore/minted/issues/109
I would like to also support the development of this APDL (ansys parametric design language) lexer for pygmentize.
Thank you for your time and consideration

Best
Andre

**Comment by Anteru** [comment]
(Original comment by camilstaps on 2016-06-24T12:18:09.335590+00:00)

See http://pygments.org/faq/#i-want-this-support-for-this-language.

**Comment by averter** [comment]
Commit [b872095ed5c7c71ae119bb4e04bdf70689cc2336](https://github.com/pygments/pygments/commit/b872095ed5c7c71ae119bb4e04bdf70689cc2336) should now close this.

**Comment by Anteru** [comment]
Indeed! Thanks for the notification!
