### ISSUE TITLE
Add 58 kewords to LLVM lexer in lexers/asm.py  to match LLVM 4.0 and 'token' type

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#970]
(Original issue 1263 created by GorNishanov on 2016-07-25T23:04:31.439378+00:00)

The following keywords are present in top of tree LLVM (LLVM4.0) and missing from the LLVM section of lexers/asm.py.

Also,  'token' type is missing from the type table for LLVM.

The list obtained by diffing the keywords from asm.py and https://github.com/llvm-mirror/llvm/blob/master/lib/AsmParser/LLToken.h .

'allocsize',
'amdgpu_cs',
'amdgpu_gs',
'amdgpu_kernel',
'amdgpu_ps',
'amdgpu_vs',
'any',
'anyregcc',
'argmemonly',
'avr_intrcc',
'avr_signalcc',
'caller',
'catchpad',
'catchret',
'catchswitch',
'cleanuppad',
'cleanupret',
'comdat',
'convergent',
'cxx_fast_tlscc',
'deplibs',
'dereferenceable',
'dereferenceable_or_null',
'distinct',
'exactmatch',
'externally_initialized',
'from',
'ghccc',
'hhvm_ccc',
'hhvmcc',
'ifunc',
'inaccessiblemem_or_argmemonly',
'inaccessiblememonly',
'inalloca',
'jumptable',
'largest',
'local_unnamed_addr',
'minsize',
'musttail',
'noduplicates',
'none',
'nonnull',
'norecurse',
'notail',
'preserve_allcc',
'preserve_mostcc',
'prologue',
'safestack',
'samesize',
'source_filename',
'swiftcc',
'swifterror',
'swiftself',
'webkit_jscc',
'within',
'writeonly',
'x86_intrcc',
'x86_vectorcallcc',

**Comment by Anteru** [comment]
(Original issue was assigned to birkenfeld)

**Comment by Anteru** [comment]
(Original comment by GorNishanov on 2016-07-26T04:51:37.249744+00:00)

removed dangling "as in:"

**Comment by Anteru** [comment]
(Original comment by GorNishanov on 2016-07-26T23:23:59.632582+00:00)

Pull request with the fix is here: https://bitbucket.org/birkenfeld/pygments-main/pull-requests/630/llvmlexer-added-58-keywords-and-token-type/diff

**Comment by birkenfeld** [comment]
PR was merged.
