### ISSUE TITLE
vim lexer hangs

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#971]
(Original issue 1264 created by bmarkhor on 2016-07-26T08:49:29.772057+00:00)

VimLexer hangs on this file:

https://github.com/chewZ/dotvim/blob/master/view/~%3D%2BArchivio%3D%2BSviluppo%3D%2Btxt%3D%2Bselect_utenze_script_exec.sql%3D

**Comment by birkenfeld** [comment]
fixed by #1312
