### ISSUE TITLE
Scala lexer incorrectly highlights code containing type parameters

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#972]
(Original issue 1265 created by acieroid on 2016-07-26T14:21:37.111928+00:00)

See the following fragment: http://pygments.org/demo/5862224/ (repeated below for completeness)
Code appearing after a trait definition with a type parameter is incorrectly highlighted.

```
#!scala


// Incorrect highlighting (on `case`)
trait Foo[A]
case class Foo1(x: A) extends Foo
// Correct highlighting
case class Foo2(x: A) extends Foo

// Incorrect highlighting (on `extends`)
trait Bar[A] extends Foo[A]
// Correct highlighting
trait Bar extends Foo
```

**Comment by Anteru** [comment]
(Original comment by acieroid on 2016-08-04T09:41:39.001634+00:00)

The source of the problem is the following. When encountering a class/trait definition, pygments will go to the 'class' token of ScalaLexer. If no type parameter is given, the last clause will occur, and pygments will '#pop' the current state, going back to the 'root' token. It can then successfully parse the rest of the code. However, if a type parameter is given, it goes to the 'typeparam' token, which will parse the type parameter until the ']', and then come back to the 'class' token. If no braces are given, as in the example above, then the 'class' token expects the name of the class to appear, and that is why 'case' and 'extends' in the example above are incorrectly highlighted (because they're detected as Name.Class instead of Keyword).
To confirm this, we can see that in the 'class' token, there is a clause for single comments (added to fix issue #713), but not for multiline comments. What does it give when we use them after a type parameter?

```
#!scala
trait Foo[A] /* comment comment comment */
```
As expected, it doesn't highlight correctly.
I don't know how to cleanly fix it. I guess that typeparam should pop twice instead of just once.
The quick and dirty solution is to add clauses from 'root' to 'class', as was done for single line comments, but that's not clean.

**Comment by Anteru** [comment]
(Original comment by dscorbett on 2016-08-04T13:44:32.795591+00:00)

How about this?
```diff
diff -r e79a7126551c pygments/lexers/jvm.py
--- a/pygments/lexers/jvm.py	Thu Jun 16 19:10:37 2016 +0200
+++ b/pygments/lexers/jvm.py	Thu Aug 04 09:41:24 2016 -0400
@@ -264,8 +264,7 @@
             # method names
             (r'(class|trait|object)(\s+)', bygroups(Keyword, Text), 'class'),
             (r'[^\S\n]+', Text),
-            (r'//.*?\n', Comment.Single),
-            (r'/\*', Comment.Multiline, 'comment'),
+            include('comments'),
             (u'@%s' % idrest, Name.Decorator),
             (u'(abstract|ca(?:se|tch)|d(?:ef|o)|e(?:lse|xtends)|'
              u'f(?:inal(?:ly)?|or(?:Some)?)|i(?:f|mplicit)|'
@@ -300,15 +299,16 @@
         ],
         'class': [
             (u'(%s|%s|`[^`]+`)(\\s*)(\\[)' % (idrest, op),
-             bygroups(Name.Class, Text, Operator), 'typeparam'),
+             bygroups(Name.Class, Text, Operator), ('#pop', 'typeparam')),
             (r'\s+', Text),
+            include('comments'),
             (r'\{', Operator, '#pop'),
             (r'\(', Operator, '#pop'),
-            (r'//.*?\n', Comment.Single, '#pop'),
             (u'%s|%s|`[^`]+`' % (idrest, op), Name.Class, '#pop'),
         ],
         'type': [
             (r'\s+', Text),
+            include('comments'),
             (r'<[%:]|>:|[#_]|forSome|type', Keyword),
             (u'([,);}]|=>|=|\u21d2)(\\s*)', bygroups(Operator, Text), '#pop'),
             (r'[({]', Operator, '#push'),
@@ -318,16 +318,21 @@
             (u'((?:%s|%s|`[^`]+`)(?:\\.(?:%s|%s|`[^`]+`))*)(\\s*)$' %
              (idrest, op, idrest, op),
              bygroups(Keyword.Type, Text), '#pop'),
-            (r'//.*?\n', Comment.Single, '#pop'),
             (u'\\.|%s|%s|`[^`]+`' % (idrest, op), Keyword.Type)
         ],
         'typeparam': [
-            (r'[\s,]+', Text),
+            (r'\s+', Text),
+            include('comments'),
+            (r',+', Punctuation),
             (u'<[%:]|=>|>:|[#_\u21D2]|forSome|type', Keyword),
             (r'([\])}])', Operator, '#pop'),
             (r'[(\[{]', Operator, '#push'),
             (u'\\.|%s|%s|`[^`]+`' % (idrest, op), Keyword.Type)
         ],
+        'comments': [
+            (r'//.*?\n', Comment.Single),
+            (r'/\*', Comment.Multiline, 'comment'),
+        ],
         'comment': [
             (r'[^/*]+', Comment.Multiline),
             (r'/\*', Comment.Multiline, '#push'),
```

**Comment by Anteru** [comment]
(Original comment by acieroid on 2016-08-04T13:48:23.328248+00:00)

This seems to be the clean fix indeed! I tested it and it works as expected.

**Comment by Anteru** [comment]
(Original comment by igaltabachnik on 2019-08-11T10:41:07.167708+00:00)

I’m very very sorry for bumping this old thread, but I just ran into the same issue \(still happens in 2.4.2\), and the patch indeed solves it \(even in the latest version\).

Was there ever a pull request sent for this? If not, I can perhaps send it myself?

**Comment by Blaisorblade** [comment]
@hmemcpy I guess igaltabachnik is you? I've sent a PR (#1314) with that patch, I hope that helps. But I haven't tested it much yet.

**Comment by hmemcpy** [comment]
Yep, that's me! I don't think I ever got an answer to why this wasn't merged... I ended up forking pygments, applying the patch, and using the patched version directly in my nix setup (for the book). The patch works great, btw, haven't seen any other issues. But I also haven't tested it much...

**Comment by Blaisorblade** [comment]
Should there be anything else in your fork (guess not), can you post a link? I can only offer https://github.com/pygments/pygments/pull/1315 :-)

**Comment by hmemcpy** [comment]
Oh wow, thanks!
