### ISSUE TITLE
CHARACTER SET isn't recognized on MySQL lexer

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#975]
(Original issue 1271 created by dereckson on 2016-07-29T00:20:08.320023+00:00)

As a sample, here the instructions for Etherpad encoding:

```
#!mysql

ALTER DATABASE `etherpad` CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
ALTER TABLE `etherpad.store` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
```

Expected behavior: CHARACTER SET and CONVERT TO CHARACTER SET receive the same highlighting

Actual behavior: CHARACTER received the class k, SET the class kt

**Comment by kurtmckee** [comment]
I am working to overhaul the MySQL lexer. I will _try_ to improve this behavior but note that "CHARACTER" and "SET" in the `lex.h` file in MySQL's source code never appear together. They are defined as separate keywords so it is highly likely that my PR will have them both rendered as the same token type, with nothing explicitly connecting them in the Pygments lexer.

I will consider this closed in my PR if CHARACTER and SET share the same token type.
