### ISSUE TITLE
docs bug - registering new styles

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#980]
(Original issue 1276 created by jcorneli on 2016-08-16T18:46:51.178115+00:00)

I've written a new file icky.py as a variant of default.py in the styles directory but when I install pygments (`sudo python setup.py install`), I don't see the new "icky" style in the list of available styles (`./pygmentize -L styles`).

The documentation says that all I need to do is "drop it in the *styles* subpackage".  But that's somewhat unclear.  What's really needde is to add the style to `__init__.py`:

```
#!python
    ....
    'arduino':  'arduino::ArduinoStyle',
    'icky':  'icky::IckyStyle'
```
Perhaps you can add this to http://pygments.org/docs/styles/

**Comment by flywire** [comment]
It is described in https://pygments.org/docs/styledevelopment/#creating-own-styles but it's not clear:

>  * or drop it into the styles subpackage of your Pygments distribution one style class per style, where the file name is the style name and the class name is _StylenameClass_. For example, if your style should be called "mondrian", name the class _MondrianStyle_, put it into the file mondrian.py and this file into the pygments.styles subpackage directory.
