### ISSUE TITLE
Some pull requests and issues cluttering the BitBucket UI

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#981]
(Original issue 1277 created by miikkas on 2016-08-24T08:42:44.096532+00:00)

There seem to be multiple pull requests and reported issues authored by Németh Orsolya – most probably by some kind of accident – that don't concern Pygments. The PRs and issues clutter the UI of BitBucket, though, so I think they should be removed.

[Here are the PRs](https://bitbucket.org/birkenfeld/pygments-main/pull-requests/?state=OPEN&author=nagy12)
and [here](https://bitbucket.org/birkenfeld/pygments-main/issues/1270/does) and [here](https://bitbucket.org/birkenfeld/pygments-main/issues/1267/generated) are the issues I could find.

**Comment by birkenfeld** [comment]
Bitbucket is gone, this should not be relevant anymore.
