### ISSUE TITLE
Add TYPO3s Typoscript

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#995]
(Original issue 1291 created by haaarp on 2016-10-12T17:02:39.254902+00:00)

TYPO3 is an Enterprise Content Management System with it´s own configuration language "Typoscript". With no skills in python myself please can somebody help me. You find the XMLs for Typoscript in notepad++ here: [https://www.d-mind.de/fileadmin/user_upload/downloads/Syntax-Highlighting-fuer-Notepad__.zip](Link URL).

**Comment by birkenfeld** [comment]
TypoScript lexer was new in 2.2.
