### ISSUE TITLE
C++ Unicode identifiers

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#998]
(Original issue 1294 created by mickk on 2016-10-24T01:40:04.372130+00:00)

C++11 has some support for the use of Unicode in identifiers:

```c++
int main()
{
    double \u03B1 = 1.0;
    α += 1;
    return \u03B1;
}
```

It appears Pygments [doesn’t like that](http://pygments.org/demo/6310561/).

Breakdown by lines:

 - lines 3 and 5: individual Unicode code points can be specified in the source as `\uNNNN` or `\UNNNNNNNN`, much like they can be inside string literals -- the spec calls them 'universal character names'
 - line 4: compilers map characters that fall outside of the usual a-zA-Z0-9 etc. to their UCNs, hence a literal `α` in the source is effectively the same as having `\u03B1` which is how we're referring to the variable we introduced on line 3

There's also a bunch of rules to prohibit ill-formed Unicode, the use of non-letter-like symbols in identifiers, and digit-like symbols at the start of identifiers. [cppreference](http://en.cppreference.com/w/cpp/language/identifiers) has some resources on the topic, although it's not authoritative and I haven't double-checked it myself.

To the best of my knowledge Clang has support for this ([Coliru demo](http://coliru.stacked-crooked.com/a/f554b1e4968a99fc)), GCC has partial support (only UCNs, no mapping).

**Comment by TrGameFn** [comment]
Today all contemporary compilers have full support for Unicode: https://godbolt.org/z/h5TMvv

Pygments still doesn't like them.
